### ISSUE TITLE
Laravel conflict with dd();

### ISSUE THREAD

**Issue by dragonfire1119** [kint-php/kint#101]
Laravel 4 has dd(). So I actually use dd() allot so when I'm working with laravel I have to use `d(true); die();` witch is not bad but I always like to save time. So I suggest to make it to ddk();.

What I did to fix this. https://github.com/raveren/kint/pull/102

**Comment by raveren** [comment]
I've already commented on the pull request, and here:

http://testandheiberg.tumblr.com/post/58148680627/using-kint-with-laravel-4

is a simple workaround.

**Comment by dragonfire1119** [comment]
@raveren The link is broken. Have you figured out a way to make this work with Laravel 4?

**Comment by barryvdh** [comment]
Maybe put kint before laravel in your composer file.

**Comment by dragonfire1119** [comment]
@barryvdh Thanks for the reply but it didn't work @raveren put on the dd() function where it checks and sees if theres another function with the same name before it calls. Laravel already has a dd() by default and that means Kint never gets called.

I made a pull request witch adds ddk() and it worked just fine for me but every time he updates Kint I have to go put my edit back.

**Comment by barryvdh** [comment]
Make a helper function in your own project, that calls the Kint class/method, instead of adding it to the kint vendor files.
Also, working link: http://andheiberg.tumblr.com/post/58148680627/using-kint-with-laravel-4

**Comment by dragonfire1119** [comment]
@barryvdh I didn't think about creating my own function in my project. Thanks. I went to the link and deleted my vendor then reinstalled everything put the Kint above Laravel and it didn't work. You would think it would work though?

**Comment by DanielHudson** [comment]
The following worked for me with Laravel 4.2.
1. Put Kint first in composer.json
2. Delete vendor & composer.lock
3. Composer install

Another option is apparently to adjust `autoload_files.php` - looks a bit dirty to me though!

http://www.stillat.com/blog/2014/05/14/getting-kint-to-work-with-laravel-4-1/

**Comment by dragonfire1119** [comment]
@DanielHudson Thanks for trying to help but didn't work laravel `dd()` still takes over for some reason. Kint is installed first also.
