### ISSUE TITLE
Kint Javascript and CSS code after closing </html>

### ISSUE THREAD

**Issue by borfast** [kint-php/kint#103]
I just noticed that when using Kint with Laravel and its default Blade templating engine, Kint outputs a `<script>` and a `<style>` tag after the closing `</html>` tag. Is there a way to move Kint's code to be inside `<html>...</html>`?

**Comment by raveren** [comment]
er, which version are you using? The WIP branch outputs code to handle AJAX requests with kint output in them.

Either way I can't see why would this be an issue, and I'm closing it unless you can convince me there's something wrong with it, sorry.

**Comment by borfast** [comment]
I'm using the WIP branch.
First reason that comes to mind is that it makes a page's HTML invalid.

**Comment by raveren** [comment]
well, if you're pushing development code into production, there's more problems than the HTML validity. 

It's a development tool, and the featureset is first and foremost priority, all modern browsers render the page properly in any case so there's no apparent drawbacks.

**Comment by borfast** [comment]
Granted. I would also prefer not to push kint onto production. Do you have any suggestion on how to do that using Laravel and composer? I had already tried putting kint under `require-dev` instead of `require` in `composer.json` but if I recall correctly, it didn't work. To be honest, I didn't spend much time around the issue, so perhaps I should try that again.

But I still maintain my suggestion: if at all possible, kint should output its code inside `<html></html>`.

**Comment by imkane** [comment]
@raveren - I don't understand why you think it's ok for you tool to put code outside of 

```
</body></html>
```

I've never seen any other tool do this, ever.  Why would you not think this is a problem?  And shouldn't it be an easy fix?

**Comment by raveren** [comment]
@imkane: I explained my reasoning already. 

There is no fix but to disable ajax features, which I'm going to make opt-in anyway.
