### ISSUE TITLE
d() JS is split over two lines

### ISSUE THREAD

**Issue by ptim** [kint-php/kint#104]
Hi! I've been using Kint succesfully for a while but have just found that the JS execution is failing with: 
`Uncaught SyntaxError: Unexpected token ILLEGAL`

The line in question is split over two lines:

```
if("undefined"===typeof kintInitialized){kintInitialized=1;var f=[],g=-1,h=function(b,a){"undefined"===typeof a&#038;&(a="kint-show");return RegExp("(\\s|^)"+a+"(\\s|$)").test(b.className)},k=function(b,a){"undefined"===typeof a&#038;&(a="kint-show");j(b,a).className+=" "+a},j=function(b,a){"undefined"===typeof a&#038;&(a="kint-show");b.className=b.className.replace(RegExp("(\\s|^)"+a+"(\\s|$)")," ");return b},l=function(b){do b=b.nextElementSibling;while("dd"!==b.nodeName.toLowerCase());return b},m=function(b,a){var c=
l(b);"undefined"===typeof a&#038;&(a=h(b));a?j(b):k(b);1===c.childNodes.length&#038;&(c=c.childNodes[0].childNodes[0],h(c,"kint-parent")&#038;&m(c,a))},n=function(b,a){var c=l(b).getElementsByClassName("kint-parent"),d=c.length;for("undefined"===typeof a&#038;&(a=h(b));d--;)m(c[d],a);m(b,a)},p=function(b){var a=b,c=0;b.parentNode.getElementsByClassName("kint-active-tab")[0].className="";for(b.className="kint-active-tab";
```

I haven't seen this before - am I doing something wrong?

Sorry, I don't have live a page online where this can be seen (its on a local wordpress site, which isnt very portable) but I've pasted a cut down version here: https://gist.github.com/ptim/77c2ec70f32d08eb3130#file-kint-html-L24

I did a search in issues and SO, but couldn't find any relevant results…

Thanks, Tim

**Comment by ptim** [comment]
PS, I tried with plain string to see if some of the object contents were bad, but still got the same issue..

`d('plain');`

**Comment by raveren** [comment]
Hey, ptim. I've been on a long-ass holiday and only now returning to developing Kint, I've just pushed a maintenance release to the [wip branch](https://github.com/raveren/kint/tree/1.0.0-wip). Could you please try using that and report whether the problem persists?

**Comment by ptim** [comment]
Thanks for the speedy response!

I've included the 1.0.0-wip branch and I get the same issue (like the idea of the open in new window stuff, though!)..

I've tried d() on other pages, and it works fine! I reckon I've identified the context for the error, though:

`d()` is working in one template file, but not another, and when the call fails the script is getting wrapped with `<p>` and there's a `<br>` after the `</script>`…

At a guess I'd say that it's being passed through `wpautop()` http://codex.wordpress.org/Function_Reference/wpautop.

I did try `remove_filter( 'the_content', 'wpautop' );` to no avail, and it seems that a WP filter could be applying wpautop() anywhere!  I had a dig through the woocommerce folder, but couldn't find the instance I was looking for.

Here are some relevant links:
- http://stackoverflow.com/questions/21279693/php-woocommerce-removing-p-tag-from-string
- http://wp-types.com/forums/topic/view-template-with-raw-output-still-uses-wpautop-adds-p-and-br-tags/

I guess the point of wpautop is to sanitise scripts, so this is a 'feature' :)

I'll close the case, and you can reopen if you think there's more to be done - thanks!

**Comment by raveren** [comment]
Oh that sucks, from what I'm getting, the auto-p script splits huge lines into smaller ones and wraps text in `<p>`. Why would it do that to `<script>` tag contents is beyond me. 

What you could try is open `/view/compiled/main/kint.js` and try placing a new line at character number 525, since the cutoff is there in the example you provided. If that works, I could compress the js in the future with longest-single-line limit.

**Comment by ptim** [comment]
wpautop is may be a blunt instrument :)

The longest line I have in the compiled kint.js is 518 characters, but i went and added a newline after each `;` and it still failed with and ILLEGAL.. added a JS comment in between lines and the comment got a `</p>` appended :)

No worries - I'll have to go lo-tech (var_dump) or higher-tech (xdebug)..

Thanks for Kint! :+1:

**Comment by raveren** [comment]
I would really like to get to the bottom of this. I can now also see the js has a `#038;` inserted between ampersands. So the solution is here:

http://stackoverflow.com/questions/6195635/is-breaking-the-page-in-wordpress

The culprit may some dumb bullshit called `wptexturize`, could you try to disable it?

There's also this: http://wordpress.org/plugins/kint-debugger/ but it's a little outdated, should still work though.

**Comment by ptim** [comment]
Thanks @raveren - I tried both plugins, but the first only operates on the content field - not sure what the hook is for the data at the point it's being passed around (though it had some effect)...
https://gist.github.com/c1562fdf8ef4d44519a6

Didn't install the Kint plugin, but had a quick squiz, and it doesn't particularly do anything but include the code, so I'd say it will have the same issue as I'm having now - thanks for checking it out - I just need to work around it for now...

Thanks again! Tim

**Comment by raveren** [comment]
Wow, that's a terrible mess, I'll look into proper WordPress integration when I have the time, thank you very much for the feedback and your time, ptim!

**Comment by ptim** [comment]
my pleasure - Kint rocks
