### ISSUE TITLE
Make the theme a modifier for Kint

### ISSUE THREAD

**Issue by jose-sa** [kint-php/kint#105]
I would like to quickly distinguish different debugging calls by means of its color. 

Info messages could use the original theme where error messages would use a reddish tone.

This could be easily possible if Kint supported an easy way to change the theme on runtime.

**Comment by raveren** [comment]
Unfortunately, kint is not currently designed for having multiple themes on a single page, and available modifiers are beginning to become scarce. Neither was kint designed for custom information delivery to the user along with variable data.

I have built a robust error handler that integrates Kint, but it's not ready for outsourcing just yet, meanwhile you might be interested in something like http://filp.github.io/whoops/.

I'm putting down this request to my private todo list for kint:

> Add a way to distinguish dumps, for example append a warning [icon](http://one-div.com/) to a specific dump or color it differently. Accomplish via custom shorthands when ready.
