### ISSUE TITLE
Using custom aliases, won't print variable names

### ISSUE THREAD

**Issue by dcorb** [kint-php/kint#106]
We are in the middle of integrating Kint with Devel (the most used Drupal debugging module) See https://drupal.org/node/2034919 or integration-code https://drupal.org/node/2034919

There is a pain point:
- We are already using `dd` alias, so the Kint alias won't work. If we create a custom alias, for example `kint()`, it won't print the variable name, because Kint checks this by comparing the callee to 'd' or 'dd' . Hard-coded here: https://github.com/raveren/kint/blob/7220259ffb228626d29dc4143738a8d4e7c8c31f/Kint.class.php#L390
  This pull request: https://github.com/raveren/kint/pull/99 fixes this partially. Do you have a better way? or ideas of helping us here?

Would be possible to have a custom Kint config option to name which function names should be considered as debugger functions?

I think that will be the cleanest work-around.
Thank you

**Comment by raveren** [comment]
Hi there, thanks for the integration work, I've already (partially) amended this in the [wip branch](https://github.com/raveren/kint/blob/1.0.0-wip/Kint.class.php). Could you try using that?

It's perfectly stable, though the always enabled auto-ajax features might not be for everyone, I just pushed a release with this as opt-in.

Please feel free to ask any questions, I'll help you in every way possible.

**Comment by raveren** [comment]
In the mean time, I'm closing the issue, but we can continue to communicate on any related matters here.
