### ISSUE TITLE
dd() fails when $_SERVER['DOCUMENT_ROOT'] is not set

### ISSUE THREAD

**Issue by andylolz** [kint-php/kint#108]
Laravel provides a CLI in which `$_SERVER['DOCUMENT_ROOT']` is not set.

This causes a problem here:
https://github.com/raveren/kint/blob/master/Kint.class.php#L294
…because `$path` == `$_SERVER['DOCUMENT_ROOT']` == `''`

The following exception is thrown:

```
strpos(): Empty needle
```

**Comment by raveren** [comment]
Thanks, I pushed the fix to the WIP branch

https://github.com/raveren/kint/tree/1.0.0-wip

I'm hoping to merge it to master within a month.

**Comment by andylolz** [comment]
Fix looks good to me. Thanks!

**Comment by barryvdh** [comment]
This fix doesn't work for me. I had to change it to this:

```
$_kintSettings['appRootDirs'] = isset( $_SERVER['DOCUMENT_ROOT'] ) && $_SERVER['DOCUMENT_ROOT']
    ? array( $_SERVER['DOCUMENT_ROOT'] => '&lt;ROOT&gt;' )
    : array();
```

Apparently DOCUMENT_ROOT returns true on isset(), but is just empty..

Also, is this possible to fix on the 0.9 branch, or are there no more releases for that?

**Comment by raveren** [comment]
I have redone configuration from the ground up an will include the fix when
work is done.

You can just use empty i stead of isset btw.

**Comment by BobRupholdt** [comment]
Ran across this problem today.  Since I don't need/want kint enabled for CLI, I changed the enabled function to:

```
    public static function enabled( $value = null )
    {
        ### kludge to disable kint in CLI
        if ( empty($_SERVER['DOCUMENT_ROOT'] ) ) return false;

        # act both as a setter...
        if ( func_num_args() > 0 ) {
            self::$enabled = $value;
            return;
        }

        # ...and a getter
        return self::$enabled;
    }
```
