### ISSUE TITLE
search keys in huge arrays/objects

### ISSUE THREAD

**Issue by raveren** [kint-php/kint#11]
http://code.google.com/p/kint/issues/detail?id=24

**Comment by rodrigoaguilera** [comment]
Is there a way to search all kind of content?

I miss that from search_krumo https://www.drupal.org/project/search_krumo

**Comment by raveren** [comment]
You can doubleclick on the plus sign next to any node and it expands _all_ nodes - CTRL+F away.

This might be implemented at a later date, but there's literary hundreds of features with higher priority unfortunately.

**Comment by neoscopio** [comment]
Code for search is now done. https://www.drupal.org/project/search_kint 
Could it be integrated as a plugin? Basically you just have to output the .js and .css files

**Comment by jnvsor** [comment]
@neoscopio How does this compare to https://github.com/jnvsor/kint/tree/2.x-dev feature wise?

**Comment by neoscopio** [comment]
@jnvsor Not sure if I understand you correctly, but main thing is a search box, and bonus is a "copy variable".
From what I see in your link that's not available.

1000 words:
https://www.drupal.org/files/project-images/search_kint_3.png

**Comment by jnvsor** [comment]
Path getting is in 2.x-dev: ![](https://camo.githubusercontent.com/4a9b6c7f649899fe04b05d60b0288b7490fe3ba4/687474703a2f2f692e696d6775722e636f6d2f797a6b4559546c2e706e67)

Is your path getting done in javascript? 2.x-dev would be a bit more robust then (Handles things like name transforms and keys/properties with unprintable characters without breaking the path)

Took a look at the code for the search thingy. Looks for a `dt:contains(query)` and uses CSS to hide all the others right? Sweet. How hard do you think that would be to get working without jquery? How hard would it be to embed it in the result itself to reduce screen realestate use?

**Comment by jnvsor** [comment]
@raveren Nearly 5 years later but the preliminary version is looking good:

![screen shot 2018-05-19 at 10 30 12](https://user-images.githubusercontent.com/5260644/40266653-ac7f91e4-5b4f-11e8-81e0-8256faab54d7.png)

**Comment by jnvsor** [comment]
Pushed in bfdd22471510c9066e873475a6da9027f8a42cfd

**Comment by raveren** [comment]
You rock dude, I am away again from active development, glad to see Kint is in such skilled and buisy hands!
