### ISSUE TITLE
Disable automatic timestamp interpretation

### ISSUE THREAD

**Issue by Jakobud** [kint-php/kint#113]
For some weird reason, whenever I dump a integer that very vaguely looks like some sort of unix timestamp, Kint decides it's going to automatically give me the human readable form of that timestamp, even though I didin't ask it to.

![image](https://cloud.githubusercontent.com/assets/87356/2771224/43c2a762-ca68-11e3-82ab-06c0efa06cb7.png)

How do I disable this?

**Comment by raveren** [comment]
Hey there, unfortunately disabling alternative data displays are not supported right now - save for deleting the alternate parser itself, but it will pop up again after updating Kint.

The one you're interested in is 
https://github.com/raveren/kint/blob/master/parsers/custom/timestamp.php

You can either delete it or just ignore the extra information. Configuration for alternate parsers is not in the plans as of yet, sorry...
