### ISSUE TITLE
Improve CLI output

### ISSUE THREAD

**Issue by igorsantos07** [kint-php/kint#116]
After installing Kint into my machine I've started using it with the PHP consoles as well... And I noticed that even with `s()` (text-only) it still outputs some HTML (`<pre>`).

Is it possible to identify which environment the code is being running into (not sure about this) and then trim HTML from what's outputted?

**Comment by raveren** [comment]
The WIP branch already does this, but thanks.

**Comment by igorsantos07** [comment]
Good to know :))
