### ISSUE TITLE
Solution for cannot redeclare class kintParser

### ISSUE THREAD

**Issue by lufias** [kint-php/kint#117]
Im using v 0.9.. and i found this error. "cannot redeclare class kintParser in kint/parsers/parser.class.php".. the problem is that kintParser trying to extend kintVariableData which is not yet declared.. the soution is simply to swap the position of class of kintParser and kintVariableData which are both on the same file; parser.class.php. Sorry i dont know how to make a pull/fix request.

**Comment by rtconner** [comment]
How is this not the most important bug on the planet to fix? It makes Kint completely unusable.

**Comment by efalder413** [comment]
Pull request created to fix this issue.
https://github.com/raveren/kint/pull/126

**Comment by jmulans** [comment]
Hi, why this fix is not merged in master branch ?
I have the same problem

**Comment by raveren** [comment]
The fix is included in master:

https://github.com/raveren/kint/commit/2739ca607099d9b92676eda47f9ea23705d37c97#diff-831b64e6a2f31153d251d17799642f03L8

are you using the recommended composer settings:

``` json
"require": {
   "raveren/kint": "^1.0"
}
```

and/or the latest release/master HEAD?

**Comment by jmulans** [comment]
I was using the master, I've switched on ^1.0 and it's now good for me.
Sorry for the inconvenience.

**Comment by raveren** [comment]
what do you mean by using the master? I'm still fumbling around with composer, was this my fault, can I fix it somehow?

**Comment by jmulans** [comment]
I was using this : 

"require": {
   "raveren/kint": "master"
}

that's pretty weird cause I still have the problem. It tells me that kintParser is declared twice in parsers/parser.php

**Comment by raveren** [comment]
So you're having it again? 

I'm assuming this is because you use a tool that uses an another version of Kint - which does not include the multiple inclusion check..

Can you help me debug this?

**Comment by jmulans** [comment]
I don't use another version of Kint
But the PR #126 fix my problem. This one is not included in the master

**Comment by raveren** [comment]
woah, that's random, you sure? ok, I'll do that.

**Comment by jmulans** [comment]
Yes I'm sure. Thanks

**Comment by raveren** [comment]
Could you please point your `composer.json` to master `HEAD` and see if the problem persists? If my changes fix it, I'll do a release.

**Comment by jmulans** [comment]
seems good to me !
