### ISSUE TITLE
Disable JS and CSS output when not needed

### ISSUE THREAD

**Issue by benjamw** [kint-php/kint#118]
I have Kint included in my php.ini file for all scripts run on my dev server.  Because of this, Kint javascript is output at the bottom of AJAX and other text-only output which will break the script receiving that output, even if there were no traces or debugs in the script.

I understand that AJAX sniffing is now an option, but it would be nice if Kint only output the relevant JS and CSS when it's needed because a debug or a trace was actually called.

**Comment by raveren** [comment]
Hey, thank you for the interest and contributing, I appreciate it a lot!

You see, there is no knowing whether an ajax call will be made after page load, so the code must be present in every rendered page to handle said background calls. Kint attempts to guess when it's not needed, i.e. when the current request itself is ajax, when it delivers non-html content etc - however all of this relies on the developer to send adequate headers (which IMO he is required to do anyway).

I can't believe I've not pushed the patch that makes the ajax feature opt-in (as opposed to on by default as it is) yet, but it's done and won't hassle users who do not want it and ask for it specifically.

I've been tied up in my daily routine but I'm slowly and steadily improving Kint, I hope to release the whole batch of changes to bring it up to 1.0 stable in the coming month.
