### ISSUE TITLE
your link for Drupal integration isn't working

### ISSUE THREAD

**Issue by holtzermann17** [kint-php/kint#120]
http://raveren.github.io/kint/#integration points to https://drupal.org/sandbox/fat763/2021241 - doesn't work, but
https://www.drupal.org/sandbox/fat763/2155159 is a working link.

**Comment by alexander-danilenko** [comment]
I'm author of Drupal module. 
That's correct, old sandbox moved to new for a few reasons related to commit log and not GPL licensed code in commit history.

**Comment by raveren** [comment]
fixed, thanks!
