### ISSUE TITLE
Pane Will Not Toggle By Default

### ISSUE THREAD

**Issue by cdaringe** [kint-php/kint#121]
Hello:

In my env, it seems as though the toggling of the kint pane does not work.  If I prefix my Kint::dump() with a ! per the instructions, it does render fully expanded.  Can you lend some tips as to the mechanism for which this is supposed to trigger the expansion toggle?
![screen shot 2014-07-08 at 11 10 11 pm](https://cloud.githubusercontent.com/assets/1003261/3520445/1ed993ac-0730-11e4-87a0-ec99e7672c6b.png)
![screen shot 2014-07-08 at 11 10 49 pm](https://cloud.githubusercontent.com/assets/1003261/3520446/1ed9f09a-0730-11e4-8a1d-ab2942dc2244.png)

**Comment by raveren** [comment]
Hey there, sorry for the late reply, I am going to need the source of the page you are seeing, but I am pretty sure that simply the existing javascript in the page clashes with kint even though I've yet to come across such a situation. 

Kint's JS is designed to be as unintrusive as possible, it should work no matter what. I'm gessing there's an invisible overlay on the page or something.

**Comment by cdaringe** [comment]
No worries!  Agreed--we are known to have some funky JS activity happening during page load.  Perhaps you can just point me to the lines where you setup your event binding, and I can do some initial debugging

**Comment by raveren** [comment]
I can see you're using the stable `master` branch, I'd advise you to switch to the `1.0.0-wip` and see if the problem persists. 

The event handler attaches a click event listener to the whole document and it processes the target element to see whether it belongs to Kint.

Anyway, I closure-compile the js code before pushing, so it might be a difficult fix for you to make, it'd be much easier IMO if you could just send the generated HTML page to me so I can debug it myself...

**Comment by cdaringe** [comment]
Great, I'll give the wip branch a shot.  Now that you explain it, I bet it's our (poor) pagination system.  We run all of our js in an iframe then copy our content over to the page :(.  Don't ask why!  I bet the click handler is only active in the iframe pane?  Will update or share some code in a bit.

**Comment by raveren** [comment]
Hey again, I'm sorry, but I'll have to close this unless you come up with something reproduce-able. Please let me know if I can help in any other way.
