### ISSUE TITLE
Unable to include project from http://cdn.rawgit...

### ISSUE THREAD

**Issue by mateuszjarzewski** [kint-php/kint#123]
Why I can't just do this.
I'm asking seriously.

``` php
require 'http://cdn.rawgit.com/raveren/kint/master/Kint.class.php';
Kint::dump($_SERVER);
```

**Comment by raveren** [comment]
This is not Kint-related, this question should be better off directed to StackOverflow, as I would never do this solely because of security implications.

**Comment by mateuszjarzewski** [comment]
You are wrong on this one. Saving time by portability of code is crucial.
Your security argument is just stupid, there is no security risk here.

**Comment by raveren** [comment]
:)

**Comment by mateuszjarzewski** [comment]
What are you laughing at, buddy?

**Comment by raveren** [comment]
Just go away, sad boring person.
