### ISSUE TITLE
Impossible to copy results out to text editor

### ISSUE THREAD

**Issue by mateuszjarzewski** [kint-php/kint#124]
It comes out messy as hell,
I believe there could be done a tremendous optimization of html code in order to improve text editor output.

**Comment by raveren** [comment]
Thanks for the feature suggestion, I was considering adding native PHP compatible dump output (similar to var_export), but this will definitely have to wait as there are many much more burning issues open :/

**Comment by raveren** [comment]
This seems redundant now that there is a proper white space output and structure access to node #194 is finished and being tested.
