### ISSUE TITLE
Choose which tab to open by default dynamically.

### ISSUE THREAD

**Issue by adityamenon** [kint-php/kint#127]
I am using Kint in conjunction with POSTMan to explore some of the functions offered by my Laravel REST API. POSTMan does not support JS in the rendered view, so when I try to click on the 'available methods' tab nothing happens.

I really like and make use of the modifiers feature, I use `+` regularly to easily browse. But I want a modifier that allows which tab to open by default as well. Is this possible to implement?

**Comment by raveren** [comment]
Hey, I'm glad you find kint useful! There might be several ways to accomplish this, can you add css to the POSTMan output? If so, the rule you need is

``` css
.kint ul:not(.kint-tabs) > li:not(:first-child) {
    display: block; /*this value is 'none' in kint css*/
}
```

this would show the tab contents below eachother, would that do?

If POSTMan allows no such thing, before calling kint you can 

``` php
echo "<style>.kint ul:not(.kint-tabs) > li:not(:first-child) display: block !important;}</style>";
```

The suggested workaround is plainly because I don't see a _user-friendly_ way to add the option (technologically it's simplish) and am a little afraid of feature-hell for obscure single-user-affecting issues, however I'm open to suggestions and keep an open mind if you'd like to persuade me either way :)

**Comment by adityamenon** [comment]
I would like to have this! I understand your concern about feature hell. It's also true that this is a little obscure. But I think people who do need this will end up appreciating it a lot :) It's not too hard to imagine environments where JS doesn't work or doesn't work well. You could either allow a new modifier for this, or do something like `Kint::noJSDump()`...

**Comment by raveren** [comment]
There's actually a html-enhanced minimal, no-js version of kint output; could you try out `sd(1);`, you'll be given a text-only trace.

The rich view with no JS actually makes little sense, it's the same information (except there's no source tab in text view) - just more cluttered. What do you think?

**Comment by adityamenon** [comment]
Sorry, but this is not enough :( I already use dd() when working in Laravel
which actually shows better output (especially because I have xdebug
installed usually). Would definitely have preferred what I asked for
earlier...

On Tue, Aug 12, 2014 at 3:15 PM, Rokas Šleinius notifications@github.com
wrote:

> There's actually a html-enhanced minimal, no-js version of kint output;
> could you try out sd(1);, you'll be given a text-only trace.
> 
> The rich view with no JS actually makes little sense, it's the same
> information (except there's no source tab in text view) - just more
> cluttered. What do you think?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/raveren/kint/issues/127#issuecomment-51893777.

## 

sincerely,

## aditya menon

http://twitter.com/adityamenon90

**Comment by raveren** [comment]
I've improved plain trace output formatting A LOT:

```
┌──────────────────────────────────────────────────────────────────────────────┐
│                                    TRACE                                     │
└──────────────────────────────────────────────────────────────────────────────┘
1:  ROOT/cake/dispatcher.php:99
────────────────────────────────────────────────────────────────────────────────
2:  APP/config/bootstrap.php:133
    Dispatcher->dispatch()
    ─────────────────────────── Callee object ──────────────────────────────────
    Dispatcher (4) (
        public base-> bool FALSE
        public webroot-> string "/"
        public here-> string "/<REDACTED>/"
        public params-> array (7) [
            'controller'=> string "<redacted>"
            'named'=> array (0)
            'pass'=> array (0)
            'action'=> string "index"
            'plugin'=> NULL
            'form'=> array (0)
            'url'=> array (0)
        ]
    )
────────────────────────────────────────────────────────────────────────────────
3:  APP/webroot/index.php:4
    require(
        $file = string "APP/config/bootstrap.php"
    )
════════════════════════════════════════════════════════════════════════════════
Called from ROOT/cake/dispatcher.php:99
```

and it's colored in the style of xdebug if in HTML or CLI, so I'm closing this for now, but I do have plans making things like visible tab in trace and other obscure options customizable on the fly. It will have to wait though.

**Comment by adityamenon** [comment]
Cool, thanks for your efforts Rokas.
