### ISSUE TITLE
Namespaces polluting the output

### ISSUE THREAD

**Issue by ninboy** [kint-php/kint#131]
Sometimes you need to define a proxy function because you can check in one place is a script or not is in "debug" mode, but when you call Kint functions through a proxy function, and the proxy function is named as a Kint default function, the namespaces and headers of the caller file will pollute the output. See attached screenshot:

![screenshot from 2014-09-16 08 47 39](https://cloud.githubusercontent.com/assets/34670/4287672/01a39a98-3da5-11e4-8210-b24559db5315.png)

Steps to reproduce:
Create a simple file, proxy.php

``` php
<?php
namespace Proxy;

class Proxy {
    private static $isDebugMode = true;
    public static function d($var){
        if(self::$isDebugMode) \Kint::dump($var);
    }
}
```

and a caller.php

``` php
<?php
namespace Caller;
include("proxy.php");
use Proxy\Proxy;

function output(){
    // Do something
    // ...
    Proxy::d(true);
}
output();
```

If you use another name for Proxy::d() it will not pollute the caller function but the "Called from" part of the output will always be the proxy function.
![screenshot from 2014-09-16 09 16 04](https://cloud.githubusercontent.com/assets/34670/4288030/7012a25a-3da8-11e4-8124-9f5aedafaf79.png)

If you use "d" as the name (To bypass the proxy function as defined on https://github.com/raveren/kint/blob/v0.9.1/Kint.class.php#L390) then the "called from" part is going to be useful, but the output "header" will be almost unreadable.
![screenshot from 2014-09-16 09 15 38](https://cloud.githubusercontent.com/assets/34670/4288038/84a18c68-3da8-11e4-98c5-b583ffd9fe1a.png)

**Comment by raveren** [comment]
Wow, thanks for the detailed report, so much work went into it, I really appreciate that!

However, please try using the wip branch as I cannot reproduce the issue on it with your provided steps:

https://github.com/raveren/kint/tree/1.0.0-wip

**Comment by ninboy** [comment]
Hi raveren,

I just tested the wip branch and it doesn't pollute the namespace anymore. And the new way to show the callers trace is good enough to not need to bypass the proxy function. Do you have any information about the next release? Sadly I cannot use composer dev dependencies on my project
