### ISSUE TITLE
[CLI] strpos(): Empty needle

### ISSUE THREAD

**Issue by ruudk** [kint-php/kint#132]
Whenever I run `d($var)` inside a unittest or Symfony2 console command I get the following error:

```
strpos(): Empty needle
/vagrant/vendor/raveren/kint/Kint.class.php:294
```

When I go to that function I see that it loops the `self::$appRootDirs` array. For me, that contains:

```
array(1) {
  [""]=>
  string(12) "&lt;ROOT&gt;"
}
```

``` php
        foreach ( self::$appRootDirs as $path => $replaceString ) {
            $path = str_replace( '\\', '/', $path );

            if ( strpos( $file, $path ) === 0 ) {
                $shortenedName = $replaceString . substr( $file, strlen( $path ) );
                break;
            }
        }
```

Because the key of the array is empty, `strpos` fails.

The following code fixes it:

``` php
        foreach ( self::$appRootDirs as $path => $replaceString ) {
            $path = str_replace( '\\', '/', $path );

            if ( !empty($path) && strpos( $file, $path ) === 0 ) {
                $shortenedName = $replaceString . substr( $file, strlen( $path ) );
                break;
            }
        }
```

**Comment by ruudk** [comment]
Kint doesn't work nicely in CLI anyway. It dumps HTML.

**Comment by raveren** [comment]
Could you please see if the issue is fixed in the wip branch:

https://github.com/raveren/kint/tree/1.0.0-wip

**Comment by raveren** [comment]
Oh and thanks for the detailed issue report, I'm so very happy that such talented and friendly people use Kint.

Anyway, the wip branch is closing completeness, I'm hoping to release RC1 in the following week. If you use CLI, you'll be happy to see that Kint will now detect that automatically and even use CLI colors when available. 

The github version might be a little rough around the edges, but its actually less buggy than the .9 stable and I did a lot of work in my local version, which I'm going to publish shortly...

Stay tuned :)

**Comment by ruudk** [comment]
Tx! I will test it out next week :)

**Comment by raveren** [comment]
I'm assuming it works now, I just have to push out the RC finally :/
