### ISSUE TITLE
can't toggle debug info when an array includes \n

### ISSUE THREAD

**Issue by leo108** [kint-php/kint#134]
the dump code is `Kint::dump(array('data' => "\n"));`

when click '+' , it will cause a js error `Cannot read property 'className' of undefined`

**Comment by leo108** [comment]
This is caused at `view/js/_kint.js` line 69 `parent = parent.childNodes[0].childNodes[0];`, if the dump data only has "\n", browser consider that `pre` tag doesn't have childNodes,  `parent.childNodes[0].childNodes.length` equals 0, so `parent` becomes undefined.

I find a tricky solution, at `decorators/rich.php` line 37, change `$output .= '<pre>' . $kintVar->extendedValue . '</pre>';` to `$output .= '<pre><span>' . $kintVar->extendedValue . '</span></pre>';`, but I'm not sure whether it would cause other bug :)

**Comment by raveren** [comment]
thank you for the perfectly reproduceable issue and a ready solution, I changed the JS and will push the changes asap!
