### ISSUE TITLE
simplexml_load_string warning when passing a string with a relative xmlns

### ISSUE THREAD

**Issue by jb-lopez** [kint-php/kint#135]
I ran into this problem when parsing a string that contains an XML response.

Below is a minimal version of the code needed to cause the error.

``` php
$XML_String = "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<root xmlns=\"schema.xsd\"></root>\n";
d($XML_String);
```

PHP throws three warnings when I run the above code:

`Warning: simplexml_load_string(): namespace warning : xmlns: URI schema.xsd is not absolute in C:\xampp\htdocs\_includes\kint\parsers\custom\xml.php on line 9`

`Warning: simplexml_load_string(): &lt;root xmlns=&quot;schema.xsd&quot;&gt;&lt;/root&gt; in C:\xampp\htdocs\_includes\kint\parsers\custom\xml.php on line 9`

`Warning: simplexml_load_string(): ^ in C:\xampp\htdocs\_includes\kint\parsers\custom\xml.php on line 9`

I believe it's the same warning three times.  It does not alter the output of kint, the output is still correct.

Setting `$_skipAlternatives` in `kintParser` to a default of `true` solves my problem, since the data is a string.  This doesn't fix the issue though, and I thought you might want to know about it.

I ran this on php 5.4.27

**Comment by raveren** [comment]
Thanks for the excellent error report and reproduce-able code! I love working on Kint knowing it helps people like you :)
