### ISSUE TITLE
Proper way to include Kint in CMS's?

### ISSUE THREAD

**Issue by jscottelblein** [kint-php/kint#136]
I've placed the Kint folder in the root of my site (/home/mydomain/public_html/devtools/kint/Kint.class.php) so I can use it in whatever I'm working on.

I've directly added the `include_once` in a basic PHP file and tested it, and it worked great. I also removed the include from the file and added it in php.ini under `auto_prepend_file` which also worked.

However, whether I directly include or use auto_prepend in either one of my WordPress sites or Drupal sites, I just get a WSOD in either one of them. Even turning on error reporting via:

```
ini_set('display_errors', 1);
error_reporting(E_ALL|E_STRICT);
```

to try and troubleshoot why it's not working, results in no errors shown or logged, just a WSOD. In fact, I would prefer to keep it always enabled in php.ini but since it breaks my CMS's I have to disable it there.

Any suggestions?

Thanks!

**Comment by alexander-danilenko** [comment]
You can use my module for Drupal 7.x: https://www.drupal.org/sandbox/fat763/2155159

Also Kint (as one of my initiative) was added to 8.x branch of Devel module as replacement for Krumo that used in Devel module for Drupal 6.x - 7.x. So for Drupal 8.x you can use Kint out of box Devel module: https://www.drupal.org/project/devel

**Comment by raveren** [comment]
Fantastic, thanks, @fat763 :)

I'm terribly sorry I'm not more responsive about the configuration rework, I had to scratch one approach, and am constantly inventing a new and universal one, just life gets in the way a lot :(

**Comment by jscottelblein** [comment]
Thanks for the help @fat763 :) , unfortunately as far as my Drupal site goes, I'm still stuck back on D5 for a while (long story). Is there another way?

As for WordPress, I installed the Kint WP plugin, but that, from what I can tell by reading it, basically just redirects Kint's output into DebugBar. Currently, I'm working on a WP site and would like to get Kint going on that even more-so than my Drupal site (at least for the moment).

**Comment by raveren** [comment]
Could you try `error_reporting(-1);`? You are using the absolute path to include Kint, correct? Are you using the master or WIP branch? I suggest the WIP.

There's only one way to determine the reason for a WSOD. Place `die(__FILE__.' : '.__LINE__);` (unless you're somehow using earlier than PHP4.0.2 which introduced `__LINE__`) in `Kint.class.php`  - first at the beginning of the file, then after it's first action - probably `require` - and thus going further until you again see just the blank screen. Please do that and report what action breaks the excecution, perhaps I can work in a generic solution.

As for WordPress, I've never used it - the WP plugin is made by third parties and you _could_ try contacting the author, but sadly, I cannot help you right now as I've no experience with the framework.

I _will_ at some point consider rolling out my own compatibility plugins, but that won't come soon :(

**Comment by jscottelblein** [comment]
Hmmm, I just got something that might help.

I placed this at the top of the file (the only difference this time was that I placed the include directly after the error reporting lines; previously I had placed the error reporting lines at the top of the file, but the include way down under the exact function I was working in):

```
ini_set('display_errors', 1);
error_reporting(E_ALL|E_STRICT);

require_once('/home/mydomain/public_html/devtools/kint/Kint.class.php');
```

And when I tried to load the page I got this error:

`Fatal error: Cannot redeclare kintlite() (previously declared in /home/mydomain/public_html/mia/wp-content/plugins/kint-debugger/Kint.class.php:872) in /home/mydomain/public_html/devtools/kint/Kint.class.php on line 740`

Looks like some conflict with the WordPress Kint plugin. When I disable the plugin Kint shows up. I'll shoot the plugin dev a note about it. As far as Drupal breaking, I guess I'll cross that bridge when I get to it. =)

**Comment by raveren** [comment]
Just use the wip branch:

https://github.com/raveren/kint/tree/1.0.0-wip

I'm already feeling sorry and ashamed for the crap that is Kint @ master branch :) I'll update the official version as soon as possible.

**Comment by raveren** [comment]
Oh, but then you'll be stuck with the Kint version the plugin uses :/

Anyway, I'm closing this and just open a new issue when you get in trouble with Drupal :))

**Comment by jscottelblein** [comment]
Just tried the WIP version, with the plugin still disabled, and I get this error now: =)

`Parse error: syntax error, unexpected T_PAAMAYIM_NEKUDOTAYIM in /home/mydomain/public_html/devtools/kint/Kint.class.php on line 201`

I'm not even sure what language that is! LOL

**Comment by jscottelblein** [comment]
Ahh, double colon in Hebrew. =)

**Comment by raveren** [comment]
Yeah, I'm fixing it, could you tell me what PHP version are you on :)

**Comment by jscottelblein** [comment]
5.2.17

Again, due to still being stuck on D5. =/

**Comment by raveren** [comment]
fixed, try it now :)

**Comment by jscottelblein** [comment]
K, these now, lol

```
Warning: Unexpected character in input: '\' (ASCII=92) state=1 in /home/mydomain/public_html/devtools/kint/parsers/parser.class.php on line 409

Warning: Unexpected character in input: '\' (ASCII=92) state=1 in /home/mydomain/public_html/devtools/kint/decorators/rich.php on line 292

Warning: Unexpected character in input: '\' (ASCII=92) state=1 in /home/mydomain/public_html/devtools/kint/decorators/rich.php on line 293
```

**Comment by raveren** [comment]
Ok, I fixed them too, but these were actually needed when using Kint in error handling in later PHP versions.

When an exception occurs in a non-default namespace, the error handling code is executed in the same namespace - that's a bug of php5.4+ and to work around it, all error handling code must provide absolute namespaces for their class calls :/

Not that you need any of this information, but in case you're wondering, why they're there :)

**Comment by jscottelblein** [comment]
doh! It didn't like that ... WSOD now with no error messages. lol

**Comment by raveren** [comment]
I'd be really happy if you help me debug it again with the die statements :))

**Comment by jscottelblein** [comment]
ok, ill give it shot in a bit, heading out on lunch break. =)

**Comment by raveren** [comment]
nvm, I'll host a PHP5.0 version on my box and test it :)

**Comment by jscottelblein** [comment]
ok, I'm back, need any help with anything?

**Comment by raveren** [comment]
Nah, I'm finishing a 5.1+ compatible commit

**Comment by jscottelblein** [comment]
Well, I just tested and I don't get a WSOD until after line 90, in the enabled function.

**Comment by jscottelblein** [comment]
Ahh ok, (just saw your last comment).

**Comment by raveren** [comment]
There, I pushed a version with PHP5.1 compatibility, could you please test it? :)

**Comment by jscottelblein** [comment]
I get WSOD from this line now: `if ( class_exists( 'Kint' ) ) return;`

**Comment by raveren** [comment]
could you replace it with 

`if ( class_exists( 'Kint', false ) ) return;`

?

**Comment by jscottelblein** [comment]
ok, tried that as well and still WSOD.

**Comment by raveren** [comment]
ok, could you now try 

`if ( in_array( 'Kint', get_declared_classes(), true ) ) return;`

**Comment by jscottelblein** [comment]
WSOD with that as well. For the record, if I comment out that line entirely now, Kint appears to be working fine. =)

**Comment by raveren** [comment]
what's your setup, I want to get to the bottom of this, is it a generic Drupal site? Cause I even downloaded Drupal 5.0 and ran it on PHP5.1 and Kint works fine with 

`if ( !class_exists( 'Kint', false ) ) return;`

I would very much like to get to the bottom of this, could you please help me?

Can you just add 
`return;`
at the top of `Kint.class.php` - does that cause a blank screen?

Could you also tell me what does 
`echo"<pre>";var_dump(class_exists( 'Kint', false ));die;`
output?

Perhaps you are already using `ddd()` somewhere in your code that would otherwise throw a `Undefined function`, because the old version that is already incuded does not have this function..?

**Comment by jscottelblein** [comment]
ok, using `if ( !class_exists( 'Kint', false ) ) return;` works.

`return;` alone causes WSOD

`echo"<pre>";var_dump(class_exists( 'Kint', false ));die;` returns `bool(true)`

it looks like we might have our wires crossed a bit, lol, I have a D5 site that I also want to use Kint with (I want to use Kint on everything I code :)), but I'm currently working on a WordPress site, which is where I'm doing all of this testing. Originally it seemed that if Kint caused WSOD on one CMS (i.e. Drupal) it also caused WSOD in the other CMS as well (i.e. WordPress), so I'm just assuming it had to do with the Kint code, and once it's sorted out in one CMS it'll (hopefully, crossing fingers) automatically work in the other as well. =)

Would it help if I could try to set you up an admin account in a sandbox WordPress site I have going? I might be able to do that?

Update: Also, I haven't used any ddd() yet. just `d($_SERVER);` as a test.

**Comment by jscottelblein** [comment]
Also, just to make sure we're on the same page, I have the WP Kint plugin disabled this whole time during testing, to rule any issues with IT out, and focus on just getting Kint itself working. =)

**Comment by raveren** [comment]
> ok, using `if ( !class_exists( 'Kint', false ) ) return;` works.

so no blank screen? 

> `echo"<pre>";var_dump(class_exists( 'Kint', false ));die;` returns bool(true)
> where did you put this line? At the top of `Kint.class.php`? If so, could you see where else Kint is included by

`echo"<pre>";var_dump($reflection->getFileName ());die("\n".__FILE__.':'.__LINE__);`

What's your wordpress version :)? 

Yeah, your assumptions about Kint being the culprit of the WSOD's is correct, it shouldn't matter which CMS you're running, however this one `return` line causing issues is really weird, and could be caused by anything. I want to find out what so others don't experience it... Thanks again for helping me! :)

**Comment by jscottelblein** [comment]
Nope, no blank screen in that first one.

Yep, I'm putting that line at the very top of kint.class.php, replacing the original line each time I test. Line 8.

`echo"<pre>";var_dump($reflection->getFileName ());die("\n".__FILE__.':'.__LINE__);` returns these 2 errors:

```
Notice:  Undefined variable: reflection in /home/mydomain/public_html/devtools/kint/Kint.class.php on line 8

Fatal error:  Call to a member function getFileName() on a non-object in /home/mydomain/public_html/devtools/kint/Kint.class.php on line 8
```

My WordPress version is the latest 4.01. I always keep those up to date. and it's no problem, I'm happy to help, looking forward to using Kint once this is all ironed out. =)

**Comment by raveren** [comment]
Oh, I'm an idiot, sorry for the undefined variable notices.

However if the `if ( !class_exists( 'Kint', false ) ) return;` does work, we're done :)

Could you do the honors and go to

https://github.com/raveren/kint/blob/1.0.0-wip/Kint.class.php

click edit, and change the 8th line to add the `false` parameter to `class_exists` and make a pull request, so you'd be mentioned in the https://github.com/raveren/kint/graphs/contributors :))

**Comment by jscottelblein** [comment]
Thanks for taking the time yesterday to figure this all out for me, much appreciated!. :D

**Comment by raveren** [comment]
Why did you add the negation? I'm declining the pull request. Also, make the commit message "Disabled autoloading when checking for existing Kint versions". Or I can do it...

**Comment by jscottelblein** [comment]
Ya lost me, which negation?

All these comments: 
https://github.com/raveren/kint/issues/136#issuecomment-65692536
https://github.com/raveren/kint/issues/136#issuecomment-65694944
https://github.com/raveren/kint/issues/136#issuecomment-65699462

Said this worked: `if ( !class_exists( 'Kint', false ) ) return;`

Which is what I added for line 8. Either way, you can go ahead and just do it yourself, I don't mind.

**Comment by raveren** [comment]
Ah, I'm sorry, I misspoke, if `if ( !class_exists( 'Kint', false ) ) return;` works that means you have another of instance of Kint already included and that's the one that's being loaded first. The mentioned line yields true and `return` is executed and `Kint.class.php` is no longer processed.

If you're still in the mood, could you add 

```
$reflection = new ReflectionClass( 'Kint' );
echo"<pre>";var_dump($reflection->getFileName ());die("Called in \n".__FILE__.':'.__LINE__);
```

above the return statement - it will show you where was Kint included before. Is it the WP debug plugin or what?
