### ISSUE TITLE
Issue on console

### ISSUE THREAD

**Issue by hgati** [kint-php/kint#138]
I run on linux terminal.
![snap1](https://cloud.githubusercontent.com/assets/6913728/5574433/6b512dfc-9002-11e4-89e6-e5853392306c.jpg)

It is appended pre tag.

**Comment by raveren** [comment]
Hey, thanks for creating the issue, are you using the wip branch?

https://github.com/raveren/kint/tree/1.0.0-wip

all active development has moved there
