### ISSUE TITLE
Add an option to automatically expand ::dump() output

### ISSUE THREAD

**Issue by Alorel** [kint-php/kint#143]
It would be useful to have the ability to not have to click the output to expand it.

**Comment by raveren** [comment]
just prefix it with `!`: `!dd($GLOBALS)`

it's all in the documentation:
http://raveren.github.io/kint/#advanced

**Comment by Alorel** [comment]
Glorious, thanks. I _have_ read the docs, but somehow managed to miss that. Closing the issue now. :)
