### ISSUE TITLE
Support for accentuated character

### ISSUE THREAD

**Issue by GMartigny** [kint-php/kint#144]
Hello,

When trying to dump character with accent (éñô ...) they're not outputted at all. 

ex :

``` php
sd('e', 'é');
```

output :
string (1) "e"
string Windows-1252 (1) ""

It's the same whether it's in string, array key or object key.

``` php
sd(array('e'=>'en', 'é'=>'fr'));
```

output :
array (2) [
    'e'=> string (2) "en"
    => string (2) "fr"
]

**Comment by raveren** [comment]
thanks for spotting it, text encoding is a pain, sorry :/
