### ISSUE TITLE
Strings with significant (ex. timestamp) values are displayed outside of array

### ISSUE THREAD

**Issue by Steveb-p** [kint-php/kint#145]
I have run into an issue when trying to display an array containing timestamp values. I've checked it against version 0.9.1 (using 1.0) and there was no issue there, so I guess it's a regression introduced between those two.

Here are some screenshots presenting versions 1.0.0 and 0.9.1 accordingly. I believe they will prove to be selfexplanatory.

![kint100](https://cloud.githubusercontent.com/assets/3183926/7961816/22fa8698-0a0a-11e5-9c99-6b0d9749532b.jpg)

![kint091](https://cloud.githubusercontent.com/assets/3183926/7961820/27367ffa-0a0a-11e5-8682-b9f100465c8e.jpg)

Thanks for really great tool :)

**Comment by raveren** [comment]
good catch, thank you!!
