### ISSUE TITLE
Javascript spilled on screen

### ISSUE THREAD

**Issue by armababy** [kint-php/kint#147]
Hey,

How to fix this one?
http://i.gyazo.com/7dd9f134552a6f7e8e005972f587b9f5.png
http://i.gyazo.com/f5f7b3415189f458d4eee8cbd0526097.png

Single composer package + 1 php file.

Steps:

```
composer require raveren/kint
```

File:

```
<?php

require __DIR__ . '/vendor/autoload.php';

ddd(['monkeys', 'dogs']);
```

Looks like its server setup specific, tried on local everything works.
Server with problem: Nginx 1.8 + php-fpm 5.5.9

Anyone seen this?

**Comment by raveren** [comment]
Hey, thanks for the bug report, can you give me the page source that you're seeing? (<kbd>CTRL+U</kbd>)

**Comment by armababy** [comment]
@raveren sure [source](https://gist.github.com/armababy/0ac43fa9ccff9b779b34)
Tell me if i can do any tweaking on machine, got full access.

**Comment by raveren** [comment]
Thanks again, it's literally reporters like you that make Kint awesome :)

Anyway, you're getting some kind of newrelic.com javascript injection. A quick search revealed it's some kind of browser tracking platform and it adds tracking code _inside_ Kint javascript. 

https://gist.github.com/raveren/0f71aed7871dd95b43f1

Kint has a method that opens dumps in a new window when clicking on the small arrow

![clipboard01](https://cloud.githubusercontent.com/assets/364220/8022965/3cf9f890-0cfc-11e5-943b-aae7d3b9d934.png)

and Kint js has text `<meta charset="utf-8">` and `<body>` inside of it - the tracking injection detects that text and mistakenly injects its javascript at those two locations breaking Kint's js.

I am not really sure what can be done about this, I could mask the html tags from trivial detection by the script you're using, but it costs quite a lot of effort, my guess is it would get inserted either way and I wouldn't like to set a precedent where Kint is changed to be compatible with weird services that do hackish things.

IMO, you should not be running the newrelic functionality in development environment either way.

What are your thoughts?

**Comment by armababy** [comment]
Yeah i do have newrelic php app reporting on machine.
It's my playground and i have lots of stuff enabled there :)

Anyway regarding the matter, i do believe that this is not a fault of Kint, thank you very much @raveren for sorting this out so speedy.

For the reference of anyone getting this here are some materials to resolve issue.
[Official response of NewRelic staff - on the matter](https://discuss.newrelic.com/t/javascript-injection-is-causing-page-break/13862/3)
