### ISSUE TITLE
 PHP Fatal error: Cannot redeclare class kintParser

### ISSUE THREAD

**Issue by gregtampa** [kint-php/kint#151]
PHP Fatal error:  Cannot redeclare class kintParser in /var/www/html/kint/parsers/parser.class.php on line 4

**Comment by raveren** [comment]
Hey, you are including Kint twice, or it could be already included via composer and then again manually, or your framework or whatever you're using has it included already..

I can help you debug the problem if you provide me detail info, but this is definitely not Kint's fault so I'm closing the issue.
