### ISSUE TITLE
PHP Fatal error:  Cannot redeclare class kintParser 

### ISSUE THREAD

**Issue by BigL** [kint-php/kint#154]
I have pasted my message in this issue,

https://github.com/raveren/kint/issues/109

$ php -v
PHP 5.5.9-1ubuntu4.9 (cli) (built: Apr 17 2015 11:44:57) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with XCache v3.1.0, Copyright (c) 2005-2013, by mOo
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies
    with Xdebug v2.2.6, Copyright (c) 2002-2014, by Derick Rethans
    with XCache Optimizer v3.1.0, Copyright (c) 2005-2013, by mOo
    with XCache Cacher v3.1.0, Copyright (c) 2005-2013, by mOo
    with XCache Coverager v3.1.0, Copyright (c) 2005-2013, by mOo

**Comment by raveren** [comment]
although it's not directly kint's fault, the latest release fixes your error, but it might not be backwards portable, so different versions of kint that are included into the same source _might_ still cause problems.
