### ISSUE TITLE
composer require raveren/kint throwing error

### ISSUE THREAD

**Issue by samundra** [kint-php/kint#157]
I executed `composer require raveren/kint` in my terminal to include the kint but got the following RuntimeException and UnexpectedValueException. See below

```
[RuntimeException]                                                                                               
Could not load package league/oauth2-client in http://packagist.org: [UnexpectedValueException] Could not parse  
version constraint ^1.1: Invalid version string "^1.1" 
```

UnexpectedValueException

```
[UnexpectedValueException]                                              
 Could not parse version constraint ^1.1: Invalid version string "^1.1"
```

I am not sure if this is composer specific error or error in Kint module itself.
Also see the screenshot below of the error.

![composer_require_2](https://cloud.githubusercontent.com/assets/760855/8569044/340bba48-2593-11e5-9a69-c2abd9a90f89.png)

I then updated the require field manually and tried `composer update` but it also gave the same error.

![composer_raveren_kint_error](https://cloud.githubusercontent.com/assets/760855/8568998/da8c45f0-2592-11e5-8f9d-c5118758555e.png)

Thanks,

**Comment by raveren** [comment]
`league/oauth2-client` must be another entry in your `composer.json` as it has nothing to do with Kint, sorry. Can I help further?

**Comment by samundra** [comment]
Hi Raveren,

My composer seemed cracked somehow. I updated it with `composer self-update` and then everything worked as expected.

Sorry to bother you.

Thanks
