### ISSUE TITLE
WordPress kint plugin

### ISSUE THREAD

**Issue by phh** [kint-php/kint#158]
Hi there!

I have used kint in a plugin wrapper for some time now and finally I have released it as a plugin:

https://wordpress.org/plugins/pco-kint/

There is already a plugin marked for WordPress, but it has not been updated for a while. This plugin uses the latest version and I will try to keep this up to date with the Kint project.

Would you mind linking to the plugin in your "Using Kint with a framework" list?

Thanks!

**Comment by raveren** [comment]
I'm so thankful for this, but I don't have time to devote to Kint **at all** right now, I just drop in to fix bugs from time to time - and even _that_ is costing me immensely. 

I will _try_ to add this asap, but I can't promise anything at this point :/

**Comment by phh** [comment]
No rush and thank you for taking your time to reply here :)

**Comment by jnvsor** [comment]
Since there's pretty much nothing out there that supports kint 2.0 at this time, I'm closing the third-party-plugin documentation issues.

I probably won't add the list back until there are a decent few to list too.
