### ISSUE TITLE
Concrete5 Kint plugin

### ISSUE THREAD

**Issue by dorian-marchal** [kint-php/kint#159]
I made a Kint add-on for Concrete5 : http://www.concrete5.org/marketplace/addons/kint-debug
You can add it to your list, if you want.

Kint is awesome :+1:

**Comment by jnvsor** [comment]
Since there's pretty much nothing out there that supports kint 2.0 at this time, I'm closing the third-party-plugin documentation issues.

I probably won't add the list back until there are a decent few to list too.
