### ISSUE TITLE
error in a ZF2 project for d(1) invocation

### ISSUE THREAD

**Issue by countless-integers** [kint-php/kint#160]
Hi,
I'm getting a fatal error when invoking `d(1)` or `\Kint::trace()` in a Zend Framework 2 (2.5.1) project:

```
Fatal error: Call to a member function fetch() on null in /projectpath/vendor/zendframework/zend-db/src/Adapter/Driver/Pdo/Result.php on line 186
```

I'm using current Kint version. Any idea why something like that could happen? It's super weird, because it's grabbing some Pdo Result wrapper object.

Part of trace:

```
28  0.8160  25994064    Kint::dump( )   .../Kint.class.php:112
29  0.8317  26090872    call_user_func:{/projectpath/vendor/raveren/kint/Kint.class.php:217} ( )    .../Kint.class.php:217
30  0.8317  26091088    Kint_Decorators_Rich::decorateTrace( )  .../Kint.class.php:217
31  5.6956  44275304    kintParser::factory( )  .../rich.php:155
32  5.6957  44276408    kintParser::_parse_object( )    .../parser.class.php:115
33  5.8956  46207416    kintParser::factory( )  .../parser.class.php:471
34  5.8956  46208816    kintParser::_parse_object( )    .../parser.class.php:115
35  6.0217  47230784    kintParser::factory( )  .../parser.class.php:471
36  6.0217  47232048    kintParser::_parse_array( ) .../parser.class.php:115
37  6.3781  50045904    kintParser::factory( )  .../parser.class.php:379
38  6.3782  50047480    kintParser::_parse_object( )    .../parser.class.php:115
39  6.3815  50081280    kintParser::factory( )  .../parser.class.php:471
40  6.3815  50082936    kintParser::_parse_object( )    .../parser.class.php:115
41  6.3895  50206760    kintParser::factory( )  .../parser.class.php:471
42  6.3906  50217720    Kint_Parsers_objectIterateable->_parse( )   .../parser.class.php:132
43  6.3906  50217864    iterator_to_array ( )   .../objectiterateable.php:10
44  6.3906  50218184    Zend\Db\Adapter\Driver\Pdo\Result->rewind( )    .../objectiterateable.php:10
```

**Comment by raveren** [comment]
This one is a repeat offender, and thanks to the trace you provided, I could trace its origin, please try the latest commit and tell me if it works:

https://github.com/raveren/kint/commit/84807eb67af45f182636e7d34c6267e7f062f9ac

**Comment by countless-integers** [comment]
Thanks, it seems to do the trick -- now it loads. However ZF2 being ZF2 uses a gazylion objects and I must bump up php's memory limit to even see that trace (otherwise it crashes due to insufficient memory). `debug_backtrace()` also runs out of memory so I blame it on ZF2.

**Comment by raveren** [comment]
Yeah, I imagine Zend might do that. There's a sparsely documented feature of Kint, however, that allows printing alternative displays of data _instead_ of the usual parsing. 

There are a few examples of this included:

https://github.com/raveren/kint/tree/master/parsers/objects

While `splfileinfo` and `closure` make sense as more informative interpretations of specific objects - `smarty` (http://www.smarty.net/) is used for the single purpose of not hanging the browser when its object is dumped. I don't unfortunately use ZF2 so coming around to implementing zend-specific adapters will definitely not come soon - but you're always welcome to make pull requests :) 

The functionality is trivial even though a little inconsistent. Each `object` parser is passed every object Kint encounters and must either return `false` to skip **or** set `$this->name` and (optionally) `$this->value` to display inline - and return an array of tabs to be parsed and displayed below.
