### ISSUE TITLE
Multiple d($var);  on one line causes error!

### ISSUE THREAD

**Issue by ATouhou** [kint-php/kint#161]
Hi i just noticed that keeping multiple d($var)  in one line, will cause the display to echo the last variable name for all outputs so :
    d($day); d($month); d($year);
will display $year  handler for all d() outputs,  while  
    d($day); 
    d($month); 
    d($year);

will display it correctly.

Only the handlers info are wrong...

**Comment by raveren** [comment]
That's a known issue with no possible workarounds as I tokenize and parse the PHP code to get variable names - and I only get the line number and called function name. It's virtually impossible to distinguish which call is Kint processing.
