### ISSUE TITLE
Encoding problem

### ISSUE THREAD

**Issue by ymakux** [kint-php/kint#162]
Hello
Kint breaks page encoding. All text strings become unreadable. My php file has UTF-8 without BOM encoding. Same result when I used Krumo. Any ideas how to fix it?

**Comment by RomeroMsk** [comment]
I think I have the same problem too. When I call `Kint::dump()` from `Windows-1251`-encoded file, all Russian characters are unreadable. I see `Windows-1252` preffix in dump for these strings, so maybe problem is in wrong encoding detection.

**Comment by RomeroMsk** [comment]
Just found [this line](https://github.com/raveren/kint/blob/master/inc/kintVariableData.class.php#L35)...
If I change 'Windows-1252' to 'Windows-1251' [here](https://github.com/raveren/kint/blob/master/inc/kintVariableData.class.php#L32), my problem is going away. So, it is a dirty workaround for now.

**Comment by smartcorestudio** [comment]
The same problem with Cyrillic characters and UTF-8 encoding. This can be solved for example by commenting some lines in function `escape()` in file `parsers/parser.class.php`. But it's also a quite dirty fix

**Comment by raveren** [comment]
Oh my, this again :)

I fixed this issue (again): https://github.com/raveren/kint/commit/c8423b9928bd35bf6ad14c688ab9c6d17d97d0eb, but Windows-1251 is indistinguishable from Windows-1252 via the method I use (and it's the result of countless hours of research), so you have to either copy `config.default.php` to `config.php` in the same directory and change the `$_kintSettings['charEncodings']` key or add 

``` php
Kint::$charEncodings = array(
    'UTF-8',
    'Windows-1251',
    'euc-jp',
);
```

somewhere early in your app bootstrap process.

Is Windows-1251 the default encoding in Russian text editors?

**Comment by smartcorestudio** [comment]
Windows-1251 is the default encoding in apps like MS Office, Notepad etc. But I think nowadays most developers use UTF-8 in their projects.

**Comment by RomeroMsk** [comment]
Most developers use UTF-8, but Win-1251 is still in use by old projects :(
Thanks for the fix!

**Comment by ymakux** [comment]
"Is Windows-1251 the default encoding in Russian text editors?"
I'm using either Sumblimetext or Notepad++ which are not "russian". As I said all my files encoded in UTF-8. I just downloaded the master branch and the issue in still there. Never mind, it's not so important fo me. Thanks for your work!

**Comment by raveren** [comment]
@ymakux, could you please send me (raveren@gmail.com) a minimal single file that reproduces the problem?

**Comment by raveren** [comment]
@ymakux, will you be able to help me or can I close this?

**Comment by ymakux** [comment]
I finally solved this issue by changing file encoding from UTF-8 to UTF-8-BOM. I always use UTF-8-BOM in translation files but this time something gone wrong... So I can confirm the latest master branch works just fine!

**Comment by raveren** [comment]
Well that's weird, I thought utf8 with BOM was deprecated or something, Kint definitely works with UTF8, and if it doesn't for you, I'd love to get the troublesome file and debug the f*ck out of it :))

 I actually created a separate honey-pot issue ;)

https://github.com/raveren/kint/issues/172

**Comment by ymakux** [comment]
@raveren I'm currently writing a project with thousand of files. There are many templates/controllers/models/translations loaded on each request so it's difficult to figure out which one will useful for you :)
