### ISSUE TITLE
Disable table view for arrays

### ISSUE THREAD

**Issue by ymakux** [kint-php/kint#163]
Is there a way to display nested arrays without tables, just collapsible rows?

**Comment by raveren** [comment]
No, currently there is not. Why would you want that, what problem are you facing?

**Comment by ymakux** [comment]
It's confusing. At least for me :)

**Comment by raveren** [comment]
Well unless there's a real objective reason, I am seeking to avoid feature creep in Kint and will not add a configuration for this - at least for now.

**Comment by sebastiaanluca** [comment]
I suppose there's no configuration setting for this yet? Sometimes I want the structure to be more clearly visible and using a table to display array data gives an obscured view of it. If I wanted to compare it to another array that's not in a table, that would also be harder to do.

**Comment by jnvsor** [comment]
You'll be able to disable it in 2.x - if you're feeling brave you can experiment with this: 0c54549386acdc8825c608d0923b954c005fbdd4

**Comment by sebastiaanluca** [comment]
Thanks for letting me know :)
