### ISSUE TITLE
add support for Symfony 2.7

### ISSUE THREAD

**Issue by klepsydra** [kint-php/kint#164]
The current mention for integrating with the Symfony 2 framework suggests
https://github.com/barelon/CgKintBundle
with seems abandoned/outdated, forcing Kint into version `raveren/kint ~0.9` leading to its own set of issues (eg. the `strpos()` error).

Two notable areas I cannot seem to get my project to run at all, or at least cannot use Kint, is:
- in TWIG templates
- Running my Symfony 2.7 project from the CLI or cron jobs (extending `ContainerAwareCommand` ).  There, for the life of me, I cannot seem to successfully run `Kint::enabled(Kint::CLI);`  no matter what namespace I `use` or require (eg. `require dirname($_SERVER["SCRIPT_FILENAME"]) . '/../vendor/raveren/kint/Kint.class.php';`  )  nor what I put in composer.json (currently only `"raveren/kint": "dev-master"` ).  Nothing relevant is in `AppKernel.php` as there is no bundle to register for Kint.

**Comment by jnvsor** [comment]
Twig templates: Out of scope: This can be implemented by a third (or first) party plugin in [2.x-dev](/kint-php/kint/tree/2.x-dev). Please test and give feedback, thanks!

> I cannot seem to successfully run `Kint::enabled(Kint::CLI);` no matter what namespace I use or require

Kint is in the global namespace to support older PHP versions. It should work with `\Kint::enabled()`. Could you test and report back please?
