### ISSUE TITLE
Class redefinition error

### ISSUE THREAD

**Issue by schlessera** [kint-php/kint#165]
When I use two plugins that each use Kint through Composer, I get a class redefinition error upon activating the second plugin:

`Fatal error: Cannot redeclare class Kint in /srv/www/<mysite.com>/htdocs/wp-content/plugins/<myplugin>/vendor/raveren/kint/Kint.class.php on line 34`

Both plugins have Kint as a dev requirement.

**Comment by raveren** [comment]
I've already played around with `class_exists` and it occasionally fails in unpredictable ways, besides, older versions that are loaded _after_ the new one will fail regardless.

**Comment by schlessera** [comment]
Ok, that was one possible solution.
But the problem still remains. More & more WP plugins use composer to include dependencies, and they should be able to deal with scenarios like this.

**Comment by raveren** [comment]
That is a terrible situation, but there's noting I can do short of retroactively fixing the old versions - which AFAIK I cannot physically do...

The problems will persist until old plugins update their dependencies to point to a recent Kint version.
