### ISSUE TITLE
Kint output hidden behind Bootstrap fixed top

### ISSUE THREAD

**Issue by webcliq** [kint-php/kint#169]
A silly issue! But it prevents me from taking full advantage of Kint. Our new version of Cliqon CMS has a fixed-top Bootstrap nav bar in the Admin area. The Kint display is hidden behind that bar. I have tried various amendments to base.less but without success. Can you suggest a quick fix? Better still, implement a long term solution. For example, putting output in popup dialog would be good choice.

**Comment by raveren** [comment]
try `-ddd($yourAwesomeVariable);` - appending the minus sign clears previous output on the page.
