### ISSUE TITLE
remove deprecated dd()

### ISSUE THREAD

**Issue by dducro** [kint-php/kint#170]
Hey,

dd() is deprecated for a while now. But because it's still there, it overrides the Laravel 5 short dump.
Can you remove it please? So we can keep Kint in our projects.

**Comment by osapishchuk** [comment]
You can fork current version and remove it in your fork. In old versions of php is still working. I wish to not remove this function.

**Comment by raveren** [comment]
> it overrides the Laravel 5 short dump

does it? Cause Laravel 4 is the reason I deprecated the `dd` function to not clash as it was inaccessible either way.

Unfortunately, I cannot simply remove a function that's still used by lots of existing users - not without a major version change - and that will not be soon.
