### ISSUE TITLE
is there a way to reduce the information shown in string mode

### ISSUE THREAD

**Issue by vesper8** [kint-php/kint#179]
Sometimes I just want to output a string and not show the backtrace or var_dump info and it would be nice if I could activate a "mode" so that kint's d() and s().

Right now if I do 

```
$someVar = new stdClass();
$someVar->name = "test";

$string = "Variable name: " . $someVar->name;

d($string);
s($string);
```

 i get 

```
$string string(19) "Variable name: test"
┌──────────────────────────────────────────────────────────────────────────────┐
│                                   $string                                    │
└──────────────────────────────────────────────────────────────────────────────┘
string (19) "Variable name: test"
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
```

Is there a way to remove the "$string string(19)" part ?

Is there a way to remove that big rectangle in string mode? Or that black bar (whatever that is) ?

Maybe it's my config that's wrong but I find these extra things unhelpful and just taking up a lot of screen space when I'm trying to debug lists of strings.

I've tried enabling whitespace / cli / plain mode but none of those removed that extra info.

Please let me know if there's a way to temporarily disable all the extra traces.

Thanks!

**Comment by raveren** [comment]
Something along those lines was requested in #150, but it's not implemented yet unfortunately. 

If you just need to output a string why not just use `echo`?

**Comment by vesper8** [comment]
I don't use echo because then I have to add an html line break, and I have no easy way to turn debugging on and off unless I enclose the echo in an if statement.

I hope you can implement something like that. And I still don't understand why the kint's string output has to include all that extra stuff like the rectangle above and the black bar below. It should be on a single line at least. The string mode s() actually creates much more noise then the d() =/

**Comment by raveren** [comment]
> why the kint's string output has to include all that extra stuff

so it stands out, it _is_ debugging information, the focus is for the info to not get lost or be ambigous, visual aesthetics is second. And anyway, I'll be working on #150 which you'll be able to use in your situation...
