### ISSUE TITLE
Exclude dumping of objects of specific class

### ISSUE THREAD

**Issue by tinnerdxp** [kint-php/kint#185]
In Symfony2 or any other framework using dependency injection container - it would be great to be able to specify in the config that any reference to a class of a given instance should not be expanded.

**Comment by Steveb-p** [comment]
This would be great if classes/interfaces like Doctrine Proxy or Symfony Form could be excluded, especially from the iteration. Symfony form dissalows iteration on itself after construction as far as I'm aware, causing Kint to error out. In case of Doctrine Proxy, it causes loading of elements, which in a lot of cases would slow down the execution.

**Comment by jnvsor** [comment]
Implemented in [2.x-dev](/kint-php/kint/tree/2.x-dev). Please test and give feedback, thanks!

You can block classes by adding them to `Kint_Parser_Blacklist::$blacklist` and prevent iteration with `Kint_Parser_Iterator::$blacklist`
