### ISSUE TITLE
Filter trace

### ISSUE THREAD

**Issue by flip111** [kint-php/kint#189]
Is there any way to filter out calls from a trace or cut-off at a certain point? When using (testing) frameworks a lot of calls are not interesting and clutter up the area.

**Comment by HLeithner** [comment]
+1 it would be cool and maybe easy to implement to filter variables with a specified class name.
For example in Joomla many object holding a variable with a reference to the "JLanguage" singleton object. This Object holds all translation strings, so most of the time I'm not interested in 1000 lines of translation strings.

If you point me to a place where it would fit best I would try to implement it.

**Comment by jnvsor** [comment]
> filter variables with a specified class name

Implemented in [2.x-dev](/kint-php/kint/tree/2.x-dev)

> filter out calls from a trace

@flip111 Would this be better placed as a plugin to replace `Kint_Parser_Trace` in 2.x?

**Comment by jnvsor** [comment]
Implemented in d6b2540da2477ec8f4c5d6d30807208e5f814d75

**Comment by kktsvetkov** [comment]
@jnvsor What about filtering out trace frames from files that are in the composer vendors folder? The current blacklist is for function names but in order to skip/hide/collapse the vendors frames the parser must ignore based on the `$frame['file']` element.

**Comment by jnvsor** [comment]
@kktsvetkov I'm not sure how much use that would have. Half the time you want a trace you're looking for something in vendor in my experience.

Can you think of a generic way to allow blacklisting stuff? Perhaps a way to insert callables into `TracePlugin::$blacklist` that should return `true`/`false`? (That would require looping through the whole thing though, so perhaps a secondary blacklist prop)

Go ahead and make an issue for it, I'll see what I can come up with
