### ISSUE TITLE
Packagist is not being updated

### ISSUE THREAD

**Issue by carlos-granados** [kint-php/kint#19]
Not sure why as you showed me that you had correctly configured packagist to hook to github, but packagist is not being updated with your latest commits. In fact it still has the original version which had the bug with the case of one file. Can you maybe try to rehook it?

**Comment by raveren** [comment]
I think it works now, could you please try it out? I removed my username - which is same on packagist and domain and I think it fixed it.

**Comment by carlos-granados** [comment]
Yes, it seems to be working now. Thanks!

2012/8/23 Rokas Šleinius notifications@github.com
