### ISSUE TITLE
Fatal error: Call to undefined function d()

### ISSUE THREAD

**Issue by aurigadl** [kint-php/kint#190]
I've used kint for a long time and it works correctly but now don't want to run.
The error is that it does nothing.

lib in path  _./kint//Kint.class.php'_
file in path _./test.php_

code in file ./test.php

```
<?php
error_reporting(E_ALL);
ini_set('display_errors', '1');

require './kint/Kint.class.php';
Kint::dump( $_SERVER );
d($_SERVER);
?>
```

output = Fatal error: Call to undefined function d()

when i remove the function d() it doesn't show nothing. 

I checked the function        public static function dump // line 157 
but var_dump(self::enabled()); return null ...

> version download https://github.com/raveren/kint/archive/master.zip 15/04/2016
> I don't change the configuration file.
> php -v  PHP 5.3.3 (cli) (built: Jul  9 2015 17:39:00)
> Linux 2.6.32-573.1.1.el6.x86_64  x86_64 x86_64 x86_64 GNU/Linux

**Comment by aurigadl** [comment]
Something strange, I have only these two files and tells me kint was already defined.
For this reason the library is not running.
When I remove the class_exists this works properly.

```
var_dump(defined( 'KINT_DIR' )); // false
var_dump(class_exists( 'Kint')); // true 
if ( defined( 'KINT_DIR' )) return;
```

**Comment by raveren** [comment]
Hello, sorry for that, I merged in a pull request without investigating it as much as I should have, try to download the newest archive..
