### ISSUE TITLE
Make collapse/expand all/parent only more discoverable

### ISSUE THREAD

**Issue by raveren** [kint-php/kint#191]
see #69

**Comment by benjamw** [comment]
One thing that may help in discoverability is to have the cursor change to a pointer when hovering the clickable var name and then have a title on that that says something like "Open/close current level". And put a title on the arrow/plus/whatever that says "Open/Close all children".

But for me... Clicking the arrow/plus/whatever should only open the current level, and then clicking the name should be the open everything action. So basically reversed.

**Comment by jnvsor** [comment]
So whenever you want to copy paste, whenever you misclick, or whenever you just randomly click on kint it'll open everything at once? Sounds like a bad idea to me.

**Comment by benjamw** [comment]
Well... making the whole header clickable is a bad idea. I'm just saying that the default "open" action seems like it should be "open one" and not "open all". Especially with huge array or object trees.

**Comment by jnvsor** [comment]
Perhaps moving "open all" to doubleclick and "open everything" to tripleclick would be the best option. I'll look into it

**Comment by jnvsor** [comment]
This should be fixed in 2.x as of a324bd75e0a675950cad356b61e249a4b92fb4aa - I've gone ahead and bumped the doubleclick to a tripleclick as explained in my last comment

@benjamw Feel free to test and leave feedback at #208
