### ISSUE TITLE
Add a way to see and copy the PHP variable tree hierarchy

### ISSUE THREAD

**Issue by joachim-n** [kint-php/kint#194]
With Krumo's output of a complex variable such as an array of object, you can double-click it to see the hierarchy of a particular part of the variable you've expanded to, for example:

```
$varyououtput['foo']->bar->biz['baz']
```

This can then be selected and copied to one's code.

It would be really useful to have this in Kint too (unless it already is there, and I've not found it :)

Here's an example of what Krumo shows:

![krumo_hierarchy_example](https://cloud.githubusercontent.com/assets/105262/14738292/9ce538be-0878-11e6-942f-647383c2d3e0.png)

**Comment by raveren** [comment]
There's a PR! But I couldn't test it yet, I'll do it asap (that does not mean soon unfortunately)

https://github.com/raveren/kint/pull/177

**Comment by raveren** [comment]
Closing as duplicate to #175 and #177
