### ISSUE TITLE
What is the purpose of this text field

### ISSUE THREAD

**Issue by kadimi** [kint-php/kint#198]
I was wondering if [this input field](https://github.com/raveren/kint/blob/9a072e1bda25cf62b809db46b505fb8d4a9dfe6c/view/base.js#L162) offer some hidden feature.

Thanks

**Comment by raveren** [comment]
When you click on the arrow on the far right of every kint container, it pops out in a new window, this can be used for keeping track, comparing dumps or whatever. You can use this field to jolt something about what you're seeing :)

**Comment by raveren** [comment]
I mean the tiny blue arrow <kbd>-></kbd> like in this picture
 ![Kint](https://camo.githubusercontent.com/df2de4dae6f949433843a171fd0c7a8ca5462241/687474703a2f2f692e696d6775722e636f6d2f39503537526f722e706e67)

**Comment by kadimi** [comment]
Thanks!
