### ISSUE TITLE
How to disable caching in Kint?

### ISSUE THREAD

**Issue by ankitgoyal91** [kint-php/kint#199]
I use Kint very often but Kint also caches result very often and doesn't get cleaned up for so so long. As soon as I use `var_dump` (function in php) instead of Kint `d` function, everything is okay.
The problem is Kint caches the result and do not flushes it even on page refresh.
Please tell some solution.

**Comment by jnvsor** [comment]
Kint doesn't cache. If there's caching going on it's somewhere else
