### ISSUE TITLE
Inline styles hard to override, inhibiting readability in backtrace

### ISSUE THREAD

**Issue by aaronbauman** [kint-php/kint#200]
Kint's backtrace item list uses an inline style to define a tiny font size (9px) and light-grey color (#ddd), making it very hard to read. (see example)
Is there a means of overriding these styles, or preventing inline styles in the first place? 
If not, let this serve as the feature request to allow it.

example:
![salesforce_mapped_object_view___d8](https://cloud.githubusercontent.com/assets/508451/15300982/6a982e5c-1b79-11e6-9ae4-f46981dc6b0f.png)

**Comment by jnvsor** [comment]
It's supposed to be like that. You can supply your own theme if you want to change it (Check the view folder) but if you just want a backtrace, use `d(1)` to get far more details

**Comment by aaronbauman** [comment]
OK, I'm trying to figure out the best way to do this for Drupal's devel module
https://www.drupal.org/node/2726653
but I'm not sure yet on the best way to go about it yet

Thanks for the speedy reply - I'll post updates from the Drupal thread here.

**Comment by willzyx-dev** [comment]
@jnvsor the problem is not the font size nor the inline style but the color applied to the minitrace.

```
.kint footer li {
  color: #ddd;
}
```

use light-grey color (#ddd) makes the minitrace very difficult to read in almost all kint themes. 
The only theme in which use #ddd has sense is "solarized-dark"

**Comment by willzyx-dev** [comment]
created pr #202 for this
