### ISSUE TITLE
Unexpected EOF: Kint stops working

### ISSUE THREAD

**Issue by theMajc** [kint-php/kint#211]
For people who may run into this problem:
- You see a blob of JS script on the top of your page
- Kint trace stack can't be expanded
- Page error "Unexpected EOF"

This is due to New Relic's page monitoring script (in mine example) injected JS code after the `</title><meta charset="utf-8">` part generated from `view/compiled/kint.js` file.

In my particular situation, it is fixed by changing `')</title><meta charset="utf-8">'` to `')</title><meta char'+'set="utf-8">'`

**Comment by jnvsor** [comment]
In this example it seems like the bug is with the page monitoring script crudely destroying anything that matches what is presumably a simple regex. There's no way to change this as the JS is produced inline and is minified before output, removing your concatenation unless you want to do it manually afterwards

**Comment by theMajc** [comment]
@jnvsor That's very true. 
I'm posting this issue only as a quick reference for people who may encounter this problem. 
It is more logical to report the issue to New Relic and let them reconstruct their code injection process, but that may take months to see effect, whereas this is an instant "fix".

As for your concern, I don't suppose this is a process that needs to be repeated, since the `/view/compile` folder isn't really a cache folder.
Even if that is the case, removing `<meta charset="utf-8">` in `base.js L:157` will do.

Again, this is a quick and dirty fix, but one that's efficient and without any side effects.

**Comment by raveren** [comment]
Hey, I'm not fully back to business yet, but this sort of duplicates #147 

`')</title><meta char'+'set="utf-8">'` would be a decent fix, but the js compression and optimization would mess it back up, I'm wondering if @jnvsor proposed changes to js compilation would circumvent this issue as well..?

**Comment by jnvsor** [comment]
> I'm wondering if @jnvsor proposed changes to js compilation would circumvent this issue as well..?

I'd doubt it (Almost certainly not)

**Comment by raveren** [comment]
Yeah, uglify optimizes `var a = 'aaa' + 'bbb'` into `var a = 'aaabbb'`, unfortunately... I don't think it's viable to attempt to solve this then, it's a newrelic issue...

**Comment by jnvsor** [comment]
@theMajc @armababy from #147 - the latest master has some obfuscation that should make it harder for shitty programmers at third parties to screw up kint dumps by matching `meta charset`, `title`, `head`, or `body` tags - if you're still having trouble here, grab [the latest master](https://raw.githubusercontent.com/kint-php/kint/master/build/kint.php) and try it out
