### ISSUE TITLE
Kint CSS problem on dark background

### ISSUE THREAD

**Issue by DRSDavidSoft** [kint-php/kint#213]
Let's say I run Kint on a webpage with the following CSS:
`body {
    background: #333;
    text-shadow: 0 1px black;
`

IMO, Kint should add the following style globally:
`text-shadow: none;`

(Or, add `text-shadow: 0 1px white;` so it looks better both on dark and bright backgrounds).

Otherwise, it would look like this:
![image](https://cloud.githubusercontent.com/assets/4673812/17918072/3b405768-69d7-11e6-9233-a95c89515321.png)

Also, the `.kint footer` should have a bright background, if the color is set to be black.

P.S., I asked this a while ago but don't remember the answer, does Kint have a dark theme? Does it support outputting HTML content without adding its CSS, so I can write my own theme for Kint?

**Comment by jnvsor** [comment]
> Also, the .kint footer should have a bright background, if the color is set to be black.

#202 "Make kint minitrace more readable" makes kint minitrace less readable... [Called it](https://github.com/raveren/kint/pull/202#issuecomment-221632035) :)

**Comment by DRSDavidSoft** [comment]
@jnvsor Thanks
Also, about themes: please guide me on 1) disabling them 2) choosing from different Kint themes 3) guide to write my own theme

Are any of these in the docs?

**Comment by jnvsor** [comment]
Not in the docs, and kint master is very rigid with these things, you'll have to edit files inside kint folders to make your own. See `Kint::$theme` and [Kint_Decorators_Rich::init](https://github.com/raveren/kint/blob/3121c39557a69c768d6d6f090166345139adf9e2/decorators/rich.php#L307)

**Comment by raveren** [comment]
The information in your screenshot is still readable despite the shadow so it's a very niche and easily ignorable problem. I am closing this issue, but I _would_ accept a readability-focused PR, however, witch would prevent the text-shadow from appearing on Kint elements and the footer text color fixed for once.

Information on how to change themes is available in the main README.
