### ISSUE TITLE
kint::debug to use a different encoding when in CLI

### ISSUE THREAD

**Issue by siran** [kint-php/kint#216]
Is there is no way to configure kint::debug to use a different encoding when in CLI, in particular to draw the boxes in latin1 instead of utf8?

Or a way to tell Kint not to draw boxes.

**Comment by jnvsor** [comment]
`MODE_WHITESPACE` doesn't output decorative characters

**Comment by jnvsor** [comment]
This is no longer true in 2.x-dev, I'll look into it

**Comment by jnvsor** [comment]
Fixed in 2.x-dev in aaba58d5eb397e4ee0a286c322138c76ed0e3933
