### ISSUE TITLE
javascript: noden

### ISSUE THREAD

**Issue by RubenNL** [kint-php/kint#218]
if you navigate with the keyboard to the '+' sign under the debug, you get an javascript error:
![image](https://cloud.githubusercontent.com/assets/15885455/19892212/1f302ce4-a044-11e6-9bdf-57e80ade5b1a.png)
Uncaught TypeError: Cannot read property 'nodeName' of null
with the mouse, it gives
![image](https://cloud.githubusercontent.com/assets/15885455/19892271/590cf956-a044-11e6-9034-95c0e6c28545.png).

**Comment by jnvsor** [comment]
FWIW - fixed in 2.x-dev e6c57edd16682e7f4ebeacc585caa433a6e37fa9
