### ISSUE TITLE
Output array as table

### ISSUE THREAD

**Issue by MRisto-zz** [kint-php/kint#221]
Is there an option to debug an array visually as array and another array as a table? Couln't debug an array as a table. Thanks for your help. The array is

#220 
Apparently, In order for the latest versions of Kint to show 2-d arrays in tabular-view, no columns should have more than 50% empty cells .

Can i set the 50% to 90%, i didnt't find such option.

**Comment by jnvsor** [comment]
Duplicate of #219 and might not be relevant with [2.x-dev](/kint-php/kint/tree/2.x-dev). Please test and give feedback, thanks!

**Comment by jnvsor** [comment]
Not a duplicate, but still might not be relevant
