### ISSUE TITLE
Documentation: Write a paragraph how Kint coexists with xdebug

### ISSUE THREAD

**Issue by knbknb** [kint-php/kint#228]
This is a feature request on improving the documenation.

xdebug is mentioned in the Readme.md file.  To me it is not clear, generally how Kint can (or cannot, should not) be installed together with xdebug . 

Should I remove xdebug when I use kint? Can they peacefully coexist? If they do, should I deactivate xdebug nevertheless, e.g for performance reasons? 

Now I have both installed (xdebug came earlier on my dev machine) and there seems to be no problem. It would be worthwhile to clarify this.

**Comment by jnvsor** [comment]
> Even the excellent `xdebug` var_dump improvements don't come close

If that's all it takes to require a paragraph explaining what xdebug is the readme's going to get an awful lot bigger.

This is one of those things you should just google if you don't know what it is IMO

**Comment by knbknb** [comment]
Thank you very much  for your valuable "Just google it" answer. But I know what xdebug is. I have used it for many years to print stacktraces and for setting breakpoints in convoluted CMS source code.  
Your quote just says that Kint is much better than xdebug, without proof or evidence. Well, thanks again, but I was not asking for evidence anyway.

 I was just puzzled, because: I have xdebug installed. Then kint comes along. What now? Uninstall/Deactivate xdebug? Yes/No? If not, remove it better still? --Because now one of the debuggers are redundant, and keeping one of them unnecessarily slowing everything down? 

I'll make benchmarks myself.

**Comment by jnvsor** [comment]
> Your quote just says that Kint is much better than xdebug

It's better than xdebug's var_dump. It serves a completely different purpose to eg. xdebug's remote debugging.

Kint is just PHP. If it can't peacefully coexist with xdebug then xdebug is broken. (I don't think xdebug is broken, I'm just pointing out that this question doesn't really make sense)

The only active attempt at interop with xdebug is `$fileLinkFormat` being set to `xdebug.file_link_format` by default AFAIK
