### ISSUE TITLE
PHP 7.1 Incompatabilites

### ISSUE THREAD

**Issue by RonanRedstone** [kint-php/kint#229]
http://php.net/manual/en/migration71.other-changes.php

**Comment by jnvsor** [comment]
This is fixed in [2.0-alpha1](https://github.com/kint-php/kint/releases/tag/2.0-alpha1) and on that note @raveren where are you? It's been 2 months since I heard from you!

**Comment by RonanRedstone** [comment]
OK - great. I had just installed the latest stable copy via composer and saw the issue.

**Comment by jnvsor** [comment]
It may be a while before 2.0 goes stable - kint-php/kint is a placeholder until @raveren gets around to transferring this repo to the org but he's in Nepal and hasn't been able to make contact for 2 months. I'd love it if you'd give it a try though - more eyes an all that!

**Comment by jnvsor** [comment]
Fixed in [2.x-dev](/kint-php/kint/tree/2.x-dev). Please test and give feedback, thanks!
