### ISSUE TITLE
Composer autoload not registering shorthand functions

### ISSUE THREAD

**Issue by joemaller** [kint-php/kint#23]
When using Composer to install Kint, the shorthand functions `d()`, `dd()`, `s()`, `sd()` do not register until some Kint static method has been called. 

Consider:

```
d($_SERVER);           // Fatal error: Call to undefined function d()
Kint::dump($_SERVER);  // works correctly
d($_SERVER);           // now works because Kint registered its shorthand functions 
```

Switching the autoload argument in `composer.json` (line 22) from `classmap` to `files` will correctly register the functions. This tells Composer to require `Kint.class.php` so the setup code executes, exactly like Kint's standard installation practice.

I'm not especially comfortable with the guts of Composer or various Autoloading styles, but I wanted to throw this out there since it seems like an easy fix.

**Comment by raveren** [comment]
thanks for the heads up, can't test myself though, I don't use Composer either.
