### ISSUE TITLE
Output to browser JS console, possible?

### ISSUE THREAD

**Issue by lkraav** [kint-php/kint#233]
(2.0-alpha3)

AJAX debugging could use some kind of a `<script>` wrapped `console.log()` output. Am I missing something about Kint's current capabilities, or is this is a new feature request?

**Comment by jnvsor** [comment]
It *is* possible and I actually have a repo with a renderer that does just this!

I just don't know how to get it to play nice with composer alpha versioning so I was planning on releasing it after 2.0 goes live.

I'll see how it works now that there are some actual tags up and create the repo on this org if it does

**Comment by jnvsor** [comment]
Your wish is granted. Did some work to get CI working before pushing to the repo. Here it is - you'll need to include kint specifically at the alpha version to get around the minimum-stability but I presume you already have since you're using it

https://github.com/kint-php/kint-js
