### ISSUE TITLE
Basic dump returns Kint_Parser_Trace not found

### ISSUE THREAD

**Issue by Julien00859** [kint-php/kint#237]
The following basic code:

	<?php
	require 'kint.php';
	Kint::dump($_SERVER);
	?>

does a `Fatal error: Class 'Kint_Parser_Trace' not found in kint.php on line 442`

File tree:

	/
	> index.php
	> kint.php

What can I do ?

**Comment by jnvsor** [comment]
That shouldn't happen. I mean the `kint.php` file has been less than 50 lines since 2.0 release. Are you accidentally including `src/Kint.php` instead of `build/kint.php`?

**Edit:** I've added a clarifying comment on the gh-pages branch.

**Comment by jnvsor** [comment]
Closing as invalid. If you still get an error with the built files, comment again and I'll get to the bottom of it.
