### ISSUE TITLE
RFC: Disabling certain plugins

### ISSUE THREAD

**Issue by jnvsor** [kint-php/kint#244]
While I feel like the main Kint repo should offer all manner of plugins (With the condition that they relate to core PHP features, not third party stuff eg. twig), there are a *lot* of plugins in Kint now, and it's hurting performance in the default version.

This is a list of some currently-enabled plugins that I would like to keep shipping, but disabled by default (Along with their pros and cons)

If I don't receive any comments I'll make these opt-in by default.

## Kint_Parser_Binary

`xxd` in Kint. It sounded like a nice idea, but how often do you run into binary blobs writing PHP code?

This triggers a rather complex render for every string that isn't `ASCII` or `UTF-8` - which means all those nasty csv (But not really csv) files users upload from windows with weird and horrible encodings will trigger this plugin.

## Kint_Parser_DOMIterator, Kint_Parser_DOMNode

Kint boasts the only dumper that can handle DOMDocument input. In fact, even the PHP builtins `print_r`, `var_export` and `var_dump` flat out refuse to traverse it.

I can't blame them - DOMNode parsing takes a *lot* of time and a *lot* of memory, even though the Kint implementation specifically only parses childnodes in order to limit recursion nightmares.

While disabling this won't have any effect if you're not using DOMDocument, if you *are* and you dump one by accident, this plugin will make things very slow for you, so I want it to be opt-in.

Additionally, the XML plugin uses SimpleXML by default (Though DOMDocument is an option) so this won't affect that behaviour.

## Kint_Parser_Serialize

Similar to `Kint_Parser_Json` this takes a serialize string and unserializes it, showing the contents and access paths.

It's triggered on a lot of strings, and needs a `preg_match` for "early" return so it has a non-negligable effect on performance.

The worst part is that for safety reasons it refuses to parse objects and arrays by default for security reasons, so the only things it shows by default are ints, bools, nulls, floats, and strings. None of which have a hierarchy, so none of which actually have much use of unserialization and parsing.

---

I looked at the other plugins but I find them all too useful to remove. Any well-argumented suggestions will be considered.

**Comment by tinpansoul** [comment]
If i don't need any html (use plain/text mode) then `~s(1)` eats around 2 Gigabytes of RAM and 25 seconds of time (macbook pro).

So, turning off any plugins and produce flat trace will be great feature in this particular case because even parsing php files as text doesn't require lots of memory, if i'm not wrong here.

But.. which plugin i must disable to speed up plain trace generation (without html)?

**Comment by jnvsor** [comment]
Hmm... The problem there is that the parser is parsing all the arguments in the backtrace under the (Correct) assumption that the output might be needed in the rich renderer.

Ideally there would be a way for a renderer to alter the plugin list before the parser is constructed. I've made an issue #249 to continue @TrogWarZ

**Comment by jnvsor** [comment]
No other comments, the plugins have been disabled
