### ISSUE TITLE
RFC: Way for renderer to alter parser plugins

### ISSUE THREAD

**Issue by jnvsor** [kint-php/kint#249]
> If i don't need any html (use plain/text mode) then ~s(1) eats around 2 Gigabytes of RAM and 25 seconds of time (macbook pro).

We need a generic way for certain renderers to affect parser plugins.

* I don't want parser plugins to have a "Supports X" field because third party renderers wouldn't be supported (And BC)
* I don't want renderers to blacklist certain plugins because any new plugin could trash performance

Idea: Add a before-create-parser hook and let the renderer do whatever it wants with the plugin list. That should allow for things like whitelisting or substituting plugins, but it seems a bit off the cuff. Any suggestions?

**Comment by jnvsor** [comment]
@TrogWarZ - how does 142457d5e06901851109e1fd92dfd842234043b5 perform for your plaintext backtrace?

**Comment by tinpansoul** [comment]
@jnvsor, yeah, it solves my issue! Now, `s(1)` works fast and don't require tons of ram!

Tested with:
`composer require --dev "kint-php/kint:dev-master#142457d5e06901851109e1fd92dfd842234043b5"`

**Comment by jnvsor** [comment]
Allrighty, that'll make it into 2.1.2 then

**Comment by jnvsor** [comment]
@TrogWarZ Consider lowering your max_depth - 25 seconds and 2 gigs is pretty bad for a backtrace (Doesn't even hit that from the depths of drupal on my system)

**Comment by tinpansoul** [comment]
@jnvsor, you'll never know. With this fix trace is blazingly fast. But i got your point!

2 gigs was gained with stack of 27 calls – this is phpunit plus big-project-10-years-without-refactoring-with-event-hell. Really helpful was 18 of 27 calls in this stack (other 9 calls – is phpunit).

**Comment by jnvsor** [comment]
Drupal's notoriously heavy - a 30 stack backtrace (in rich mode) went from 50 seconds and 350m ram usage to 6 seconds 71m by lowering max_depth from 7 to 5. I generally tweak the depth limit in any long-term project I'm working on

**Comment by jnvsor** [comment]
Pushed
