### ISSUE TITLE
no resolv modifiers

### ISSUE THREAD

**Issue by carschrotter** [kint-php/kint#251]
Hello, 
I have problem when using the static dump method from class with modifiers, then this do not work.
Example `$dump = @Kint::dump($value); ` print out the value and not save in the variable.
The problematic code is on "src/SourceParser.php" line 182:
```php
                if (!$prev_tokens[0] || $prev_tokens[0][0] !== T_STRING || strtolower($prev_tokens[0][1]) !== $class) {
                    continue;
                }
```
you see strtolower($prev_tokens[0][1]) and  $class is on code not convert to lower.
Change to the following code work fine:
```php
                if (!$prev_tokens[0] || $prev_tokens[0][0] !== T_STRING || $prev_tokens[0][1]!== $class) {
                    continue;
                }
```

ps. sorry for the Bad English. I am talking about this only very circularly.

**Comment by jnvsor** [comment]
Oh my, I seem to have forgotten an strtolower. Does this diff work in your use case?

```
diff --git a/src/SourceParser.php b/src/SourceParser.php
index d8d8d08..befc6cf 100644
--- a/src/SourceParser.php
+++ b/src/SourceParser.php
@@ -130,7 +130,7 @@ class Kint_SourceParser
 
         if (is_array($function)) {
             $class = explode('\\', $function[0]);
-            $class = end($class);
+            $class = strtolower(end($class));
             $function = strtolower($function[1]);
         } else {
             $class = null;

```

**Comment by carschrotter** [comment]
Hello, I have applied this fixed manually (I use composer for installation, no git repo). And it works fine with me!

**Comment by jnvsor** [comment]
All right, I'll push that soon

**Comment by jnvsor** [comment]
Pushed. Thanks for the bug report!
