### ISSUE TITLE
Render Location of Script and Style Tag

### ISSUE THREAD

**Issue by martinherweg** [kint-php/kint#254]
Is there anyway to define the Location (at best just above the </body> tag) where the script and style Tag should get rendered?

Background ist that I have a Page with an appWrapper which is watched by Vue and Vue doesn't allow script or style tags in it's watched element and strips them out.

Thanks in advance.

Cheers,
Martin

**Comment by jnvsor** [comment]
The rich renderer does this output in the `preRender()` method. The first thing that comes to mind is to extend it to prevent output and store it for later.

**Edit:** Something like this?

```php
<?php

class R extends Kint_Renderer_Rich
{
    public static $preRenderOutput;

    public function preRender()
    {
        if (!self::$preRenderOutput) {
            return self::$preRenderOutput = parent::preRender();
        }

        return parent::preRender();
    }
}

Kint::$renderers[Kint::MODE_RICH] = 'R';

// At end of page

echo R::$preRenderOutput;

```

**Comment by martinherweg** [comment]
Thanks for the suggestion, I'm using kint as a Plugin in Craft CMS with a Twig Extension, if you have a direction for me how to implement it in that environment that would be great.
Meanwhile I will have a look myself if I could implement it.

**Comment by jnvsor** [comment]
I made a [twig extension](https://github.com/kint-php/kint-twig) so that shouldn't be too hard. And the snippet above should work in combination too. (Though you'd need to write your own twig function to echo it)

**Comment by martinherweg** [comment]
Thanks, seems like I got it working, I think it is pretty ugly as I'm not a PHP Pro but it works and I let a colleague review it.

Thanks for your hints.

**Comment by martinherweg** [comment]
Hm I have nearly no experience with PHP so this is pretty hard for me.
I forked the Original Plugin and updated it to the newest Kint Version.
https://github.com/martinherweg/craft_kint
I think it does it's own Twig Implementation together with the Craft Implementation.

I'm not sure where I should put your snippet and how to go on from there. I've tried putting it in the Base Plugin Folder and loading it in the Twig Extension, it does _something_ but I'm not sure what your snippet should output.

I totally understand if that is out of scope for this and I could ask a colleague next week if we could work it out, but would really appreciate if you could give further hints.

Thanks! :)

**Comment by jnvsor** [comment]
Yeah this is going more into craft than Kint, with a few bits of missing PHP knowledge to boot. Your colleague should be able to throw something together in a few minutes if you show him this thread though :)

A quick look shows you should include kint-php/kint-twig somewhere [here](https://github.com/martinherweg/craft_kint/blob/master/kint/KintPlugin.php#L101)

The part above the comment in the snippet is initialization, and below is just outputting the script/style tags (You might need to throw in a closing div tag too)
