### ISSUE TITLE
"Text.php" | PHP Warning:  str_repeat()

### ISSUE THREAD

**Issue by voku** [kint-php/kint#258]
tested with PHP 7.0.x

---

PHP Warning:  str_repeat(): Second argument has to be greater than or equal to 0 in vendor\composer\kint-php\kint\src\Renderer\Text.php on line 107

---

PHP Warning:  str_repeat(): Second argument has to be greater than or equal to 0 in vendor\composer\kint-php\kint\src\Renderer\Text.php on line 105

---

PHP Warning:  str_repeat(): Second argument has to be greater than or equal to 0 in vendor\composer\kint-php\kint\src\Renderer\Text.php on line 103

**Comment by jnvsor** [comment]
Are you setting `Kint_Renderer_Text::$default_width` to 0 somewhere?

**Comment by voku** [comment]
no ... but I think it's the -> $terminal_width = null;

$width === null
$text === '...'

![screenshot 6](https://user-images.githubusercontent.com/264695/29248577-ae97a1b6-801b-11e7-9031-d444921ddf38.png)

**Comment by jnvsor** [comment]
Where do you see `$terminal_width = null`? It sets it to `$default_width` which is 80 by default. What is the output of `tput cols` in a terminal?

**Comment by voku** [comment]
"Cli.php"

-> $terminal_width = null

-> the fallback for "self::$terminal_width" is only used for "if (!self::$terminal_width && !KINT_WIN) {"

-> $this->header_width = self::$terminal_width;

PS: Do we need the check for windows? Without the check "!KINT_WIN" it's working for me ...

**Comment by jnvsor** [comment]
Oh I see now. Does f227d3da58837bbed751671c03740b76b42acacd work for you?

**Comment by jnvsor** [comment]
Fixed as per https://github.com/kint-php/kint/commit/f227d3da58837bbed751671c03740b76b42acacd#commitcomment-23621690
