### ISSUE TITLE
Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by Ivan-Baranov** [kint-php/kint#259]
Invalid argument supplied for foreach() - /vendor/kint.php(307) : eval()'d code:1 
Kint v.2.2

**Comment by jnvsor** [comment]
Can you give me more info? What is the error message when using composer (Which shows the source file and line of the issue) and what data are you dumping to cause the warning?

Can you send a `var_export` or `serialize` of the data?

I'm about to leave for a week's vacation, so I won't be able to ask for follow-up info. Sorry in advance for the delay.

**Comment by Ivan-Baranov** [comment]
Excuse me. The trouble in config, app_root_dirs has been defined as string, but not as [string].

**Comment by jnvsor** [comment]
@Ivan-Baranov Glad you figured it out, and thanks for responding
