### ISSUE TITLE
The microtime plugin

### ISSUE THREAD

**Issue by alwinkpc** [kint-php/kint#261]
Can you please be more explicit about how to use the microtime plugin?
I've found in [this page](https://kint-php.github.io/kint/plugins/) no information but how to clean the stack

**Comment by jnvsor** [comment]
If you just dump microtime it will work (EG: `Kint::dump(microtime()); d(microtime());`) I'll clarify the text

**Comment by alwinkpc** [comment]
Wow, nice and fast.
Though I need more setup. Spend like an hour reading the code. Thanks

**Comment by jnvsor** [comment]
Fixed in dd749030a1275bb48b4b5f43e28a8e30e6f1ef91
