### ISSUE TITLE
How to set the tab toString as default ( not text only )

### ISSUE THREAD

**Issue by TLMcode** [kint-php/kint#263]
Wondering if there's something I'm missing as I would like to display toString by default ?
![image](https://user-images.githubusercontent.com/3152974/33150452-7f507416-cfa1-11e7-8734-8dac0546fd97.png)

Thanks for any info

**Comment by jnvsor** [comment]
You would need to write a plugin to move it to the front (The first tab is always selected by default)

Or if you wanted toString to always be at the front you could extend the plugin and do it there. Either way the body of the parse should look something like this:

``` php
if (!$var instanceof Api\Invoice) {
    return;
}

$rep = $o->getRepresentation('tostring');

if ($rep) {
    $o->replaceRepresentation($rep, 0);
}
```

**Comment by TLMcode** [comment]
Thanks for the speedy reply <3

**Comment by jnvsor** [comment]
I'll go ahead and close it then, comment back if you have more trouble
