### ISSUE TITLE
incompatibilty with php < 5.3.9

### ISSUE THREAD

**Issue by mba242** [kint-php/kint#266]
PHP-Documentation:
http://php.net/manual/de/function.is-a.php

> bool is_a ( object $object , string $class_name [, bool $allow_string = FALSE ] )
> ...
> 5.3.9 | Added allow_string parameter

https://github.com/kint-php/kint/blob/c9a028b6bc7f273ef129d577ea7d4683fa6debaa/src/Parser.php#L430

uses allow_string without php-version check.

Example:
http://sandbox.onlinephpfunctions.com/code/e0de898eaf1918d343191d083abfd7914bf65295
PHP 5.3.2

**Comment by jnvsor** [comment]
Well spotted. Since this is comparing the hierarchies of class names, do you know of any replacement?

**Edit:** I suppose since we're generating the class names ourselves from `get_class` we can be fairly certain the same class will have the same name, and use `is_subclass_of` for the rest...

**Comment by jnvsor** [comment]
Should be fixed in 528f9195d44637c83b64d7ed58dcf17e9c1027c5

**Comment by mba242** [comment]
ok - seems to work. THX.
