### ISSUE TITLE
Option to not sort object properties

### ISSUE THREAD

**Issue by deanhouseholder** [kint-php/kint#268]
It would be great if there was an option to prevent sorting array values automatically. Can you please add this?

**Comment by jnvsor** [comment]
Array values aren't sorted. Object parameters are (So that they can be ordered by visibility, among other things)

Are you seeing an array shown in the wrong order somehow?

**Comment by deanhouseholder** [comment]
Sorry, I guess it was an array of objects.  So yeah, it was the objects that I wished were not alphabetized.

**Comment by jnvsor** [comment]
Since there's no stable sort built into PHP the only choices would be a very slow mergesort in code, or not sorting at all and losing visibility order... The first won't work and I don't see how anyone would prefer the latter (It really does make things confusing for subclasses) but I wouldn't be against adding a flag to the parser to enable/disable it.

The tricky part is integration with the facade and helper functions. I'm going to table this until I've finished rewriting the facade in the next branch, which is going to take a while too.

In the meantime if you really want it, you can comment out [line 307](https://github.com/kint-php/kint/blob/528f9195d44637c83b64d7ed58dcf17e9c1027c5/src/Parser.php#L307) and rebuild the single file version, going around composer.

**Comment by deanhouseholder** [comment]
Yes, I did mean the latter, not sorting it at all.  Here's my use case. I'm writing a WordPress plugin which does DB fetches pulling back objects per row, but for some reason wraps them all up into an array.

array (13) [
    0 => stdClass (10) (
        public 'description' -> string (71) "10 x 10 ft. pipe and draped space with neighboring booths on both sides"
        public 'id' -> string (1) "1"
        public 'layout_id' -> string (1) "1"
        public 'length' -> string (2) "10"
        public 'price' -> string (6) "495.00"
        public 'quantity_total' -> string (3) "106"
        public 'sale_price' -> string (6) "400.00"
        public 'status_id' -> string (1) "1"
        public 'title' -> string (12) "Aisle Booths"
        public 'width' -> string (2) "10"
    )
    1 => stdClass (10) (
        public 'description' -> string (93) "10 x 10 ft. pipe and draped space located on the end of an aisle, providing increased traffic"
        public 'id' -> string (1) "2"
        public 'layout_id' -> string (1) "1"
        public 'length' -> string (2) "10"
        public 'price' -> string (6) "625.00"
        public 'quantity_total' -> string (3) "100"
        public 'sale_price' -> null
        public 'status_id' -> string (1) "1"
        public 'title' -> string (13) "Corner Booths"
        public 'width' -> string (2) "10"
    )

Here's a print_r of the same thing:

Array
(
    [0] => stdClass Object
        (
            [layout_id] => 1
            [id] => 1
            [title] => Aisle Booths
            [description] => 10 x 10 ft. pipe and draped space with neighboring booths on both sides
            [price] => 495.00
            [sale_price] => 400.00
            [quantity_total] => 106
            [length] => 10
            [width] => 10
            [status_id] => 1
        )

    [1] => stdClass Object
        (
            [layout_id] => 1
            [id] => 2
            [title] => Corner Booths
            [description] => 10 x 10 ft. pipe and draped space located on the end of an aisle, providing increased traffic
            [price] => 625.00
            [sale_price] => 
            [quantity_total] => 100
            [length] => 10
            [width] => 10
            [status_id] => 1
        )

To me, this format is faster for me to scan through looking for the id or layout_id because they are at the front of my SELECT statement.

So, yes, I'd like to have a flag when invoking Kint::dump to not sort the objects.

**Comment by raveren** [comment]
Of course it shouldn't sort the properties, this will be removed, sorry for the inconvenience.

**Comment by jnvsor** [comment]
I'm not so sure about that @raveren - When working with large objects with lots of (over 100) properties and little consistency (Aka: Any legacy system) it can be a big help to have things sorted.

From an architectural point of view though, if it sorts it should definitely happen in the renderer not the parser.

**Comment by deanhouseholder** [comment]
I was just hoping for an option.  Not to change the default setting.

**Comment by jnvsor** [comment]
Raveren has a point though, that kint should default to showing accurate information. Even if it's as unimportant as object property order and has a legibility detriment.

So I'll make sorting an opt-in flag on the renderers in the next major version

**Comment by jnvsor** [comment]
@deanhouseholder Can you try out 7a62bf557e090e1ce7758af2d5a9683532cf1150 on [my test branch](https://github.com/jnvsor/kint/tree/test) and see if you have any feedback?

**Comment by jnvsor** [comment]
7a62bf5
