### ISSUE TITLE
ReflectionException "Notice: Undefined property: "

### ISSUE THREAD

**Issue by AdamPS** [kint-php/kint#269]
This issue is for 1.x from using the code in Drupal devel module.

Exception is generated if a property is unset:

```
class Foo {
    public $bar;
}

$instance = new Foo;
unset($instance->bar);                                                                                                                         Kint::dump($instance);
```
> PHP error:  Cannot access protected property Foo::$bar on line 1

This seems to be a [change in PHP](https://bugs.php.net/bug.php?id=72174).  Given that the property might be protected I can't see any way to test for isset save catching the error.
```
                        $old_handler = set_error_handler(function() use(&$value) { $value = NULL; return true; });
                        $value = $property->getValue( $variable );
                        set_error_handler($old_handler);
```

**Comment by jnvsor** [comment]
1.x is no longer supported, and 2.x is only supported for bugfixes since I'm working on 3.x now.

The last 1.x release was a year ago and last time I checked devel had a version that was several years older than that. They also ignored patches I sent to update to a new version for so long that I gave up trying.

2.x doesn't use reflection for object properties at all: If a property is unset the correct behaviour for a debugger is *not to show it* not to pretend that it's set and null.

If you want this fixed I suggest you start complaining on [the devel bug report](https://www.drupal.org/project/devel/issues/2859114) but I wouldn't get your hopes up if I were you

**Comment by AdamPS** [comment]
@jnvsor Thanks for the response.

As you say sadly Drupal devel seems to be stuck on the very old code.

I think the best I can do is to post a patch for devel that implements the above fix (which I just edited).  I acknowledge that this reports null instead of not printing at all.  However it's a big improvement on endless warnings and then printing the value of the previous variable which is what we have now.

**Comment by jnvsor** [comment]
@AdamPS I already posted a patch to update to 2.x on that bug report, you can probably replace the file with a newer version and it should work just the same. It'll fix a lot more bugs than just that one.

**Comment by AdamPS** [comment]
@jnvsor Yes I understand.  However people may prefer a specific patch.

Unless the module owners take the patch, I think that many people will consider it risky to switch to a new major library version individually.  The integration into Drupal is largely untested, and you would have no community to support you.

You [said yourself](https://www.drupal.org/project/devel/issues/2859114#comment-12017220):
> That said, performance is still an issue

Any update on performance in newer versions?

**Comment by jnvsor** [comment]
Performance is an issue, but IIRC it's faster than 1.x for the typical workload. The main issue is that 2.x has far more plugins so if you leave them all on you'll get way more info and (no surprise) it will take longer.

If you disable half of them you'll get a larger featureset with better perf than 1.x

Additionally, kint 1.x has no way to blacklist certain objects for dumping - if the IOC container shows up in your dump kint 2 will be anywhere from 2 to 200 times faster...

**Comment by AdamPS** [comment]
OK, I'm going to try and revive the [Drupal devel issue](https://www.drupal.org/project/devel/issues/2859114) - I added a comment.  Are you willing to come back and take another look?  Failing that, if the maintainers are totally uninterested, I think it would be easy enough to make a new kint2 contrib module.

**Comment by jnvsor** [comment]
Nah. If you take the patch I submitted and replace the build file it should be good to go, but I've done that so many times I don't want to any more :(

In theory, all a separate module would have to do is add the IOC container to the blacklist, lower the dump depth to 5 (6 is a bit much for drupal), and register the twig extension.

**Comment by AdamPS** [comment]
The status of the Drupal issue is

- I have asked a question that probably only you can answer
- I have made some review comments that likely need updates to the patch.  Most importantly I am suggesting we use composer.json rather than including the kint binary inside the module so that should be the end of "replace the build file so many times":-)
