### ISSUE TITLE
css ".kint-rich footer" need background color

### ISSUE THREAD

**Issue by qaharmdz** [kint-php/kint#271]
version: 2.2

`.kint-rich footer` css need background color to override site `footer` stylesheet.
I get dark background with dark text because of this.

Thank you.

**Comment by jnvsor** [comment]
A lot of sites use footer elements and style them which might make this a good idea, but then there can be multiple footer elements on a page so it seems more like something we should leave to the end user

**Comment by jnvsor** [comment]
3af0b5c
