### ISSUE TITLE
Pulling in with composer doesn't autoload versions 2.0 and higher

### ISSUE THREAD

**Issue by sojohnnysaid** [kint-php/kint#273]
Pulling this in and only works if version is set to "^1.0.0" within my composer.json
If I try going any higher I get nothing in the browser, and phpstorm doesn't sniff out any of the functions for autocompletion. I think it might have something with kint's composer.json where it's pointing to the src directory instead of build?

**Comment by jnvsor** [comment]
No, the build folder is only for non-composer use. Can you give me a reproducible test case? My own attempt works fine with use right after autoload

**Comment by sojohnnysaid** [comment]
I'm still learning, not sure how to recreate the issue so i'll close this up. Glad I can use the 1.0.0. It's a great package. Thanks for the reply.

**Comment by jnvsor** [comment]
@sojohnnysaid No no no, if you have a real issue I want (And need) to fix it - can you paste me your composer.json from when it's not working?

**Comment by sojohnnysaid** [comment]
@jnvsor yes of course my apologies, still learning this stuff. I'll recreate the issue and paste the composer.json today. Thank you.

**Comment by jnvsor** [comment]
@sojohnnysaid I've reopened this one, just paste it here when you get the chance :)

**Comment by sojohnnysaid** [comment]
@jnvsor no longer able to recreate the issue when I set everything up again. Must have been an error on my part. 

Here is the composer.json:

```javascript
{
    "name" : "knowthecode/wordpress-starter-plugin",
    "description" : "Know the Code Starter Sandbox plugin.  Use this plugin for all of the Know the Code demo Labs and Docx.",
    "type" : "project",
    "keywords" : ["wordpress", "wp", "plugin"],
    "homepage" : "https://knowthecode.io",
    "license" : "GPL-2.0+",
    "authors": [
        {
            "name" 	: "hellofromTonya",
            "email" : "hellofromtonya@knowthecode.io"
        }
    ],
    "require": {
        "php" : ">=5.4.0"
    },
    "require-dev": {
        "kint-php/kint" : "^2.2",
        "filp/whoops": "~2.0"
    },
    "autoload" : {
        "classmap": [],
        "files": [
            "src/support/exceptions.php",
            "src/sandbox.php"
        ]
    },
    "extra": {
        "branch-alias": {
            "dev-master": "1.0-dev"
        }
    },
    "config": {
        "vendor-dir": "assets/vendor"
    },
    "minimum-stability": "dev"
}
```

**Comment by jnvsor** [comment]
All right then, thanks for confirming!
