### ISSUE TITLE
Add a setting to max memory in addition to depth

### ISSUE THREAD

**Issue by zainengineer** [kint-php/kint#276]
its hard to choose depth limit as different objects /arrays consume vastly different memory for same depth.

Is it possible to have a max memory limit, which is casually checked in addition to `max_depth`

check can be added here https://github.com/kint-php/kint/blob/725cfea8d5aa7d54be465c195eca57ef458504ed/src/Parser/DOMIterator.php#L35

so if max memory is reached, it does not iterate further on the object.

It won't be perfect but will give a better way to stop code to render more then resources allow.

May be every time, it reaches the memory limit, increases limit by 1 MB so elements in other branches can be rendered.

**Comment by jnvsor** [comment]
> May be every time, it reaches the memory limit, increases limit by 1 MB so elements in other branches can be rendered.

And this hits the crux of the problem: You might be looking at a very expensive object, or you might be looking at one of a million ints. Or maybe you only dumped one int, but the application was already using close to max memory.

I'd say the "correct" way to handle objects that consume a large amount of memory is to use the [blacklist plugin](https://github.com/kint-php/kint/blob/528f9195d44637c83b64d7ed58dcf17e9c1027c5/src/Parser/Blacklist.php) (Which I suggest you always do to things like IOC containers that are likely to contain lots of object children)

The only way I can think of doing this would be to allow the parser to *increase* the memory limit while running, but that sounds like a *very* scary idea... It would be equivalent to `ini_set('memory_limit', -1)`

On the other hand: You shouldn't be using Kint in production, and on a development machine you can set the memory limit to whatever you want. Is there something specific you're dumping that's causing this?

**Comment by zainengineer** [comment]
can we strlen(serialize($object)) to psudo estimate the object length ? and if its longer then a `max_object_size` we do not attempt it parse it.

**Comment by jnvsor** [comment]
Nope. if it's longer than `max_object_size` there's a good chance allocating the string alone will push you over your memory limit. Besides, that would make Kint unbearably slow, serializing every array and object recursively (And it's not exactly lightning on those heavy objects as-is, hence the blacklist plugin)

As far as I know there's no way to determine the amount of memory 'used' by an object without extra PHP modules

**Comment by jnvsor** [comment]
@zainengineer Can you think of any other way to do this? If not I'm going to close it since I don't think it can be done
