### ISSUE TITLE
display error with IE

### ISSUE THREAD

**Issue by junaexp** [kint-php/kint#278]
Hi. 
display error with IE..
plz check this file :)

![1](https://user-images.githubusercontent.com/21023621/41074102-56916f40-6a41-11e8-8e1a-371e65918806.png)

**Comment by jnvsor** [comment]
That looks weird - I don't suppose there's any chance you're using IE 10 or below?

**Comment by junaexp** [comment]
yep...weird
this browser & environment is
**windows7, IE 11.0.96
IIS6.0, PHP 5.6, require kint.phar**

Personally I think that IE10 and below are not used by anyone. :)

![4](https://user-images.githubusercontent.com/21023621/41081240-133c4ab6-6a65-11e8-9c28-10ca316da836.png)

**Comment by jnvsor** [comment]
> Personally I think that IE10 and below are not used by anyone. :)

I had hoped the same about IE11 and edge :)

I've tried my virtual machine with IE 11 in it, it seems to work fine. The folder from 3.0 doesn't work in IE 11 which is pretty bad, nor do the foldout icons (Which is also pretty bad) but functionally it works mostly.

Are you dumping kint inside a table or a list or something? I know browsers have a habit of moving elements out of tables before the javascript can get at them and mess things up.

**Comment by jnvsor** [comment]
@junaexp I've had a look at it in a VM. I had forgotten how horrible it was to work with IE...

Anyway, I've fixed the folder not working, and the icons not working. It's a bit of a detriment to styling the buttons on any other platform, but it works well enough.

I still can't reproduce your error though. Can you try 70dfc888628c7ac89093edc8006a3f892823d6cc from [my fork](https://github.com/jnvsor/kint/tree/test) and see if it works?

**Comment by junaexp** [comment]
Thank you for support, it's work!
IE11 said  "addEventListener" (L : 6293) is Problem..(? Why?) -- IE is sucks

Anyway, don't be stress, 
Kint is became the light of my coding life.
Thx :)
