### ISSUE TITLE
Error dumping on CLI mode Linux

### ISSUE THREAD

**Issue by lordskynner** [kint-php/kint#279]
Hello, when i try to dump someting in CLI mode, always print like this:
`ââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââ
â literal                                                                      â
ââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââ
array (1) [
    'teste1' => integer 1
]
ââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââ
Called from <ROOT>/dados.php:4
`

Already try dump with ~d(['teste1' => 1]), d(['teste1' => 1]), s(['teste1' => 1]), always with the same print.
how can i fix this plz?

**Comment by jnvsor** [comment]
This happens in terminals that don't support UTF-8 properly (eg putty) - you can turn off decorations by setting `Kint\Renderer\TextRenderer::$decorations` to false (Or `Kint_Renderer_Text::$decorations` in 2.x)

**Comment by lordskynner** [comment]
Now it works, thx @jnvsor
