### ISSUE TITLE
Limit displayed array items

### ISSUE THREAD

**Issue by lordskynner** [kint-php/kint#280]
Have any way to limit number of displayed array items? Example, i have an array with 5000 items, but, only need to dump first 1000. And maybe a last line with an information like "More 4000 Itens.'

Thx.

**Comment by jnvsor** [comment]
Hmm... I could add something to the blacklist plugin to set an upper limit on array length, and then make it shallow so you can dump it directly to see more. It won't show you the first 1000 items, but it will show you how many are in there

**Comment by jnvsor** [comment]
Sorry for the delay. @lordskynner I've added the array size limit to the blacklist plugin on my test branch at 27ac8a9292fc17240dad468cfa24a001eed1a875

Does this work?

**Comment by jnvsor** [comment]
Pushed to kint-php with 1k/10k defaults
