### ISSUE TITLE
How to not display dump on the bottom, but inline

### ISSUE THREAD

**Issue by arjgid** [kint-php/kint#284]
Kint dump are now by default displayed at the bottom. Commit: 3076ae0
How can this behavior be turned off without modifying the code?

**Comment by jefvhal** [comment]
Seems like not documented yet: But this works:
```php
<?php
require 'kint.phar';
Kint\Renderer\RichRenderer::$folder = false;
```

**Comment by arjgid** [comment]
Thanks Jeffrey!

**Comment by jnvsor** [comment]
@jefvhal is absolutely correct. I've had updating the website on my todo list for a while, but first I want to update the kint-twig and kint-js plugins, and I haven't been able to carve any time out of my day for a while. Stay tuned

**Comment by jnvsor** [comment]
Kint 3 has been released and the documentation has been updated. You can now see the folder setting on the [settings page](https://kint-php.github.io/kint/settings/)
