### ISSUE TITLE
Asking for help: Upgrade from v.1.1 to 3.0

### ISSUE THREAD

**Issue by Tilogorn** [kint-php/kint#285]
Due to a wrong decision in my dependency management I ugpraded from v.1.1 to v.3.0 just today. That's about a year without updates. As I walked through the changelog there have been many nice changes, but also two I don't like:

- as soon as I dump a variable with `d($something);` the dump gets appended at the bottom of the page. I am used to the behaviour that the dump appears in the HTML layout where I inserted the `d($something)`
This CSS responsible for that:
```css
    .kint-rich.kint-folder {
        position: fixed;
        bottom: 0;
        [...]
    }
```
Is this change reversible? I liked the dumps where I expected them to appear according to my positioning of the `d($something)`.

- In v.1.1 the dump of e.g. an array was directly visible with `!d($array)`. Now the expanded dump is wrapped in a not expanded layer just called `Kint`. Is this also reversible?

See the attached pictures for explanations
![bildschirmfoto vom 2018-10-02 10-34-58](https://user-images.githubusercontent.com/7524854/46338107-988dea00-c62f-11e8-888f-166f533a9bf7.png)

**Comment by jefvhal** [comment]
As outlined on the [settings](https://kint-php.github.io/kint/settings/) page, you can disable the option to collect all kint-messages at the bottom by changing Kint\Renderer\RichRenderer::$folder to false (default true)

E.G.
```php
<?php
require 'kint.phar';
Kint\Renderer\RichRenderer::$folder = false;
```

Kint output is now visible where you called it.

This should solve both of your issues.

**Comment by Tilogorn** [comment]
Wow, the framework really grew :-) Thanks for pointing me to the settings.

Anyone who is interested in my use case: Setting kint settings in CodeIgniter can be archieved with a [hook](https://www.codeigniter.com/user_guide/general/hooks.html), which is executed on every request.

**Comment by jnvsor** [comment]
> I ugpraded from v.1.1 to v.3.0 just today. That's about a year without updates.

More like 2 :)

If you have any other issues the documentation doesn't address, feel free to post them here.

Did Jeff help you fix your issues?

**Comment by Tilogorn** [comment]
Yes, I‘m good. Issue can be closed 👍🏼 Thanks for the fast and good help!

**Comment by jnvsor** [comment]
All right, I'll close this. Thanks for the help @jefvhal
