### ISSUE TITLE
How to turn off docked mode on the new version?

### ISSUE THREAD

**Issue by pressaholic** [kint-php/kint#288]
Hello folks,

Thanks a lot for building this tool, i'm using it on all my projects 👍 

I've switched to the latest version using the .phar file, but whenever i use d( $var ), it shows docked to the bottom of the browser. How can i turn that feature off? I mean i'd like to render the Kint element inlined.

Thanks again!

**Comment by jnvsor** [comment]
It's in the [documentation](https://kint-php.github.io/kint/settings/): `Kint\Renderer\RichRenderer::$folder = false`

Dupe #284 #285

This solve your issue?

**Comment by pressaholic** [comment]
Oh! I feel stupid now ... :/
Thanks again for your help!


-----------------------------------------------------------------------
*pressaholic*
Wordpress and PHP Web Development
http://pressaholic.com
