### ISSUE TITLE
IDE will throw warning when using kint with composer

### ISSUE THREAD

**Issue by jefvhal** [kint-php/kint#289]
Phpstorm is having problems when kint is included via an composer command.

Repro:
- Add kint via composer to project (`composer require kint-php/kint`)
- Use the "old" layout without folder in bottom (`Kint\Renderer\RichRenderer::$folder = false;`)

Results in warning in IDE: `Multiple declarations: this version of IDE *will* have problems with completion, member resolution and inheritance analysis for all classes that have multiple definitions in project files (regardless of includes).`

The double declarations are included via
- vendor\kint-php\kint\init.php
- vendor\kint-php\kint\build\kint.phar\init.php

Can't advice in the best approach to solve this, but one of them shouldn't be downloaded when using composer.

**Comment by jnvsor** [comment]
Yeah 2.x used to use a bigass gzipped eval'ed string to support back to 5.1, but phar files are the modern way of doing it. The IDE probably has less trouble parsing it.

Unfortunately, the only way of preventing its use in composer also prevents the phar file from being included in zip downloads from github (Marking it as `export-ignore` in `.gitattributes`)

An alternative would be to rig travis to create build artifacts of some sort, but that still leaves something to be desired...

I'll think about this, but I'm not sure how to deal with it just yet

**Comment by jnvsor** [comment]
@raveren What do you think about export-ignoring the phar file? It will make the 'Download zip file' option in github useless, but fix some IDE issues.

**Comment by jnvsor** [comment]
@jefvhal It should be fixed in master now with 9de21c4b -- can you confirm?
