### ISSUE TITLE
"unknown type" variables not dumped

### ISSUE THREAD

**Issue by VSilantyev** [kint-php/kint#29]
When there is variable with "unknown type" error appears on parser.class.php:56

``` php

        # first parse the variable based on its type
        $methodName = '_parse_' . gettype( $variable );
```

gettype in php 5.4 returns "unknown type" according to:
http://php.net/manual/en/function.gettype.php

suggested fix:

``` php
        # first parse the variable based on its type
        $type = gettype( $variable );
        if($type == 'unknown type')
            $type = 'unknown';
        $methodName = '_parse_' . $type;
```

**Comment by raveren** [comment]
Thanks, and fixed. When does this happen? How can a variable be of unknown type?

**Comment by VSilantyev** [comment]
I did not try to reproduce this error in clean environment.

I received this type as part of big trace inside our project.
