### ISSUE TITLE
2.x to 3.0

### ISSUE THREAD

**Issue by voku** [kint-php/kint#293]
Hi, I updated from 2.x to 3.0 but I had some issues.

1. "Kint::settings()" is not there anymore, what is the replacement for this?
2. /Kint/Kint::$expanded is not working, because the JS code hide it again

PS: Is there a changelog or a update howto?

**Comment by jnvsor** [comment]
1. `Kint::getSettings`
2. Are we talking about the folder? (`RichRenderer::$folder`?)

**Comment by voku** [comment]
1. but Kint::settings() was a setter + getter, or?

2. this property is not working anymore (for me), it set the class on load (via PHP), but the JS code remove it again...

```
    /**
     * @var bool expand all trees by default for rich view
     */
    public static $expanded = false;
```

**Comment by jnvsor** [comment]
1. Yes, the setter was removed
2. Hence my point: Are they being dumped expanded but in the folder? (There's a patch ~coming~ on master to turn this off when dumped with the modifier, but you'll still want to disable the folder if you want to set it as a default mode)

**Comment by voku** [comment]
1. ok

2. I don't know what you mean with  "folder", but I tried the current "master"-branch and this patch seems not to fix the issue. If I set "expanded = true", Kint is still not expanded by default. 

Here is the code that I modified for v3, I removed the "Kint::settings()"-things and added the namespace, but it did not work as before (2.x) / expected.

```php
/**
 * quick-debug: print the variable $var [exit] [echo || return]
 *
 * @param mixed $var
 * @param bool  $exit
 * @param bool  $echo
 * @param bool  $plaintext
 *
 * @return mixed
 */
function dd($var, bool $exit = true, bool $echo = true, bool $plaintext = false)
{

  $isCliRequest = is_executed_via_cli();
  $isAjaxRequest = is_ajax_request();

  /** @noinspection DisallowWritingIntoStaticPropertiesInspection */
  \Kint\Kint::$enabled_mode = true;

  /** @noinspection DisallowWritingIntoStaticPropertiesInspection */
  \Kint\Kint::$cli_detection = true;
  /** @noinspection DisallowWritingIntoStaticPropertiesInspection */
  \Kint\Kint::$expanded = true;
  /** @noinspection DisallowWritingIntoStaticPropertiesInspection */
  \Kint\Kint::$return = true;

  if ($plaintext === true) {
    /** @noinspection DisallowWritingIntoStaticPropertiesInspection */
    \Kint\Kint::$mode_default = \Kint\Kint::MODE_PLAIN;
  } else {
    /** @noinspection DisallowWritingIntoStaticPropertiesInspection */
    \Kint\Kint::$mode_default = \Kint\Kint::MODE_RICH;
  }

  if ($isCliRequest === true) {
    /* @noinspection DisallowWritingIntoStaticPropertiesInspection */
    \Kint\Kint::$mode_default = \Kint\Kint::MODE_CLI;
  }

  if ($isAjaxRequest === true) {
    /* @noinspection DisallowWritingIntoStaticPropertiesInspection */
    \Kint\Kint::$mode_default = \Kint\Kint::MODE_TEXT;
  }

  $output = \Kint\Kint::dump($var);

  /** @noinspection DisallowWritingIntoStaticPropertiesInspection */
  \Kint\Kint::$enabled_mode = false;

  if ($echo === true) {
    // protect against "headers already sent"
    \register_shutdown_function('printf', '%s', $output);
  } else {
    return $output;
  }

  if ($exit) {
    \http_response_code(HTTP_200_OK);
    exit(0);
  }

  return '';
}
```

**Comment by jnvsor** [comment]
Expand is a per-dump setting. Dumps are collectively being moved to a folder docked at the edge of the screen for use in document layouts where they would be too small to read. Again: Check `RichRenderer::$folder`

**Comment by voku** [comment]
Ok, thanks for the support ... if anymore has the same problem, here (again) the code:

```php
/** @noinspection DisallowWritingIntoStaticPropertiesInspection */
\Kint\Renderer\RichRenderer::$folder = false;
```
