### ISSUE TITLE
Kint output not showing up

### ISSUE THREAD

**Issue by kelesi** [kint-php/kint#294]
Hello. I just upgraded from Kint 2.x to 3.0 and the debug message are not visible. Kint is outputing html/ccss/js code, but it's not visible even when I paste it to a standalone html file. I uploaded the output. When I remove the javascript manually the Kint debug message is shown.

[kint.zip](https://github.com/kint-php/kint/files/2514358/kint.zip)

**Comment by jnvsor** [comment]
Look at the bottom of your window :wink:

**Comment by kelesi** [comment]
> 
> 
> Look at the bottom of your window wink

Lol. I did not notice that . I just looked at top where it was in version 2. 
Thanks and sorry for the useless issue.

**Comment by paxperscientiam** [comment]
@jnvsor , is there a setting for putting it back at the top?

EDIT: nvm, solution is in #284
