### ISSUE TITLE
Docked toolbar behavior with expansion functionality

### ISSUE THREAD

**Issue by Rarst** [kint-php/kint#295]
I spot the new docked toolbar, which can certainly be preferable under some circumstances. :)

However it seems to me it doesn't behave consistently with older functionality if you want things expanded. Forcing dumps with `!` or `Kint::$expanded` expands them _within_ the toolbar, while toolbar itself stays _collapsed_ on load.

It might make sense if toolbar could start expanded, whether implicitly from the expansion status of dumps within it or via explicit configuration (`$expanded` or dedicated setting).

**Comment by jnvsor** [comment]
Expanded is a per-dump setting. Unless you want the dock to be expanded even if only one of the 100 dumps you did is expanded, that's not going to work.

In the meantime, the version on master places dumps expanded with the `!` modifier outside of the panel, in the page layout, as before. (And you can always disable the panel with `RichRenderer::$folder`)

**Comment by Rarst** [comment]
Ok, I guess that's good enough. :) Thank you for reply.
