### ISSUE TITLE
Override calling file, line and function

### ISSUE THREAD

**Issue by viharm** [kint-php/kint#297]
Is it possible to override the calling file, function and line number?

**Comment by jnvsor** [comment]
Not *quite* sure why you'd want to do this. If you want the calling file/func/line to match a different function, you can add that function/method to `Kint::$aliases`

Otherwise you *can* override it but you'll have to construct the class manually

**Comment by viharm** [comment]
Hi @jnvsor , thanks for your prompt response. I use a wrapper function around *Kint* to add additional functionality like obfuscation (see #148 ).

Unfortunately, one of the limitations of my wrapper has always been lack of visibility of caller. I tried *Kint* aliases, but for some reason *Kint* stops dumping if my wrapper is in the alias list.

How may I construct the class manually?

**Comment by jnvsor** [comment]
> for some reason Kint stops dumping if my wrapper is in the alias list

That sounds wrong... Is your wrapper inside eval? If you can give me some example code I'd like to fix that asap.

As for #148, there was a *huge* rewrite for kint 2.0, and the plugin system is now much easier to use. I'd suggest you look at the documentation to [write a plugin](https://kint-php.github.io/kint/writing-plugins/) to block password hashes or password properties/array elements.

**Comment by viharm** [comment]
Agreed, I know I'm not doing this right; since the wrapper is quite old and from the old *Kint* days.

For reference, it takes a token title, echoes it out, then dumps the variables through *Kint* - https://gitlab.com/viharm/phpKhelper/blob/master/phpKhelper.lib.inc.php#L143

Your recommendation for using plugins is sound. I will try plugins and maybe even stop using this wrapper, as it is very clunky. It's whole point was to wait until *Kint* was capable of doing this :-)

**Comment by jnvsor** [comment]
If you end up needing (even) more control over it than just writing a plugin, you can start digging through [the facade](https://github.com/kint-php/kint/blob/master/src/Kint.php) to see what it does and reproduce it with tweaks. I'm proud of the flexibility I've built into Kint over the past few years :)

I'm going to close this issue for now. If you have any question writing a plugin, feel free to leave them here.

**Comment by viharm** [comment]
Hi @jnvsor , agreed. I am not experienced enough to comment on the code quality, but *Kint* is indispensible. I would rather create a plugin and contribute back rather than diversify into a wrapper.

Thanks for your hard work on *Kint*
