### ISSUE TITLE
javascript compression cause naming conflicts

### ISSUE THREAD

**Issue by VSilantyev** [kint-php/kint#30]
Seems like by default kint uses compressed javascript. 
This compression creates many global short-named variables, like:

``` js
i=function...
```

This global variables were overwritten somewhere in our big project. "i" is common name for cyclic variable. As a result - expand/close button in kint traces are not working.

I get rid of this by adding:

``` php
$_kintSettings['devel'] = true;
```

But I'm not sure that this will not break something in future releases.
I think there is no need for compression at all, anyway kint is used only in debugging environment.

**Comment by raveren** [comment]
Was not aware of that, thanks for the excellent bug reports, I'll see if I can play around with google closure settings to avoid this.
