### ISSUE TITLE
Config.default doesnt make sense

### ISSUE THREAD

**Issue by 0xCardiE** [kint-php/kint#301]
I am setting max depth with $GLOBALS['_kint_settings']['maxLevels'] = 5; but only to find out it is beeing overriden by $_kintSettings['maxLevels'] = 7; in config.default.php file. 
I mean I can delete it there and it will work, but this doesnt make sense, I might as well then change it there. This will also not work well with updates as I will then need to redo this. This config should be other way around or maybe it is somehow imagined to work that I dont understand?

**Comment by jnvsor** [comment]
You're using a version of kint that hasn't been updated since october 2016. Please use a version that's not ancient, and all your problems will be solved.

**Comment by raveren** [comment]
Yeah @adriadrop , you have a really really old version, like closer to 2014 :) I'm the original author of what you have, it's been improved upon for years since, and now @jnvsor is taking it to another level still, so good news to you, if you have issues porting, here's my personal setup:

```php
require ROOT . '/system/kint.phar';
Kint::$aliases[] = 'dd';
function dd(...$vars){Kint::dump(...$vars);exit;}
Kint::$file_link_format = 'http://localhost:8091/?message=%f:%l'; // phpstorm + remote call (plugin)
```

EDIT: once I go live with my project I also add a disable-by-default + enable for certain IPs (for example) functionality.

**Comment by 0xCardiE** [comment]
Sorry, I am just using drupal integration of kint. https://www.drupal.org/project/devel 
Maybe I just had old version of that module which integrated old kint, will need to check. Thanx for clarification.

**Comment by raveren** [comment]
Yup, it still uses pre-1.0, you can override the setting via `Kint::$maxLevels = 7;` anywhere you please - after Kint is included :)

**Comment by raveren** [comment]
Can I ask about the Drupal module (never used it) what is displayed with `ddebug_backtrace()`: is it Kint as well? :)

**Comment by jnvsor** [comment]
I tried working directly on a devel patch for a few months but I swear I could hear crickets in the background... No-one was interested.

Gave up in the end.
