### ISSUE TITLE
Table array view only showing types not values

### ISSUE THREAD

**Issue by robertkent87** [kint-php/kint#317]
I'm outputting some array data. In the array view it renders fine and I can see the values

![kint - array](https://user-images.githubusercontent.com/1167648/57916461-c5270700-788a-11e9-92dd-85fdde10c84d.png)

but this array defaults to a table view where only the value types are displayed, not the values themselves

![kint - table](https://user-images.githubusercontent.com/1167648/57916555-f8699600-788a-11e9-9ff3-e175f5801447.png)

Is there a setting I need to set to correct this behaviour?

**Comment by jnvsor** [comment]
You can tweak the settings in `BlobObject` to match your encoding if you want, then it should show up. You can try enabling the binary plugin to see a hex dump of the strings and see what it is.

I am however somewhat alarmed by your `binary string (0)` which should just be detected as an ASCII string. Is it possible you're removing *all* the encodings from the `BlobObject`?

Could you dump your `Kint\Object\BlobObject::$char_encodings` and `Kint\Object\BlobObject::$legacy_encodings` so I can see?

**Comment by robertkent87** [comment]
![kint-encodings](https://user-images.githubusercontent.com/1167648/57941943-291bf080-78c8-11e9-8c3e-0592816f771e.png)

**Comment by jnvsor** [comment]
Right, then I have no idea.

Could you get me your kint version and phpinfo? Do you have the mbstring extension installed? Also a separate reproducible file would be nice to help debug it.

**Comment by robertkent87** [comment]
Kint version: 3.2.2
PHP Version: 5.6.38
mbstring is **not** installed

**Comment by jnvsor** [comment]
> mbstring is not installed

Then there's your problem - I don't know if you've installed Kint through composer or not, but it suggests having either mbstring of the symfony polyfill, otherwise it can't do any string detection at all.

I should put a warning or a fallback or something in, so please leave this issue open for now.

**Comment by jnvsor** [comment]
This was fixed with an end-of-the-world fallback to ascii in 4fef22a1457f6d384120e7dd00fa1e722fff7d43 but I forgot to close the issue: Closed
