### ISSUE TITLE
Version Number Missing ?

### ISSUE THREAD

**Issue by marcoczen** [kint-php/kint#318]
Hi ...Why cant we see the version number  anymore ?
Should be visible somewhere ? Kint is now 2.x.y ?

**Comment by jnvsor** [comment]
I don't know what you mean, but if you click [releases](https://github.com/kint-php/kint/releases) you'll see the latest version is 3.2.2

**Comment by cloudsvrtech** [comment]
Noted. Thanks.

**Comment by marcoczen** [comment]
Noted. Thanks.
