### ISSUE TITLE
Use of undefined constant STDERR

### ISSUE THREAD

**Issue by harryqt** [kint-php/kint#320]
Hello, I'm getting the following Warning message:

> Warning: Use of undefined constant STDERR - assumed 'STDERR' (this will throw an Error in a future version of PHP) in C:\wamp64\www\inc\vendor\kint-php\kint\src\Object\ParameterObject.php on line 67

**PHP : 7.3.8**

**Comment by jnvsor** [comment]
That's extremely weird. I can't find stdanything in the entire history of that file. Which version are you using?

**Comment by harryqt** [comment]
I think xdebug was causing the problem.
