### ISSUE TITLE
Group header ?

### ISSUE THREAD

**Issue by beppe9000** [kint-php/kint#322]
is there some operator i can use to suppress the `string(12)` in front of the first parameter of `d('ERROR', $exception, $data1,$data2)`. I would like to use it as a group header...

**Comment by jnvsor** [comment]
It sounds to me like you might want to override the `RichRenderer` with a custom version for displaying your error messages. If you override the `preRender` function to include your header that should do the trick.

**Comment by beppe9000** [comment]
Thanks I'll try that

**Comment by jnvsor** [comment]
I'm going to go ahead and assume that worked and close this
