### ISSUE TITLE
INSPECTING STRUCTURE WITH POSTMAN

### ISSUE THREAD

**Issue by abelardolg** [kint-php/kint#323]
Hi,

When I am using Postman, I can't inspect the structure which is showed by using your library.

Is possible to inspect any object as I am using it with a web browser?

Kindest regards.

**Comment by jnvsor** [comment]
> Is possible to inspect any object as I am using it with a web browser?

The browser has javascript which is responsible for a lot of stuff. You can dump it as plaintext to see it in the raw response a la postman: `~d($var);`

**Comment by abelardolg** [comment]
Hi @jnvsor 
Sorry, but I didn't very well explain myself .

I meant how to inspect any structure **by using Postman** as I do usually in any web browser.

Sorry for my bad English.

**Comment by jnvsor** [comment]
If postman can't render HTML and/or doesn't support JS, you can't. Use a browser or make do with plaintext output mode. This sounds more like a question on how to use postman.

Or are we talking about something completely different? I'm thinking of the browser extension (now native app?) for building custom requests.

**Comment by abelardolg** [comment]
I am making POST requests. 

If I knew how to make POST requests by using a browser where I could inspect any object with this library, perfect!

**Comment by abelardolg** [comment]
I am requesting an improvement to this library to inspect any PHP object with this library by using POSTMAN.

Is possible?

**Comment by jnvsor** [comment]
> If I knew how to make POST requests by using a browser

I think there's a pretty massive knowledge gap in this issue. You might want to look into an HTML tutorial.

You're either asking me to make changes to postman (not kint) to rewrite the entirety of kint in *it*, or for *postman* to support HTML/JS like a fully-fledged browser.

Either way, this is not a Kint issue. Again, I'd suggest you use the plaintext output mode if all you're getting back is the raw response.
