### ISSUE TITLE
Disable flag does not work

### ISSUE THREAD

**Issue by DasJott** [kint-php/kint#325]
That flag `Kint::$enabled_mode = false;` meant to disable Kint functionality seems to be ignored.
It is still included into all of the pages.

Using newest version with php 5.3 ( I know, damn old... )

**Comment by jnvsor** [comment]
@DasJott In my test script it's working fine, more importantly it's also part of the unit tests to make sure that works. Are you sure some other part of the program isn't turning it back on again? Can you dump it and see what it says it is near the end?

**Comment by jnvsor** [comment]
Since I can't reproduce this I'm going to assume it's a problem in your setup unless you can get me some more info
