### ISSUE TITLE
howto show kint output correctly in phpstorm console?

### ISSUE THREAD

**Issue by michabbb** [kint-php/kint#326]
hi and pardon, I know this kind of question are not the ones that belong to here.

as many of you (i guess) are using phpstorm as well: today I tested phpstorm with remote docker.
seems like phpstorm is not able to show the output of kint correctly:

![image](https://user-images.githubusercontent.com/3524595/68766932-19cff280-0620-11ea-9e5f-4a601af8b6c8.png)

i don´t really know if that has anything to do with docker or if it´s just the JetBrains console that
is not capable of showing this kind of chars. the color is not the problem, it´s the chars.

does anybody here have an idea how to fix that ?

thanks for any help!

**Comment by michabbb** [comment]
[i also posted at the jetbrains forum](https://intellij-support.jetbrains.com/hc/en-us/community/posts/360006573940-Phpstorm-unable-to-show-special-chars-in-run-console), if someone wants to follow.

**Comment by jnvsor** [comment]
@michabbb Have you tried using master? c184db8c818d728ccd4e6d1ab5022572cfa661bc should have fixed this on windows. (New version release planned before PHP 7.4 hits this month)

**Comment by michabbb** [comment]
@jnvsor thanks for your feedback.  

1) i am stuck with php 5.6, so i guess i cannot use master
2) it has nothing todo with colors, your commit show only changes with colors

i tested with `~d(...)` but the output is the same....

**Comment by jnvsor** [comment]
1. Master supports down to 5.3
2. You're right, my mistake. The colors are working. It's the UTF-8 support that isn't. You can turn off the decorations with `Kint\Renderer\CliRenderer::$decorations = false`, or try tweaking your console's settings to allow utf8 (If it supports that)

**Comment by michabbb** [comment]
okay, will try later. seems to be a windows issue, at my forum post someone shows a Screenshot where everything looks fine 😔

**Comment by michabbb** [comment]
@jnvsor that seems to work:

![image](https://user-images.githubusercontent.com/3524595/69007776-8d387380-0942-11ea-9625-e5a5b06739e4.png)

but anyway, [as this guy pointed out](https://intellij-support.jetbrains.com/hc/en-us/community/posts/360006573940-Phpstorm-unable-to-show-special-chars-in-run-console?page=1#community_comment_360000942559), with linux you have no char garbage, so maybe this is a windows 
problem. i will create a bug report, let´s see what the devs will say 😏 
thanks for your help !!

**Comment by michabbb** [comment]
i don´t know if this is a bug or not, anyway, i filled a [bug report](https://youtrack.jetbrains.com/issue/WI-49702).

**Comment by michabbb** [comment]
@jnvsor just FYI it has nothing to do with kint, sorry. my phpstorm - why ever - is not capable of displaying Unicode inside a remote docker console window ☹️

**Comment by jnvsor** [comment]
@michabbb Yeah this is a common issue with windows terminals, putty does the same. I've left the other issue up because I'd like to find a way to detect it eventually (If not possible I'll just end up disabling or replacing UTF-8 on windows)

**Comment by michabbb** [comment]
@jnvsor the sad thing is: the guy helping me right now with my bug report is using windows, vmware, docker... everything the same... but his phpstorm displays unicode... it´s super strange... 😏

**Comment by michabbb** [comment]
@jnvsor and.... you don´t have to change anything - there is no need, really. your project is great. i work on windows, but my scripts are running with linux, on a real or virtualized host, so everything that runs is with linux - as it should be and not on windows 🙈  - with my windows ssh client, connected to any linux: everything is fine.  this all started because i wanted to test the docker capabilities of phpstorm, and accidentally found out, that there is something wrong 😏

**Comment by michabbb** [comment]
@jnvsor it´s getting a very funny and strange debugging journey, if you are interested, you can follow me [here](https://youtrack.jetbrains.com/issue/WI-49702) 😏
