### ISSUE TITLE
How do I get Kint to work?

### ISSUE THREAD

**Issue by judy5** [kint-php/kint#328]
I installed the plugin.

I am using wordpress. I created a folder on the server and put this code into it:
?php
 
// One of the files from the build folder
include 'kint.phar';
 
d('Dumped with Kint')
and gave the folder a name.

The I place this in my code so that I can see the value of the variables:
include 'kint.phar';
 d($entry_id, $entry_id);

But I see know where that Kind show me the output of these values, there is suppose to be a bar or someting :
[KINT.docx](https://github.com/kint-php/kint/files/4082523/KINT.docx)

**Comment by jnvsor** [comment]
> I installed the plugin.

We don't support third party plugins, but I suspect the problem is in your own code from what you posted.

Feel free to update the issue if you have any more info
