### ISSUE TITLE
Kint toolbar not visible with Bootstrap 4

### ISSUE THREAD

**Issue by Tilogorn** [kint-php/kint#330]
I was happily using Kint with `Bootstrap 3` in my project. After I migrated to `Bootstrap 4`, the kint toolbar disappeared.

It certainly is just a CSS issue, but I'm not able to fix it (backend-dev here :wink:). As Bootstrap is my "base"-framework I want to leave the used classes untouched and instead inject some custom css to `.kint-rich` to make the toolbar visible again.

I have a minimal working example [set up here](https://portal.alluris.de/bs4-kint/). It is just a copy of the official Bootstrap 4 [sticky footer/fixed navbar example](https://getbootstrap.com/docs/4.4/examples/sticky-footer-navbar/) with these lines of `php` on top:
```php
<?php
    require __DIR__ . '/vendor/autoload.php';
    Kint\Renderer\RichRenderer::$folder = false;
    d('foo');
?>
```
I'm aware of the fact that adding the PHP on top of the html and setting `folder` to `false` is part of the problem, but that it is exactly the use case of my project (where Kint gets called in the controller before the view gets loaded). `folder = false` is a personal preference which I don't want to give up on.

**Comment by jefvhal** [comment]
Seems like you are calling the d() before the body (even before the headers...). Therefore it is displayed at the very top. As you use the fixed navbar, this navbar is placed on top of the kint::dump. When I hide your navbar, the dump is perfectly shown.

Try calling the d() in the body instead of outside the body.

-edit-
OK, I was wrong: You are calling it in the body, but also calling all meta tags in the body (should be in the head element). Still, above applies. As kint::dump is called before your fixed `<nav>` element, it is hidden underneath the `<nav>`

**Comment by Tilogorn** [comment]
No, you were right: I'm calling it before the whole html document. As I tried to point out: that it is intended. In PHP you often have a lot going on (database calls etc.) before the view (= `<html>...</html>`) gets presented. I often want to dump something in controllers/models without touching the view, which results in Kint appearing at the top of the page (which is perfectly fine).

So calling `d()` inside `<body>` is no solution for this issue.

**Comment by jefvhal** [comment]
OK, clear. The biggest problem is the navbar, who has a fixed position (as intended) top:0. You could force the kint::dump to show on top by altering the z-index.

Changing this on the general kint-rich will change it for -all- kint dumps.

Quick & dirty:
`<div style="z-index:1100;"><?php d('foo'); ?></div>`

As the navbar has a z-index of 1030, this would push kint on top. Downside: the links in the navbar are now hidden by kint. adding margin-top to 90px will show kint under the navbar

`<div style="z-index:1100;margin-top:90px;"><?php d('foo'); ?></div>`

Really Quick & Dirty, so any other solution would possibly be better

**Comment by Tilogorn** [comment]
I was looking exactly for such a dirty solution. I tried adding a z-index before but never this high.
Overlapping the navbar or pushing the content downwards (side effect of your `margin-top` solution) is no problem here since I just use it for debugging, means: temporary calls where the page layout does not matter.

I'll just add the following to my styles:
```css
.kint-rich {
    z-index: 1031;
    margin-top: 90px;
}
```
so I won't have to change my dump calls.
Thanks a lot for your help!
