### ISSUE TITLE
[ Partial FIX ] d($_COOKIE)  - PHP Warning:  Cannot modify header information - headers already sent

### ISSUE THREAD

**Issue by marcoczen** [kint-php/kint#331]
Hi ... whilst using Kint to debug a page which has a setcookie snippet, i get the error below

    PHP Warning:  Cannot modify header information - headers already sent 
    by (output started at phar:///srv/www/vhosts/testapp/dbug/kint.phar/src/Kint.php:622)

Any idea why ? 

The warning goes away when I replace the Kint debugger ( d($_COOKIE) )  with  var_dump as below ...

    echo "Cookie  - "; echo var_dump($_COOKIE)."<br>";

I am on Kint v 3.3 btw.

Note : Line 622 in Kint.php contains

     echo $output;

which i suppose explains the error ( output will send more headers ) ? 
Is this normal for Kint - no support for snippets with  setcookie?  Or a bug ?

**Comment by jnvsor** [comment]
This is normal PHP. Any output will send headers because the body of a HTTP response comes after the headers. In the case of var_dump it's probably dumping so little text that it doesn't get flushed to the output.

Try using `Kint::$return` mode and echoing it after setting your cookie.

**Comment by marcoczen** [comment]
Hi .... I went to https://kint-php.github.io/kint/advanced/ and could not find any doc 
about Kint::$return ?

So you want me to put 

    Kint::$return;
    setcookie(session_name(), " " , 1 , $params["path"], $params["domain"], 
              $params["secure"], $params["httponly"] );  
    d($_COOKIE);

?

Anyway ... to the next reader .. i just used ob_start() and ob_end_flush() in the script

**Comment by jnvsor** [comment]
You're looking for https://kint-php.github.io/kint/settings/

If you do the `d()` call after the setcookie you won't need return anyway, unless you're trying to set headers again later

**Comment by marcoczen** [comment]
Thank u. We know you are the main  developer and your time has to go into development mainly. Kint is great.  The partial fix is ok for me.

At the link you gave, I dont see how i can echo the output. So the partial fix is ok for me. Thanks.

**Comment by xampp2** [comment]
"I experienced this error and solved it this way. Although I did not understand what it had to do with this code."

Write This code before Top of ur php codes and Test again.u can then clear `that.`

```
<?php
// Prevent "headers already sent" error with utf8 support (BOM) 
 header('Content-Type: text/html; charset=utf-8');
?>

```

**Comment by mopsyd** [comment]
Simplest answer for this:

in your index.php

```
ob_start();

// do everything your program does

ob_end_flush();
```

this will buffer output and not send it until the end of execution, preventing printing from interfering with cookies, session, etc.

If you get a fatal error, you may also need to check if the output buffer has any stack level and flush it in a shutdown function. This depends on your php settings. Usually it is not neccessary. If you are getting whitescreens on fatal errors, you need to do this step also.
