### ISSUE TITLE
Improving the doc

### ISSUE THREAD

**Issue by abelardolg** [kint-php/kint#333]
Hi there,

I'm here to suggest an improvement at your doc: https://kint-php.github.io/kint/settings/

Where should I write these settings line: PHP class, config file I should create...?

How could I show the output on the top instead on the bottom (by default)?

Best regards.

**Comment by jnvsor** [comment]
> Where should I write these settings line: PHP class, config file I should create...?

I'm not sure what you mean

> How could I show the output on the top instead on the bottom (by default)?

You would change the CSS, either by wrapping the renderer or by inserting your own.

It wouldn't be particularly easy though. In any case, since the folder isn't going to be default any more (And may be removed altogether if I can't get the keyboard navigation to work properly) I don't think that belongs in the docs

**Comment by abelardolg** [comment]
Hi there, 

Where should I write these settings line: PHP class, config file I should create...?

At https://kint-php.github.io/kint/settings/ appears this line:
`Kint::$enabled_mode`: where should I write this sentence to config this option: in my PHP class, in any config file, by setting its value using a command...?

Certainly, the second question should be added to the FAQ section.

Best regards.
--

**Comment by jnvsor** [comment]
> At https://kint-php.github.io/kint/settings/ appears this line:
Kint::$enabled_mode: where should I write this sentence to config this option

Wherever you like - it's just code.

> Certainly, the second question should be added to the FAQ section.

There is no built-in option for that, so it would involve quite a bit more than belongs in an FAQ
