### ISSUE TITLE
Deprecate blacklist/whitelist in favour of blocklist/allowlist

### ISSUE THREAD

**Issue by normanlolx** [kint-php/kint#337]
There's the `$parser_plugin_whitelist` and there's the `BlacklistPlugin` with quite some occurrences of these problematic strings. Of course also in the test. I guess we can't simply replace the one strings provided by PHPUnit but maybe let's start by providing alternatives for the ones we currently have in Kint and deprecate the old ones for now.

**Comment by jnvsor** [comment]
No

**Comment by Schnitzel** [comment]
great idea @leymannx!

How about `$parser_plugin_allowlist` and `BlocklistPlugin`?

**Comment by damienmckenna** [comment]
@jnvsor: Could you please explain why a list of items to be blocked should be called a "black" list - what definition of "black" do you consider the relevant one? Ditto for why a list of items to be allowed should be called a "white" list. Thank you.

**Comment by normanlolx** [comment]
Wow, look at this [change record from PHPUnit 9.3]( https://github.com/sebastianbergmann/phpunit/blob/master/ChangeLog-9.3.md) I've been just made aware of! All references to blacklist/whitelist are now deprecated and replaced by exclude-list/include-list references. So they are one step ahead now. I think Kint is such a great tool and definitely should catch up. References to black=bad and white=good can easily be seen as offensive language and there are so many better terms to replace them.

Like @Schnitzel specified from the issue title `$parser_plugin_allowlist` and `BlocklistPlugin` sound fine. But maybe `$parser_plugin_includelist` or `ExcludelistPlugin` are good candidates as well.

**Comment by deanvalentine** [comment]
> No

Perhaps you could elucidate more on this reply. Replying with a  simple "No" and then not engaging further can come across as a little tone-deaf.

Many other projects (such as MySQL, Github themselves and even Linux) are going down this path of more inclusive language. Why not join them?

**Comment by bookworm2000** [comment]
@jnvsor Python, Drupal, Github, and Django have all worked to remove master/slave language and promote more inclusive language. Apple and Twitter are removing the term blacklist. Does this project have to keep words with racist undertones, which communicates to open source developers that not everyone is welcome in this community?

**Comment by raveren** [comment]
Wow you see a race issue in the word "black"?? Holy hell world's full of mad people

**Comment by joehuggans** [comment]
When does political correctness go too far?

**Comment by normanlolx** [comment]
When does empathy harm?

After all, blacklist/whitelist simply are not precise terms. Name it butterflylist/elephantlist, same.

Blocklist/allowlist or excludelist/includelist simply is a more precise wording. Can we agree on that?

**Comment by joehuggans** [comment]
I don't believe this is empathy, I believe this is political correctness grounded in post-modern thought. 

I don't believe it is making people more empathetic, I believe it is making people fearful of saying the wrong thing.

True racism is when we stop seeing the skin colour, blacklist and whitelist are just words, they are not associated with race.

**Comment by normanlolx** [comment]
I value your opinion and I don't see a contradiction in renaming these terms though. I like that you don't associate these terms with race. Maybe you can imagine that others do associate them with race. That language can be racist. But language also can be inclusive. No one needs to be afraid of making mistakes. That's okay. We can learn. We can develop. Let's simply choose neutral equivalents for these imprecise terms. 🤗

**Comment by joehuggans** [comment]
It is not so much I have a problem with this particular change of terms, it is the ideology which drives it which I see as a problem. But I still welcome your perspective, I just don't think langauge can be racist, it is the intention behind language which makes it racist.

**Comment by joehuggans** [comment]
@damienmckenna Because white is the presence of all colours, and black is the absense of colour. "All other colors are reflections of light, except black. Black is the absence of light".

**Comment by damienmckenna** [comment]
@joehuggans: You might do yourself a favor and listen to this podcast: http://www.sceneonradio.org/seeing-white/

**Comment by joehuggans** [comment]
Sure, and you should listen to this: https://www.youtube.com/watch?v=ofmuCXRMoSA

**Comment by damienmckenna** [comment]
Jordan Peterson? That sexist bigot? No thanks.

**Comment by joehuggans** [comment]
Any evidence for that claim?

**Comment by damienmckenna** [comment]
https://samirchopra.com/2018/06/08/jordan-peterson-is-a-sexist-tool/

**Comment by joehuggans** [comment]
That is utterly terrifying.

**Comment by georgjaehnig** [comment]
@leymannx:
 
> I value your opinion and I don't see a contradiction in renaming these terms though. I like that you don't associate these terms with race. Maybe you can imagine that others do associate them with race. That language can be racist. But language also can be inclusive. No one needs to be afraid of making mistakes. That's okay. We can learn. We can develop. Let's simply choose neutral equivalents for these imprecise terms. 

I have heard this reasoning a few times already, and I am genuinely curious how far it would go. From what I understand, it goes:

- there are people that associate these terms with race
- these people feel then excluded
- so to include them, we shall rename the terms.

Now, does this also extend to other areas, e.g. [Gender of connectors and fasteners](https://en.wikipedia.org/wiki/Gender_of_connectors_and_fasteners)? If there were people who associate them with gender (of humans) and feel excluded because of it, would that be sufficient enough that engineers should change these terms?

**Comment by joehuggans** [comment]
They believe that we live in a society dominated by white straight males, they only see group identity, it is cultural marxism which has been spread through the universities.

So if the language is seen to make people uncomfortable (apart from straight white males) then they will try to change it.

**Comment by normanlolx** [comment]
Not sure how far this goes. Maybe we can fix these imprecise terms some day. 🤷

**Comment by georgjaehnig** [comment]
@leymannx But which condition is sufficient enough for you to change a term? That there are people who say they feel excluded by it?

**Comment by normanlolx** [comment]
Common sense.

**Comment by georgjaehnig** [comment]
@leymannx Well, then apparently the condition is not met here: The views on this question are visibly highly disputed, not common at all.

**Comment by normanlolx** [comment]
Thank you for the explanation. 🤣

**Comment by georgjaehnig** [comment]
Thank you! I knew: When we talk about (language) politics the programmer's way, we can quickly come to an understanding. ;)
