### ISSUE TITLE
Rename master branch to main

### ISSUE THREAD

**Issue by normanlolx** [kint-php/kint#338]
Before I provide much context I guess everybody is aware of the current discussions about master/slave references. Let's jump in and rename the `master` to `main`.

**Comment by jnvsor** [comment]
No

**Comment by Schnitzel** [comment]
I agree with @leymannx, changing from `master` to `main` will be the standard soon on github: https://twitter.com/natfriedman/status/1271253144442253312 so we better keep up with changing standards :)

**Comment by bibliophileaxe** [comment]
+1 for this. It's a minor change and *should* be done.

**Comment by normanlolx** [comment]
This issue was probably closed in a rush. Renaming a default branch in a repository, does not fix any current societal issues, of course. It's not that simple. But this change is not to restore justice in the world, it's only changing a single word. The master terminology in Git is historically tied to the master/slave metaphor, see https://mail.gnome.org/archives/desktop-devel-list/2019-May/msg00066.html. So let's change it something more inclusive instead.

Codewise there are only three references at all in Kint, as far as I can see: two in the README and one in the CONTRIBUTING.md. Github now also allows project admins to edit the base branch of an open PR, so any open merges against master could be updated to use the new main branch after it is created. I only wonder what happens for people that have `"kint-php/kint": "dev-master"` in their project's dependencies. They probably need to update it to `"dev-main"` then.

I also find this blog post from Kapwing about [How to Rename Your Master Branch to Main in Git](https://www.kapwing.com/blog/how-to-rename-your-master-branch-to-main-in-git/) quite enlightening. It lists some pros and cons of the renaming and also show some sample commands how this can be done.
