### ISSUE TITLE
Add option to delay output untill end of main program

### ISSUE THREAD

**Issue by fleokan** [kint-php/kint#341]
Hi, i would like to have modifier which make functions like d() cache their output insted of printing it into page, this will help a lot in debugging ajax and pre render parts of the code as kint force php to send default headers when he start output which i need to prevent

**Comment by jnvsor** [comment]
Hi @fleokan, you can write your own helper function to do this. [The site docs](https://kint-php.github.io/kint/advanced/#helperfuncs) have more info on the subject.

You can use `register_shutdown_function` in your helper or store the output in some variable and render it at the end of the page.

**Comment by kktsvetkov** [comment]
@fleokan look if this would help. It does what was suggested -- it collects the output and then queues it with `register_shutdown_function()`

```php
function fleo(...$vars)
{
    Kint::$return = true;
    $output = Kint::dump(...$vars);
    register_shutdown_function('print', $output);
}
```

**Comment by jnvsor** [comment]
Yeah, @kktsvetkov 's version will work fine for you. I'll go ahead and close this for now, comment if there's anything else
