### ISSUE TITLE
NULL instead of empty array

### ISSUE THREAD

**Issue by coalaura** [kint-php/kint#345]
If i debug an associative array and one of the values is an empty array, the debugger will print it as NULL instead of an empty array.

**Code:**
```php
d([
    'sdkadlfjhald' => [
        'key1' => 'value',
        'key2' => null,
        'key3' => false,
        'key4' => [
            'abc' => [
                'en' => 'abc',
                'de' => 'abc'
            ],
            'def' => [
                'en' => 'def',
                'de' => 'def'
            ],
            'ghi' => [
                'en' => [],
                'de' => [] // THESE VALUES ARE EMPTY ARRAYS
            ]
        ]
    ]
]);
```

**Result:**
![result](https://i.imgur.com/MoBZIP6.png)

This issue seems to appear if you have multiple keys having similar values and they get rendered in a table.
```php
d([
    'abc' => [
        'en' => 'abc',
        'de' => 'abc'
    ],
    'def' => [
        'en' => 'def',
        'de' => 'def'
    ],
    'ghi' => [
        'en' => [],
        'de' => []
    ]
]);
```
![other result](https://i.imgur.com/mvBbIUV.png)

**Comment by jnvsor** [comment]
Which version of kint are you using? Since there is only one rep this looks like version 1 which hasn't been touched in 4 years, and it shows `array(0)` in my test.
