### ISSUE TITLE
Screen position

### ISSUE THREAD

**Issue by mambax7** [kint-php/kint#357]
Great tool! Thank you! 

It seems like in the ver. 3.x, the Kint is now on the bottom of the screen. 
Is there a way to have it on top of the screen, as it used to be? Is this something I could change locally?

**Comment by jnvsor** [comment]
You can disable it with `Kint\Renderer\RichRenderer::$folder = false` or install from master where it's off by default again

**Comment by mambax7** [comment]
Thank you!
