### ISSUE TITLE
kint in WordPress -- pages fail to render, error: "Cannot modify header information - headers already sent by ..."

### ISSUE THREAD

**Issue by huna02** [kint-php/kint#358]
i've installed `kint.phar`
```
ls -al /opt/kint/build/kint.phar
	-rw-rwx---+ 1 root root 393K Apr  2 07:44 /opt/kint/build/kint.phar*
```

in my Wordpress install, I've replaced working `var_dump()` with
```
cat wp-config.php
	<?php
	include '/opt/kint/build/kint.phar';
	Kint::$enabled_mode = true;
	d($_SERVER);
//	var_dump($_SERVER);
	...
```

On nav to

	https://example.com/wp-admin

(1) with NO debug statement, renders OK.

(2) with `var_dump()`, renders OK, displaying dump

(3) with `d()`, kint displays output at top of otherwise blank page; no add'l page render

in logs, only
```
==> /var/log/nginx/php-fpm.log <==
[02-Apr-2021 15:15:13 UTC] PHP Warning:  Cannot modify header information - headers already sent by (output started at phar:///opt/kint/build/kint.phar/src/Kint.php:596) in /home/www/site/wordpress/wp-includes/pluggable.php on line 1332
```

**Comment by jnvsor** [comment]
@huna02 If you write more than the buffer can store before wordpress sends the headers PHP will spit out a warning. Either from your settings or from wordpress it seems to be refusing to continue the script after this warning. `d` outputs far more than `var_dump` so it's flushing the buffer and starting the response.

You can either run `d` after the headers are sent (For example in a wordpress hook) or just turn it off when you want to run the page again.

**Comment by huna02** [comment]
closed? so much for any disucssion.

deleted.

thx anyway.
