### ISSUE TITLE
Save to logfile

### ISSUE THREAD

**Issue by konstantin83** [kint-php/kint#369]
Hi! Thanks for a wonderful component. I am planning to use it a lot.

My question is this — is there a way to save dumped data to a file from browser as if the script was called from cli?
I tried to use:
```
    file_put_contents(
        $_SERVER['DOCUMENT_ROOT'] . '/_main.log',
        date("Y-m-d H:i:s") . "\n" . @d(111) . "\n",
        FILE_APPEND | LOCK_EX
    );
```
but I get html code of the whole kint's browser output instead of something like the output of print_r().

Playing with +, !, -, ~ didn't make effect either.

**Comment by jnvsor** [comment]
Yeah, assuming you want to make it a plain text file you'd want return mode and the plain renderer. Unfortunately if you combine `@` and `~` you end up with the entire output flipped so you'd have to set it manually:

```php
Kint::$return = true; // Same as @d()
Kint::$enabled_mode = Kint::MODE_TEXT; // Same as ~d()
``` 

Then a standard `d()` will return the string you want. (If you plan on opening the file with `less -R` or something to preserve colors you can set it to `MODE_CLI` instead to dump with color control chars)
