### ISSUE TITLE
JS error when not using die() right after d()

### ISSUE THREAD

**Issue by chrion02** [kint-php/kint#370]
Whenever i dump something with d() i get an js error.
![kint-error](https://user-images.githubusercontent.com/25898806/140297243-6329750f-7084-4d97-90ce-fa26f6138d5b.png)
This error does not occur if i use die() or exit() right after i use d(). The content of the d() dosen't matter. I tried both downloading the kint.phar directly and composer, both with the same result.

When getting the error, kint is shown either in-line or at the bottom depending on Kint\Renderer\RichRenderer::$folder but nothing happens when i click on the output to expand it.

**Comment by jnvsor** [comment]
> This error does not occur if i use die() or exit() right after i use d().

This pretty much confirms that this isn't a problem with kint itself. Also, `&#038;&#038;` is the htmlentity encoding for `&&`... It's clearly being buffered and escaped by whatever framework or templating engine you're dumping from.

For my curiosity: What framework/templating engine is that?

**Comment by chrion02** [comment]
> For my curiosity: What framework/templating engine is that?

I'm running WP in a https://varyingvagrantvagrants.org/ environment :)

**Comment by jnvsor** [comment]
Odd, I don't remember wordpress escaping stuff by default. Do you use wordfence or some other paranoid plugin?

**Comment by chrion02** [comment]
No weird plugins no :) yoast SEO only

**Comment by jnvsor** [comment]
And you're dumping straight from a template or in a hook or filter?

**Comment by chrion02** [comment]
Straight from a template.

**Comment by jnvsor** [comment]
Why do people keep inventing overcomplicated ways of doing stuff? _sigh_

Vagrant won't work because of some obscure virtualbox networking error and the closest fixes I can find don't work either. It works fine in vanilla wordpress so I'll have to leave it at that.
