### ISSUE TITLE
Use Kint without Phar and without Composer

### ISSUE THREAD

**Issue by DRSDavidSoft** [kint-php/kint#377]
I'm sorry to ask such a basic question, but I couldn't figure out how I could use Kint without the phat package and without composer.
As in doing a `git clone`, or downloading a Zip file and extracting it.

I thought `include`ing the `init.php` file would be sufficient, but it appears not.

Please forgive me if I'm not finding the relevant information or don't know an obvious solution to this, but how would I include it like this?

**Comment by jnvsor** [comment]
The phar has its own autoloader, and the init assumes an autoloader exists (So either the phar one or composer)

So do a `composer install` in the cloned folder and include the autoloader from vendor in the cloned folder.

Alternatively, the phar is committed in the repo so you can just require it from the build folder if you don't intend to tweak the code

**Comment by DRSDavidSoft** [comment]
Awesome, thanks for the info!
