### ISSUE TITLE
Kint throws an error itself trying to output stream variables

### ISSUE THREAD

**Issue by maskas** [kint-php/kint#38]

**Comment by raveren** [comment]
I need more info to reproduce issue, works for me (standard PHP5.3):

``` php
dd( fopen( __FILE__, 'r' ) );
```

![Screen](https://f.cloud.github.com/assets/364220/53638/379ef454-5a70-11e2-9c10-e7164d814f56.png)

**Comment by maskas** [comment]
I don't have more details at the moment. The problem is not when you do dd(stream), but when there is an error in function which has a stream as an argument. I will post more details if I meet the same again.

By the way, it happened on PHP 5.4. But I doubt if it is PHP 5.4 related.

**Comment by raveren** [comment]
What kind of stream is enough info. File? Local/remote?

**Comment by maskas** [comment]
I have reproduced the error. Might be it is not related to streams, but to PHP 5.4. Because the same code works on 5.3.

Code I'm executing
        //$type ==  'products';
        //$api->getError() == '';
        throw new errException( 'API: id request failed', $type, $api->getError() );

The error I get is:

ReflectionException [ 0 ]: Method productsCmsHelper::__callStatic() does not exist ~ C:\xampp\htdocs\system\core\kint\Kint.class.php [ 175 ]

I don't think you will reproduce it very easily as it should be related to function arguments or something. But I didn't find it yet.

**Comment by raveren** [comment]
You're using an older version of kint, but that's not the issue, the error is raised in `Kint::trace()` method and is directly related to PHP versions, although looking at the source, it should break on <PHP5.3, no idea why it does that on 5.4. I'll push the patch once I get to test this on all three - 5.2, 5.3, 5.4 versions. 

Thanks for the report!

**Comment by raveren** [comment]
this should have been fixed in the latest HEAD revision, but I couldn't reproduce the issue.
