### ISSUE TITLE
Scope-based disable mode

### ISSUE THREAD

**Issue by Endermanbugzjfc** [kint-php/kint#385]
I am a PocketMine-MP plugin developer and want to use Klint for debugging my code. I will set Klint to the disabled mode when releasing the plugin. However, I worry that Klint settings are shared between multiple plugins. Therefore, if I do it in my plugin. Other developers who had installed my plugin as a dependency will not be able to use Klint for debugging their codes.

# TL;DR
Please add a scope-based (specified functions, namespaces, etc...) disable mode.

**Comment by jnvsor** [comment]
While that's an interesting idea, I'd say the easy way to do this would be to write your own wrapper function and passthrough to kint, then disable it in there with your own setting. That way you wouldn't depend on the global Kint setting.

Something like:

```php
Kint::$aliases[] = ['MyUtilClass', 'd'];

class MyUtilClass
{
    public static $enable = false;

    public static function d(...$opts)
    {
        if (!self::$enable) {
            return 0;
        }
        return Kint::dump(...$opts);
    }
}
```

Then you call `MyUtilClass::d()` instead and you can turn it on and off at will without effecting anything else

> I will set Klint to the disabled mode when releasing the plugin.

I'm not sure how these plugins are packaged, but you should consider not shipping Kint at all for a release build unless you expect users to need to enable it for some reason (ie. `require-dev` in composer terms) especially if you only intend to use it for your own development
