### ISSUE TITLE
kint.phar: continue2 or break?

### ISSUE THREAD

**Issue by Uv516** [kint-php/kint#396]
In Drupal 9.4.7, php 7.4 I have inserted kint.phar:
Call to dpm is working fine, but:
When I call dpm I get a watchdog message: _Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in include_once() (line 147 of (website)/core/lib/Drupal/Core/Extension/Extension.php)._
kint.phar is called as:
 ```
 if(file_exists(__DIR__.'/kint/kint.phar')){
    require __DIR__.'/kint/kint.phar';
  }
```

**Comment by jnvsor** [comment]
Since drupal bugs almost always end with "Devel is always using an ancient Kint version" I've got to ask what version they're using. Does this still happen if you replace the phar with the one from this repo?

**Comment by Uv516** [comment]
The kint.phar is from this link: https://raw.githubusercontent.com/kint-php/kint/master/build/kint.phar
Downloaded sunday 9. october.

**Comment by jnvsor** [comment]
Well I've skimmed all my switches and haven't found any continues. The file and line your message refers to only shows the require of the phar itself. Is there a more complete stack trace in this error or is that all they're giving? Because if that's an up to date phar I'm guessing the actual warning is coming from drupal or devel somewhere

**Comment by Uv516** [comment]
The message comes from Drupal. Apparently from Extension.php. The strange thing is that there is no continue in extension.php at all.
I have tried various things and came to the conclusion that "require kint.phar" gives "continue"-error. When I remove the "require kint.phar" line, there is no "continue"-error.

**Comment by jnvsor** [comment]
Yeah the line they point to is the require of the phar, but if there's no continue in the kint code then it must be calling into drupal code through and the drupal code is causing it. Any idea where I can see the devel code? I don't think they have a github repo. They might be adding their own plugins or something

**Comment by jnvsor** [comment]
No further info, closing. I'll reopen if you feel like you can debug further
