### ISSUE TITLE
feature request: add keyboard shortcut to expand all nodes

### ISSUE THREAD

**Issue by taat** [kint-php/kint#40]
Keyboard shortcut to expand all of the nodes would by highly appreciated.
(eg. "f" to expand the nodes and start keyboard navigation, "j" to expand first node and start keyboard navigation)

BTW, there's no direct link to github project on the project home page suggested by google: http://raveren.github.com/kint/

**Comment by brunowego** [comment]
+1

**Comment by raveren** [comment]
@brunowego : are you aware there's keyboard shortcuts at all? You press `d` and then navigate the tree as usual (you must use the wip branch though https://github.com/raveren/kint/tree/1.0.0-wip) - and also if you append a `!` like this: `!dd($GLOBALS);` the output will be expanded by default.

In the years I've been using Kint I've never missed the requested shortcut yet. Still, I might get to implementing it at some point...

**Comment by jnvsor** [comment]
I also find keyboard navigation more than sufficient. In the rare case where you *actually* want to expand **all** nodes taking the time to tripleclick the `[+]` is probably a good idea anyway, since this could easily freeze your browser if you've been dumping tons of stuff.
