### ISSUE TITLE
Solarized-dark theme changes body text and background color

### ISSUE THREAD

**Issue by LoranRendel** [kint-php/kint#405]
Solarized-dark theme changes body text and background color making page unreadable for complex design pages.

**Comment by jnvsor** [comment]
Yeah I suppose the purpose of that was superseded by the rich folder. I'll have to do some other tweaks to the style after removing the body styles but I'll remove that since it's inconsistent with the other themes

**Comment by jnvsor** [comment]
Fixed in b8b1da8 (5.0.4)

**Comment by LoranRendel** [comment]
Thanks.

However, .kint-rich uses margin and there will be stripes.
![image](https://user-images.githubusercontent.com/7853801/221903252-b3f64f80-b699-4d48-b182-f3fd9884bc1d.png) ![image](https://user-images.githubusercontent.com/7853801/221903446-83e1ad0b-ff11-4aff-923c-9d6283e9595b.png)

It will be better to set `box-shadow: 0 0 0 10px #073642` for `.kint-rich` or remove margin:
![image](https://user-images.githubusercontent.com/7853801/221903898-4f399f66-8563-401a-b80a-481cea0af6bf.png) ![image](https://user-images.githubusercontent.com/7853801/221903752-82305d43-2813-48ed-9245-10c64edcb70b.png)

**Comment by jnvsor** [comment]
> .kint-rich uses margin

This is consistent with all the other themes. If you want to remove the margin (Or change it to padding or something) make your own style changes and put them in your stylesheet or `RichRenderer::$pre_render_sources`

**Comment by LoranRendel** [comment]
Already did. Yes, you're right, thanks!
