### ISSUE TITLE
Can't return plain text with modifiers

### ISSUE THREAD

**Issue by GlassGruber** [kint-php/kint#414]
Hei there

I've tried to log the returned plain text from kint by using the modifiers as following, but unfortunately the resulting log file contains garbled encoded text.

```php
<?php
include '/pathto/kint.phar';

error_log(
   @~d('plain text via kint!')
  ,3
  ,"/pathto/kint.log"
);
```

The following instead works as expected, but I wonder if this is intended or if I'm missing something

```php
<?php
include '/pathto/kint.phar';

Kint::$return = true;
Kint::$mode_default = 't';

error_log(
   d('plain text via kint!')
  ,3
  ,"/pathto/kint.log"
);

```

Thank you!

**Comment by jnvsor** [comment]
Your `~` modifier xors the returned string. You can fix that by xoring it twice (`@~~d("...")`) but honestly the return modifier should just be used on its own. (If you used any other modifier the returned string would be irretrievable, eg. `@!d()` casting the output to a bool)

Your second example is what you should use, though you can also create a [helper function](https://github.com/kint-php/kint-helpers/blob/339884c2ec32aea9200763fd2a93b037acdb873a/init.php#L92) dedicated to returning plain text.

**Comment by GlassGruber** [comment]
> Your second example is what you should use, though you can also create a [helper function](https://github.com/kint-php/kint-helpers/blob/339884c2ec32aea9200763fd2a93b037acdb873a/init.php#L92) dedicated to returning plain text.

Thank you for your answer, yes this is what I ended up with. I leave it here also in case someone may need it

```php
Kint::$aliases[] = ['yourClass', 'td'];

class yourClass 
{
   public static function td(...$args)  {
        

        if (false === Kint::$enabled_mode) {
             return 0;
        }

        $kstash = Kint::$enabled_mode;

        Kint::$enabled_mode = Kint::MODE_TEXT;
        Kint::$return = true;

        $out = Kint::dump(...$args);

        Kint::$enabled_mode = $kstash;
        Kint::$return = false;

        return $out;
    }
}
```
