### ISSUE TITLE
Show dump time

### ISSUE THREAD

**Issue by rozbyn** [kint-php/kint#418]
I think it will be cool if kint shows its call time, near to call trace. Something like this:
![Screenshot_161](https://github.com/kint-php/kint/assets/34918480/fdafd85f-cfd4-4728-8b84-b6440ccc0f53)
![Screenshot_162](https://github.com/kint-php/kint/assets/34918480/ba4f4ce7-6336-4316-b357-7e8407fe121d)

**Comment by jnvsor** [comment]
Well generally kint dumps will be in a web page, in which case all the timestamps would be the same (Or at most off by 1 second if it crosses the boundary during the run) In that case I'd say just stick a timestamp on the page, or override `RichRenderer::postRender` if you really need it for some specialized logging solution.

The only use cases I can think of for rendering the timestamp on every dump would be if a page is loading _really_ slowly and needs to be debugged, or when you want to measure much smaller time differences than your examples would show anyway. In both those cases we have a `microtime()` plugin that does the job.

There's also the case of dumps that take a long time, and then there's a question of whether the timestamp would be at the start of a dump, at the end of a dump, or halfway through between the parse and the render. The explicitness of calling `microtime()` means you (as a user) don't have to worry about any internal timing issues.

Can you think of any special use case where this would be necessary? I wouldn't mind adding it to `RichRenderer` as an option if you can, but I think it would find more use in `TextRenderer` where it might be used in logs and the like

**Comment by rozbyn** [comment]
I think it's may be useful when developer not sure, dump was executed right now, or an hour ago, when content may be same. Sometimes i want to dump into html file like `@d();`, with good formating, when cron works, or incoming web-hook

**Comment by rozbyn** [comment]
As an option will be good) If it not very popular feature request - i override RichRenderer::postRender)

**Comment by jnvsor** [comment]
I wanted to add it for text renderer and it was simple enough (And lightweight enough since it only gets used once on `postRender`) so I added it to the rich renderer too. 3be3e46f1c4f2790c2ec86cfd5211f9cb7e2a497

I'll push the documentation when it's tagged
