### ISSUE TITLE
Allow class in shallow_blacklist to display occurrences of same class in it's own dump

### ISSUE THREAD

**Issue by GlassGruber** [kint-php/kint#419]
I've dumped directly an object that is present in `$shallow_blacklist`, the dump works correctly as expected but as you can see in snippet below other items inside that same object are of the same class and are blacklisted, is there a way to allow them as well?

Thank you!

![image](https://github.com/kint-php/kint/assets/1172428/4dd48c85-9978-42b1-bb0b-48a348f24623)

**Comment by jnvsor** [comment]
Yeah, just remove `Form` from the blacklist. (Assuming it's `Form` you have blacklisted and not one of its interfaces)

The normal blacklist is more for security purposes (IE hiding credentials that should never be dumped) while the shallow one is more for performance and clarity.

The `shallow_blacklist` differs from the normal one in that it _will_ allow dumping of something explicitly (So at the top level) but won't dump that class when it's found deeper in the data structure. This is great for things you may want to dump occasionally but can bloat your output if you dump them everywhere they're found. (The container is the prime offender here)

If you remove it from the blacklist entirely you'll see what's in there, but it'll dump every `Form` you come across which is probably not what you want or you wouldn't have blacklisted it in the first place.

There's no special case for blacklisting a class that contains copies of itself _except_ when you dump that class at the toplevel.

You could write your own plugin for this based on `BlacklistPlugin` if you wanted to, that tracks the toplevel classname, but when I run into this stuff with something I've blacklisted I usually just dump the children explicitly like `d(...$form->all())`

**Comment by GlassGruber** [comment]
> when I run into this stuff with something I've blacklisted I usually just dump the children explicitly like `d(...$form->all())`

Make sense, also yea dumping the object with a spread to lower the nesting depth is a nice trick thank you!
