### ISSUE TITLE
Adding additional information to value lines

### ISSUE THREAD

**Issue by HLeithner** [kint-php/kint#433]
I have kint plugin which checks for an object of type `Joomla.....QueryInterface` the [Joomla query interface](https://github.com/joomla-framework/database/blob/3.x-dev/src/QueryInterface.php) is  holds a database query against different sql versions including the payload like prepared statement parameters

This is an example of the output with one prepared statement:

![image](https://github.com/user-attachments/assets/7b9b213c-ddad-48b2-9769-db0db7ffbd39)

As you can see I have added 4 entries to the tab, the last one (Full prepared parameters) is a bit redundant, because it only adds information to the one before (Prepared Parameters).
My issue I try to solve without too much effort is to show the value of `:x` where we have `:x => stdClass#1118 (4)`, next to it o by replacing `stdClass#1118 (4)` with `integer 5`. 
So actually allow adding childs to every `Value` type, like in this case for the `FixedWithValue` value.

Is this possible without writing a `parser` and own `value` classes?

**Comment by jnvsor** [comment]
Yeah, you can add representations to any value including integers.

Take the "Properties" `ContainerRepresentation` from the "Full prepared parameters" and attach it to the integer value in "Prepared Parameters". Then you can unfold the integer the same way.

You can name the representation or set `$implicit_label` to `true` in the constructor to get rid of the tab UI altogether. Whether you want to loop through parsing them one at a time or just parse your `stdClass` and nab the representation contents is up to you.

(You can also use `addRepresentation(..., 0)` to put your "Prepared Database Query" tab in front if you use it more than "Properties")

**Comment by HLeithner** [comment]
Perfect works as expected. thanks
![image](https://github.com/user-attachments/assets/b90cdd9c-53ba-48be-ae6c-7f4932b85323)

other side question, is it possible to show rendered HTML?

**Comment by jnvsor** [comment]
Not without a renderer plugin, no. (And needless to say arbitrary HTML output would break too much to put in kint core)

You can just subclass whatever type it is (Probably a `StringValue`) set a hint, then make a renderer plugin for it. Or better yet add a representation for it since that sounds like what you want.

Take a look at how `TableRepresentation` interacts with `Rich\TablePlugin` via `RichRenderer::$tab_plugins` and then make your own representation and render plugin based on that

**Comment by HLeithner** [comment]
It took me sometime but finally I got what I wanted.

![image](https://github.com/user-attachments/assets/35c161f9-3b2f-4b57-b789-3248ff339a86)

thanks for your help
