### ISSUE TITLE
The browser console cannot be expanded

### ISSUE THREAD

**Issue by iygwei** [kint-php/kint#434]
![image](https://github.com/user-attachments/assets/dae0c7ad-290c-4889-a24e-e1d6d2aa9c91)
I can't expand it as shown

 Kint::$expanded = true; I can't open them all

![image](https://github.com/user-attachments/assets/18704dca-1e5d-4f7e-bdb8-151a27402c6b)

**Comment by jnvsor** [comment]
To clarify: We're talking about the mini-trace not opening with `Kint::$expanded = true` yes? Not the dump above

Or are you having trouble opening dumps at all?

**Comment by iygwei** [comment]
> To clarify: We're talking about the mini-trace not opening with `Kint::$expanded = true` yes? Not the dump above
> 
> Or are you having trouble opening dumps at all?

yes ，I set

**Comment by iygwei** [comment]
If you're using it on Postman, the '+' button below cannot be clicked.

**Comment by jnvsor** [comment]
Ah right since there's no JS in that context... Can you confirm if 29d3cb845ff5a92c978046b1e8d461aefff11b62 does what you want?

**Comment by iygwei** [comment]
> Ah right since there's no JS in that context... Can you confirm if [29d3cb8](https://github.com/kint-php/kint/commit/29d3cb845ff5a92c978046b1e8d461aefff11b62) does what you want?啊，因为在这种情况下没有 JS...你能确认一下吗[ 29d3cb8 ](https://github.com/kint-php/kint/commit/29d3cb845ff5a92c978046b1e8d461aefff11b62)做你想要的吗？
I am php7.1
![image](https://github.com/user-attachments/assets/1d9f8679-9a83-494f-a9e0-ee6edd42f498)

**Comment by iygwei** [comment]
has_children 是false

**Comment by jnvsor** [comment]
Oh I see... I'm not going to do feature requests for 5.x going forward. 7.1 is 8 years old so you should probably upgrade. But you should be able to patch postRender yourself if you really need it.

Otherwise you can dump an expanded trace if you really want to see where it is:

```php
+Kint::trace();
```

**Comment by iygwei** [comment]
How do I fix this without modifying your source code? +Kint::trace(); I've tried not to unfold it

**Comment by jnvsor** [comment]
If you must you can extend `RichRenderer`, copy the modified `postRender` (Or regex replace it), and update `Kint::$renderers`

I'm off to work, I'll respond later today

**Comment by jnvsor** [comment]
Added in 1d02bb2329a7b9fa31786bccfe23eef7469decc0

If you need support below 7.4 you'll still have to roll your own
