### ISSUE TITLE
Ability to disable "d" keyboard shortcut?

### ISSUE THREAD

**Issue by will123195** [kint-php/kint#47]
Having kint on the page interferes with my ability to type the letter `d` into an html form.  The keyboard navigation is great, usually, but I do not see an option in the config to disable it.  Is this currently an option?

**Comment by raveren** [comment]
yeah, no, it's not configurable currently, I'll make it so `d` is not captured if user is typing in an input field.

**Comment by raveren** [comment]
no longer a problem since f2cab96770, typing into any field does not trigger kint callbacks.
