### ISSUE TITLE
Add a new modifier or config value that will dump data to error_log()

### ISSUE THREAD

**Issue by ericthelin** [kint-php/kint#51]
I would like the option to send the dumps to the error log instead of the browser. In a perfect world there would be a modifier for this to send one message and there would be a config setting that would in effect turn that modifier on 100% of the time so that all output goes to the error_log.

**Comment by raveren** [comment]
I'm not too sure about this on the basis that it would encourage Kint usage in production environments. I use it there myself but I'm well aware of the tradeoffs and can fix bugs immediately. It's purely a development tool and I'd prefer it stayed that way. 

Having said that, I also have an extremely verbose error handling/reporting functionality that I built and use in my projects. Obviously, it heavily incorporates kint and I feel I'll be happy with its functionality and stability in approximately another year of real-world usage to release it to the public.

Until then, I'm leaving this issue open, but I'm very doubtful I'll implement it.

**Comment by ericthelin** [comment]
I am not thinking of the error_log usage as something that I would use in
production but rather a way to dump data in such a way that it doesn't
interfere with my page layout and shows up instantly instead of waiting for
the page to load completely with my other hack. But I suppose others may
use it differently...

**Comment by Gounlaf** [comment]
Hi,

I'm interesseted to for this "feature" ; I'm using kint for debuging, but I use it in two way : classic (via WebBrowser) and console (PHP-CLI ...) ;
In console mode, all html format is shown, and it's hard to debug =/

Thanks

**Comment by raveren** [comment]
Hey, @ericthelin, sorry for coming back to this so late, but how do you imagine handling the output? I can see that the [error_log](http://www.php.net/manual/en/function.error-log.php) calls must be pre-configured with destination and whatnot. I haven't used this ever, could you provide a working example, preferably of how you usually do it..

**Comment by ericthelin** [comment]
What I have been doing is almost exactly the same as the s() function.

``` php
   function l()
    {
        if (!Kint::enabled()) {
            return;
        }

        $argv = func_get_args();
        $out = '';
        foreach ($argv as $k => $v) {
            if ($k) {
                $out .= "\n\n";
            }
            $out .= kintLite($v);
        }
        error_log($out);
    }
```

This doesn't support writing to custom file locations for the error logging but if I were to add that I would add a static property of the Kint class for log destination and use that if it were set.

Something like:

``` php
if (!empty(Kint::$errorLogFile)) {
    error_log($out, 3, Kint::$errorLogFile);
} else {
    error_log($out);
}
```

Does that help? If not let me know.

**Comment by raveren** [comment]
Yes, thanks! How does this differ from directly writing to file though?

**Comment by raveren** [comment]
kint can return output and one can use it in any custom implementation now.
