### ISSUE TITLE
regression: expand modifier no longer works

### ISSUE THREAD

**Issue by raveren** [kint-php/kint#53]
since f2cab96770, need to rewrite this through decorator parameters, not js

**Comment by brianhwang123** [comment]
Hi, raveren

There is a minor bug. Line 229 of Kint.class.php should be
self::$maxLevels   = 0;
instead of = false.

Otherwise, when I add + modifier, it gives me only 1 level before "depth too great".

**Comment by raveren** [comment]
ah thanks, I missed this one change to push, I have a dev version with lots of experimental functionality and differences are many so I overlooked one.
