### ISSUE TITLE
Create stable tag for Composer installs

### ISSUE THREAD

**Issue by agentphoenix** [kint-php/kint#56]
Currently everything is displayed in Packagist with `dev-master` but doing so doesn't allow the package to be installed with a minimum stability of stable, only dev. To fix this, create a version tag so that Kint can be installed in stable Composer installs.

**Comment by raveren** [comment]
could you help me out on this? I've created the stable v0.9 version, but I'm not sure whether it had any effect:

https://github.com/raveren/kint/tree/v0.9
https://packagist.org/packages/raveren/kint

what should I do now?

**Comment by Rarst** [comment]
That `v0.9` shows up on packagist, however it doesn't fit semantic versioning Composer uses, drop the `v` prefix:

> This must follow the format of `X.Y.Z` with an optional suffix of `-dev`, `-alphaN`, `-betaN` or `-RCN`.

http://getcomposer.org/doc/04-schema.md#version

**Comment by raveren** [comment]
But it says here

http://getcomposer.org/doc/02-libraries.md#tags

> It should match 'X.Y.Z' or 'vX.Y.Z'

I'm confused. Will I definitely fix it by dropping the `v`?

**Comment by Rarst** [comment]
Well, it doesn't seem like there is anything to fix really - it's on packagist and seems to work just fine.

I would say it's better to stick with non-v as per spec, but it doesn't seem to matter that much.

**Comment by raveren** [comment]
So is there a stable tag now in packagist? I don't really use it myself...

**Comment by Rarst** [comment]
Yes, there is. _Look_ at your page there. :)

**Comment by raveren** [comment]
It doesn't say `stable` though :) ok, closing this, I suppose :)

**Comment by Rarst** [comment]
> It doesn't say stable though

There is no concept of single explicit stable version in Composer. You project simply has non-development versions and since they are comparable (thus the fuss with adhering to semantic versioning spec) the largest of them acts as de-facto current stable.

**Comment by raveren** [comment]
good to know, thanks for all the help!
