### ISSUE TITLE
Specify depth per dump.

### ISSUE THREAD

**Issue by cryptiklemur** [kint-php/kint#58]
Instead of a config wide depth level, can we have a per dump with a default? Or a per dump, with the config fallback

**Comment by raveren** [comment]
As per documentation in http://raveren.github.io/kint/ you can use `+dd($var)` to bypass nesting depth restrictions for that one call (to be clear, add a plus sign before kint dump).

**Comment by cryptiklemur** [comment]
Per the documentation, this only allows for ignoring the depth level in the upwards direction, and in an unlimited manner. 

What this was asking for, was a way to specify the exact depth, on a per dump basis

**Comment by raveren** [comment]
It removes depth restrictions on a per dump basis. I'm in the progress of writing custom shorthands functionality which will allow you to bind any config changes to a shorthand - eg. you will be able to create a wrapper `d8()` that will dump 8 levels deep.

**Comment by cryptiklemur** [comment]
Yeah, thats pretty much what i was asking for
