### ISSUE TITLE
ErrorException, Illegal offset type when using dd() and Closure type hinting

### ISSUE THREAD

**Issue by jasonlewis** [kint-php/kint#64]
I've come across some weird behavior when using `dd` with Kint. Consider the following class.

``` php
class Foo {

    public function bar(Closure $baz)
    {
        return call_user_func($baz);
    }

}
```

If you attempt to `dd` an instance of this class it will throw an `ErrorException`.

``` php
dd(new Foo);
```

The weird thing is, if you allow the method to receive a second argument it doesn't freak out on you.

``` php
class Foo {

    public function bar(Closure $baz, $qux)
    {
        return call_user_func($baz);
    }

}
```

`dd` on a new instance now and it works fine. The next really weird thing is if you reverse the order of the arguments it fails again with an `ErrorException`.

``` php
class Foo {

    public function bar($qux, Closure $baz)
    {
        return call_user_func($baz);
    }

}
```

I'm not really sure where to begin debugging this as I'm not familiar with Kints code base at all. Hopefully I've given enough information for you to be able to reproduce this.

Running PHP 5.4.13 as well.

**Comment by aljinovic** [comment]
I just bugfixed the "Illegal offset type" yesterday, could you download the latest master and check if it works now?

**Comment by jasonlewis** [comment]
Wonderful. Appears to be fixed. Cheers @aljinovic!
