### ISSUE TITLE
add option to collapse all children

### ISSUE THREAD

**Issue by winkbrace** [kint-php/kint#69]
When you for instance have an array of objects, you don't always want to see the contents of the objects, just the headers.

I imagine the icon to look like 3 horizontal lines

**Comment by raveren** [comment]
http://raveren.github.io/kint/#navigation

>  Left click anywhere on a collapsed dump to show its contents. Doing so on the leading [+] will un-collapse all levels of the dump as well.
> Double-clicking any plus sign will un-collapse all dumps on the page.

**Comment by winkbrace** [comment]
Ah, I see.

But how to close all child elements of an element after you opened them all?

**Comment by raveren** [comment]
Click the minus - that will collapse all children recursively then click next to it, it will show only immediate children of the selected node.

**Comment by winkbrace** [comment]
Thanks. :+1:

**Comment by joachim-n** [comment]
That's not really discoverable as a UI feature.
How about having 2 buttons, one to expand by one level and one to expand all children?

**Comment by raveren** [comment]
Hello, thanks for the input - and although I agree that it is a slight usability issue, cluttering the interface is not a solution unfortunately.

**Comment by joachim-n** [comment]
Coming from Drupal, where Kint is being used in the Devel module to output _massive_ arrays, not knowing how to collapse them down to see just the first level is a massive usability problem. I considered Kint completely unusable until I found this was possible.

**Comment by raveren** [comment]
Ok, I can feel your pain :) 

So what do you suggest, an another button is not an option IMO, a tooltip would be one solution that's easy to implement as well: on the [+] button `This button expands and collapses all nodes, click *next* to it to only collapse top level.`

What do you think?

**Comment by joachim-n** [comment]
> a tooltip would be one solution that's easy to implement as well

That would certainly help, but I'm not a UX expert -- I don't know if that would be sufficiently discoverable.

**Comment by raveren** [comment]
I'm guessing it's better than nothing, I'll add it.

**Comment by 0xCardiE** [comment]
We in drupal world were used to krumo, by default it only expanded top levels so we can get an overview of the object. Now Kint goes like this. 
![image](https://cloud.githubusercontent.com/assets/8969767/17940103/d77570a4-6a2d-11e6-90f9-a900b34a31c6.png)

and what I really want by default is this
![image](https://cloud.githubusercontent.com/assets/8969767/17940127/f6122f48-6a2d-11e6-8310-77fef60ad46a.png)

So maybe some modifier in config files, where we can add (open only first level) would be good. But I would also say that would be best UX for all anyway, but if people differ with that, at least to have option to set it like that. I know 99% of drupal people would use that setting.

**Comment by jnvsor** [comment]
> Click the minus - that will collapse all children recursively then click next to it, it will show only immediate children of the selected node.

**Comment by 0xCardiE** [comment]
Maybe I am using different version of KINT. I dont see any next. But it does work when I click on the whole highlighted area as I wanted it to work.

**Comment by jnvsor** [comment]
> I dont see any next.

Have trouble finding the "Any" key too? :)

**Comment by 0xCardiE** [comment]
I was reading above where it says
"This button expands and collapses all nodes, click _next_ to it to only collapse top level." so somehow I got it that it must say _next_  :)  but when I read it now, I see I got it wrong.

**Comment by jnvsor** [comment]
Anyway, the question of the button's lack of clarity continues at #191
