### ISSUE TITLE
show __toString info on objects header row

### ISSUE THREAD

**Issue by winkbrace** [kint-php/kint#70]
When an object has a __toString() function, get it and display it in the header row. Handy for understanding at a glance collapsed objects.

**Comment by aljinovic** [comment]
Calling methods from an object can cause problems that can not be predicted, since __toString(), like any other method, can execute any code, causing errors or performance issues. If you plan on adding this functionality, please make it optional and off by default in configuration.

**Comment by raveren** [comment]
Sorry, will not be implementing this. I even opted out unserializing applicable strings so as not to trigger `__wakeup` methods. 

Too risky business, wouldn't be comfortable having a ticking timebomb in Kint code.

**Comment by winkbrace** [comment]
Okay, I hadn't thought of it like that. I'll just make a plugin for my own
use then. :)

;} Bas de Ruiter

2013/6/6 Rokas Šleinius notifications@github.com

**Comment by raveren** [comment]
If you go around doing it, it's very simple - just create a new parser in `kint\parsers` directory. You might create a pull request, I'll accept it once I create a parser management system of some kind.
