### ISSUE TITLE
dd() no styling

### ISSUE THREAD

**Issue by dragonfire1119** [kint-php/kint#74]
I noticed when you use dd() it as no style to it and it looks like text output only. With d() you get to see the styling. So I don't know if this is a bug because I just found this and so far it's really nice idea & very helpful. Thanks for making Kint.

**Comment by raveren** [comment]
Hey there, thanks for the kind words.

Unfortunately, I'll need more info to solve your problem, what does the page source look like, does `dd()` output differ from `s()` and `sd()` or is it just unstyled? What browser do you use? The more info the better.

**Comment by dragonfire1119** [comment]
I made pics of what you wanted here they are http://dragonfire1119.com/kint-issue/ If you need anything else to solve this just ask.

**Comment by raveren** [comment]
404 :)

**Comment by dragonfire1119** [comment]
Sorry about that you can see it now.

**Comment by raveren** [comment]
``````
"NetworkError: 403 FORBIDDEN - https://dl-web.dropbox.com/get/Kint/s%28%29-kint.png?w=AADg-1btwENER6dSzjKOOUwlGGHItmAOUJal-YvV3uYP-g"
s()-ki...V3uYP-g
"NetworkError: 403 FORBIDDEN - https://dl-web.dropbox.com/get/Kint/dd%28%29-kint.png?w=AAAUFo1vAZouzHYdrPDEqr3sCjo1PAh4nWvESWizSiNmQQ"
dd()-k...zSiNmQQ
"NetworkError: 403 FORBIDDEN - https://dl-web.dropbox.com/get/Kint/d%28%29-kint.png?w=AACGt0ghFBnwXmHbSU1doOTANHdruKfHieXIjuz3fJEujQ"
d()-ki...3fJEujQ
"NetworkError: 403 FORBIDDEN - https://dl-web.dropbox.com/get/Kint/sd%28%29-kint.png?w=AADwiA_G2CXiihyelV1VlULKXpTYZalHftcVbcvbQyhzhQ"
sd()-k...bQyhzhQ
"NetworkError: 403 FORBIDDEN - https://dl-web.dropbox.com/get/Kint/d%28%29-kint.png?w=AACGt0ghFBnwXmHbSU1doOTANHdruKfHieXIjuz3fJEujQ"
d()-ki...3fJEujQ
"NetworkError: 403 FORBIDDEN - https://dl-web.dropbox.com/get/Kint/s%28%29-kint.png?w=AADg-1btwENER6dSzjKOOUwlGGHItmAOUJal-YvV3uYP-g"
s()-ki...V3uYP-g
"NetworkError: 403 FORBIDDEN - https://dl-web.dropbox.com/get/Kint/sd%28%29-kint.png?w=AADwiA_G2CXiihyelV1VlULKXpTYZalHftcVbcvbQyhzhQ"
sd()-k...bQyhzhQ
"NetworkError: 403 FORBIDDEN - https://dl-web.dropbox.com/get/Kint/dd%28%29-kint.png?w=AAAUFo1vAZouzHYdrPDEqr3sCjo1PAh4nWvESWizSiNmQQ"```
``````

**Comment by dragonfire1119** [comment]
You should be able to see it now I put it on photobucket this time sorry about that.

**Comment by raveren** [comment]
There appears to be another function named `dd()` in your environment (which apparently directly maps to `print_r`). Kint only creates `dd()` if it's not already defined (`if(!function_exists('dd'))`).
