### ISSUE TITLE
ADD pretty-printed stderr dumps when run from console

### ISSUE THREAD

**Issue by mcd-php** [kint-php/kint#82]

**Comment by raveren** [comment]
This is actually my first priority right now before releasing v1.0.0. 

Unfortunately, the colors do not work on windows unless 3rd party packages are installed into the system.

**Comment by isimmons** [comment]
If you are referring to colors in cmd.exe IMHO I think it is safe to say windows users can just install conemu which works with ascii colors for things like phpunit, codeception, laravel artisan if they don't want to see those ugly ascii characters printed to the screen. BTW just found this package and am using it in Laravel. It's pretty awesome :-)
