### ISSUE TITLE
allow full depth parsing, get rid of *DEPTH TOO GREAT* warning

### ISSUE THREAD

**Issue by panique** [kint-php/kint#85]
### Problem

Currently **kint** only shows/parses some levels deep and gives out `DEPTH TOO GREAT` when going deeper with `d()`. This might be useful for performance issues, but breaks the sense of this wonderful tool.
### Solution

Parsing the full depth of a variable/object with `d()`. If this is a performance issue, then this should be an option that can be triggered by the user, like `d($stuff, $show_full_depth = false)`.

**Comment by aljinovic** [comment]
It is possible to override any Kint config property in runtime:

``` PHP
\Kint::$maxLevels = 0; // 0 equals no limit
d($whatever);
```

To change the setting globally, using Kint config file:

``` PHP
$_kintSettings['maxLevels'] = X; // X being number of levels
```

**Comment by panique** [comment]
Awesome! Thanks a lot! This should be part of the README.

**Comment by panique** [comment]
Btw there's typo in your comment: Needs to be
`\Kint::$maxLevels = 0;` (with an `;` not a `:`)

:+1:

**Comment by aljinovic** [comment]
Fixed ;)

**Comment by raveren** [comment]
there's more: 

http://raveren.github.io/kint/#advanced

``` php
+d($stuff);
```

will bypass any depth and length restrictions **on the fly**.

**Comment by NabiKAZ** [comment]
Test in PHP 7.2.2 (cli)

This don't work:
```PHP
\Kint::$maxLevels = 0;

Fatal error: Uncaught Error: Access to undeclared static property: Kint\Kint::$maxLevels
```

This don't work:
```PHP
$_kintSettings['maxLevels'] = 0;
```

This works:
```PHP
+d($x);
```

**Comment by jnvsor** [comment]
@NabiKAZ That's because this is a 5 year old thread and it's `Kint::$max_depth` now
