### ISSUE TITLE
Cache duplicate information with javascript to save render time and bandwidth

### ISSUE THREAD

**Issue by raveren** [kint-php/kint#91]
- Show static properties in the same place with dynamic ones
- Class definition and documentation, links to online APIs, methods and constants should only be printed once (click to open in another window?)
- Parent classes of displayed ones are saved separately in case different inherited ones are displayed on the page.

**Comment by raveren** [comment]
Object name looks like this:

_ClassName_ <sup>[?]</sup>

Clicking on question mark opens documentation in new window, clicking className will go to its definition in source if applicable

**Comment by jnvsor** [comment]
Partial dupe of #39

I think only printing methods and constants once would be great but I also think it'll need some javascript magic because of the access paths (They definitely aren't the same even if the contents are)

**Comment by jnvsor** [comment]
pretty much superceded by #242
